// SPDX-License-Identifier: CC-BY-2.0-FR
//
// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).
// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>
//
// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.
// "changed: true" means that we expanded a contraction, for example "don't" to "do not".
// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.

import type { TatoebaEntry } from '../bank'

export const TATOEBA_0010_BANK: readonly TatoebaEntry[] = [
  {
    word: "kettle",
    sentences: [
      { id: 2537229, text: "Tom filled the kettle with water and put it on the stove." },
      { id: 12853359, text: "Do you want to make tea? First you have to fill the kettle with water." },
      { id: 13482245, text: "Is there hot water in the kettle?" },
    ],
  },
  {
    word: "limp",
    sentences: [
      { id: 303562, text: "He walked with a limp." },
      { id: 9933380, text: "I can finally walk without a limp." },
      { id: 321112, text: "The hat got wet and went limp." },
    ],
  },
  {
    word: "movements",
    sentences: [
      { id: 12148931, text: "Dance is a set of movements that are performed following the rhythm of the music." },
      { id: 7117419, text: "I tried not to make any sudden movements." },
      { id: 7895018, text: "Do not make sudden movements when you drive.", changed: true },
    ],
  },
  {
    word: "discovery",
    sentences: [
      { id: 7483273, text: "Who made this remarkable discovery?" },
      { id: 3217417, text: "The scientist made a significant discovery." },
      { id: 299364, text: "He made an important scientific discovery." },
    ],
  },
  {
    word: "comforting",
    sentences: [
      { id: 12106072, text: "Thank you for your comforting words." },
      { id: 12071930, text: "What a comforting thought!" },
      { id: 325603, text: "Nothing is more comforting than kindness offered to us while traveling." },
    ],
  },
  {
    word: "direct",
    sentences: [
      { id: 680695, text: "Can you direct me to the train station?" },
      { id: 1216266, text: "Traffic lights are used to direct traffic." },
      { id: 11550435, text: "Let me give you a direct answer." },
    ],
  },
  {
    word: "concrete",
    sentences: [
      { id: 12130303, text: "Is this wall made of concrete?" },
      { id: 48309, text: "The building will be made of concrete on a steel framework." },
      { id: 10612154, text: "There were not nearly enough concrete blocks to build that bridge." },
    ],
  },
  {
    word: "eyelids",
    sentences: [
      { id: 4649306, text: "My eyelids are heavy." },
      { id: 2947372, text: "Camels have three eyelids." },
      { id: 9851484, text: "Were your eyelids stuck together when you woke up this morning?" },
    ],
  },
  {
    word: "patches",
    sentences: [
      { id: 11641457, text: "A few patches of woods surrounded the houses." },
      { id: 4848894, text: "These days, people rarely wear patches on their elbows and knees." },
    ],
  },
  {
    word: "tasty",
    sentences: [
      { id: 12387494, text: "The food was very tasty." },
      { id: 8625012, text: "Why is this bread so tasty?" },
      { id: 13593207, text: "Tom prepared a very tasty meal for us." },
    ],
  },
  {
    word: "rivers",
    sentences: [
      { id: 4398669, text: "Most rivers flow to the sea." },
      { id: 2951283, text: "Some fish live in rivers, others in the sea." },
      { id: 239997, text: "The water in lakes and rivers is usually fresh." },
    ],
  },
  {
    word: "swift",
    sentences: [
      { id: 325455, text: "The stream is not very swift." },
      { id: 6606574, text: "The journey was a swift and pleasant one." },
      { id: 4520281, text: "Have you ever seen a swift?" },
    ],
  },
  {
    word: "necks",
    sentences: [
      { id: 8547048, text: "Giraffes are famous for their long necks." },
      { id: 4211734, text: "The girls wore grass skirts and had flowers around their necks." },
      { id: 1155815, text: "The water came up to our necks." },
    ],
  },
  {
    word: "clothing",
    sentences: [
      { id: 5296243, text: "We need food, clothing, and shelter to live." },
      { id: 1365758, text: "Is there a clothing store near here?" },
      { id: 11018556, text: "Do you always wear black clothing?" },
    ],
  },
  {
    word: "constant",
    sentences: [
      { id: 57799, text: "There is a constant flow of traffic on this road." },
      { id: 1453565, text: "Languages are subject to constant change." },
      { id: 10532802, text: "Sheep need constant access to fresh water." },
    ],
  },
  {
    word: "gown",
    sentences: [
      { id: 11637043, text: "My dressing gown is lovely and fluffy." },
      { id: 6549412, text: "Mary wore a beautiful evening gown to the party." },
      { id: 10895379, text: "After finishing her bath, Mary dried herself off and put on her dressing gown." },
    ],
  },
  {
    word: "winds",
    sentences: [
      { id: 6555123, text: "The strong winds knocked down a lot of tree branches last night." },
      { id: 19181, text: "Strong winds stripped the tree of its leaves." },
      { id: 11296781, text: "Today is a fine day with gentle winds." },
    ],
  },
  {
    word: "impression",
    sentences: [
      { id: 3823585, text: "We need to make a good first impression." },
      { id: 13882383, text: "Tom made a good impression on me." },
      { id: 11511744, text: "What was your first impression of him?" },
    ],
  },
  {
    word: "performance",
    sentences: [
      { id: 2649706, text: "Tom gave a first-class performance." },
      { id: 3534649, text: "Did you enjoy the performance last night?" },
      { id: 11271589, text: "The team put up a great performance at the show last night." },
    ],
  },
  {
    word: "hammer",
    sentences: [
      { id: 9439872, text: "I hit my finger with a hammer." },
      { id: 7774342, text: "Do you have a hammer I can borrow?" },
      { id: 8080233, text: "Hand that hammer to me." },
    ],
  },
  {
    word: "stool",
    sentences: [
      { id: 12116096, text: "Use a step stool if necessary to reach higher shelves safely." },
      { id: 8068846, text: "Bring a stool from the kitchen." },
      { id: 3223095, text: "Tom sat on a stool at the counter." },
    ],
  },
  {
    word: "ache",
    sentences: [
      { id: 7822763, text: "Suddenly I felt a strong stomach ache." },
      { id: 2762760, text: "Does your head still ache?" },
      { id: 4284642, text: "Do you have a stomach ache?" },
    ],
  },
  {
    word: "intense",
    sentences: [
      { id: 30210, text: "Far from stopping, the storm became much more intense." },
      { id: 6820258, text: "An intense heat wave is predicted." },
      { id: 280136, text: "I had an intense pain in the head." },
    ],
  },
  {
    word: "bubbles",
    sentences: [
      { id: 245687, text: "The children are blowing bubbles." },
      { id: 12310770, text: "The boy blows soap bubbles." },
      { id: 10294469, text: "The scientists study the air bubbles in the ice." },
    ],
  },
  {
    word: "efforts",
    sentences: [
      { id: 8423810, text: "Thanks to her tireless efforts, we reached our goal." },
      { id: 1933582, text: "I appreciate your efforts to help me." },
      { id: 11733013, text: "If we combine our efforts, we will achieve our goal.", changed: true },
    ],
  },
  {
    word: "thirsty",
    sentences: [
      { id: 866125, text: "I drink water because I am thirsty." },
      { id: 10165289, text: "I was thirsty and wanted something cold to drink." },
      { id: 1190474, text: "By the end of the trip we were very thirsty." },
    ],
  },
  {
    word: "elderly",
    sentences: [
      { id: 1025693, text: "Tom gave his seat to an elderly lady." },
      { id: 11241762, text: "The young man helps the elderly woman cross the street." },
      { id: 427774, text: "An elderly person was resting under a tree." },
    ],
  },
  {
    word: "advanced",
    sentences: [
      { id: 11746554, text: "You can take advanced classes in school to challenge yourself." },
      { id: 10681523, text: "Do you have an advanced or beginner level?" },
      { id: 10172802, text: "The work is at a very advanced stage." },
    ],
  },
  {
    word: "schools",
    sentences: [
      { id: 3802064, text: "The schools are closed today because of the snow." },
      { id: 12442613, text: "Is French taught in primary schools?" },
      { id: 7542151, text: "Tom teaches at three different schools." },
    ],
  },
  {
    word: "operation",
    sentences: [
      { id: 11776180, text: "The rescue operation was successful." },
      { id: 45636, text: "The system will go into operation in a short time." },
      { id: 48515, text: "The plan was put into operation." },
    ],
  },
  {
    word: "title",
    sentences: [
      { id: 5190603, text: "Do you remember the title of that book?" },
      { id: 6173069, text: "Tom is writing a book, but it does not have a title yet." },
      { id: 1898013, text: "What is the title of the book you are reading?", changed: true },
    ],
  },
  {
    word: "fiery",
    sentences: [
      { id: 4873656, text: "The sun was setting a fiery red." },
      { id: 18272, text: "The sky was fiery with the setting sun." },
    ],
  },
  {
    word: "dazzling",
    sentences: [
      { id: 9939368, text: "Tom has a dazzling smile." },
      { id: 8928901, text: "The sun is dazzling." },
      { id: 9019956, text: "He has dazzling white teeth." },
    ],
  },
  {
    word: "bitter",
    sentences: [
      { id: 9522961, text: "Do you have sugar? The tea is very bitter." },
      { id: 28814, text: "We were all shaking from the bitter cold." },
      { id: 6539566, text: "A bitter winter is setting in." },
    ],
  },
  {
    word: "cousins",
    sentences: [
      { id: 6263384, text: "How many cousins do you have?" },
      { id: 8340924, text: "One of my cousins is visiting us this coming weekend." },
      { id: 9966277, text: "My cousins live on the beach." },
    ],
  },
  {
    word: "stove",
    sentences: [
      { id: 2956723, text: "Tom filled the pot with water and put it on the stove." },
      { id: 11887069, text: "Clean the stove and oven after cooking." },
      { id: 13870591, text: "Do you have a gas stove or an electric one?" },
    ],
  },
  {
    word: "circular",
    sentences: [
      { id: 6825647, text: "The swimming pool we swam in yesterday had a circular shape." },
      { id: 49374, text: "The house looks circular, but it is not a complete circle.", changed: true },
    ],
  },
  {
    word: "solution",
    sentences: [
      { id: 2662923, text: "There must be a solution to this problem." },
      { id: 8215760, text: "Have you found the solution to the problem?" },
      { id: 7218887, text: "Can you think of any good solution to this problem?" },
    ],
  },
  {
    word: "brass",
    sentences: [
      { id: 270718, text: "A brass band is marching along the street." },
      { id: 11045298, text: "Her coat has big brass buttons." },
      { id: 257302, text: "I like my old brass tea pot." },
    ],
  },
  {
    word: "picnic",
    sentences: [
      { id: 11113433, text: "What a beautiful day for a picnic!" },
      { id: 2820757, text: "Tom and Mary are planning a picnic at the lake." },
      { id: 10771353, text: "Can you recommend a good place to have a picnic?" },
    ],
  },
  {
    word: "dash",
    sentences: [
      { id: 4311253, text: "Would you like a dash of milk in your tea?" },
      { id: 5345324, text: "Tom won the hundred-yard dash." },
      { id: 26828, text: "After the rain had let up a bit, we made a dash for the car." },
    ],
  },
  {
    word: "gifts",
    sentences: [
      { id: 5284367, text: "Giving gifts is always nicer than receiving them." },
      { id: 12932141, text: "People often exchange gifts on Christmas morning." },
      { id: 11371544, text: "What gifts did you get for Christmas?" },
    ],
  },
  {
    word: "intelligent",
    sentences: [
      { id: 270253, text: "All human beings are much more intelligent than animals." },
      { id: 13477359, text: "Humans are the most intelligent of all animals." },
      { id: 3672911, text: "Mary was a very intelligent, but very quiet girl." },
    ],
  },
  {
    word: "marble",
    sentences: [
      { id: 9974427, text: "The columns were made of marble." },
      { id: 680978, text: "Marble floors are beautiful." },
      { id: 10919285, text: "The sink is made of marble." },
    ],
  },
  {
    word: "connection",
    sentences: [
      { id: 5906259, text: "Tom has a strong connection with nature." },
      { id: 2885750, text: "My sister and I have a very strong connection." },
      { id: 11484145, text: "I have a strong connection to him." },
    ],
  },
  {
    word: "screech",
    sentences: [
      { id: 4316931, text: "The owl gave a loud screech." },
      { id: 8572645, text: "He heard a car screech." },
      { id: 11219149, text: "A screech rang out through the air." },
    ],
  },
  {
    word: "suggestion",
    sentences: [
      { id: 1322224, text: "Do you have a better suggestion?" },
      { id: 252003, text: "My friend put forward a good suggestion." },
      { id: 2982980, text: "I have a suggestion for you." },
    ],
  },
  {
    word: "judge",
    sentences: [
      { id: 1517920, text: "You should judge a tree by its fruits." },
      { id: 6049452, text: "Who am I to judge other people?" },
      { id: 10241508, text: "The judge read out the ruling." },
    ],
  },
  {
    word: "puddle",
    sentences: [
      { id: 3403293, text: "Tom stepped in a puddle of water." },
      { id: 3446922, text: "Tom jumped over the puddle." },
      { id: 693402, text: "A passing car hit a puddle and splashed water all over me." },
    ],
  },
  {
    word: "flow",
    sentences: [
      { id: 12664703, text: "Let the water flow, will you!" },
      { id: 11551370, text: "The water continued to flow from the tap." },
      { id: 12770694, text: "Why does the river flow so gently?" },
    ],
  },
  {
    word: "outer",
    sentences: [
      { id: 5647181, text: "Have you ever been to outer space?" },
      { id: 1488106, text: "Is there life in outer space?" },
      { id: 680896, text: "Have you thought about exploring outer space?" },
    ],
  },
  {
    word: "patterns",
    sentences: [
      { id: 12071393, text: "Humans and cats have very different sleeping patterns." },
      { id: 277153, text: "Global warming will change the patterns of the weather world-wide." },
      { id: 5906029, text: "The human mind often sees patterns where there are none." },
    ],
  },
  {
    word: "lunchtime",
    sentences: [
      { id: 7899854, text: "Tom stayed in bed until lunchtime." },
      { id: 8883916, text: "The shop is also open at lunchtime." },
      { id: 6664292, text: "I was very hungry by lunchtime." },
    ],
  },
  {
    word: "maps",
    sentences: [
      { id: 9333119, text: "Are you good at reading maps?" },
      { id: 10603650, text: "The blue lines on the maps are rivers." },
      { id: 802629, text: "Both men drew maps and pictures of what they saw." },
    ],
  },
  {
    word: "bacon",
    sentences: [
      { id: 9705178, text: "Do you want bacon and eggs for breakfast?" },
      { id: 5810760, text: "We ate bacon and eggs." },
      { id: 6577453, text: "How many slices of bacon?" },
    ],
  },
  {
    word: "mistakes",
    sentences: [
      { id: 30386, text: "Be more careful, or you will make mistakes." },
      { id: 6064005, text: "Everyone makes mistakes from time to time." },
      { id: 11603378, text: "We should allow Tom to learn from his mistakes." },
    ],
  },
  {
    word: "target",
    sentences: [
      { id: 2259961, text: "You are aiming too low to hit the target.", changed: true },
      { id: 5275107, text: "Tom was right on target." },
      { id: 11636403, text: "Who is the target audience for this book?" },
    ],
  },
  {
    word: "urgent",
    sentences: [
      { id: 12372251, text: "Hurry; the matter is urgent." },
      { id: 903700, text: "There is an urgent need for more money." },
      { id: 19732, text: "I have an urgent matter to attend to." },
    ],
  },
  {
    word: "exchange",
    sentences: [
      { id: 267205, text: "A girl gave me an orange in exchange for a piece of cake." },
      { id: 21981, text: "The exchange rates for foreign currency change daily." },
      { id: 321408, text: "Will you exchange seats with me?" },
    ],
  },
  {
    word: "positive",
    sentences: [
      { id: 24621, text: "Try to have a positive attitude about everything." },
      { id: 11505584, text: "The film received mainly positive reviews." },
      { id: 13018897, text: "Habits can be both positive and negative." },
    ],
  },
  {
    word: "gloomy",
    sentences: [
      { id: 10682241, text: "The room was gloomy and cold." },
      { id: 8659197, text: "The library is dark and gloomy." },
      { id: 13855300, text: "Today, the weather is gloomy." },
    ],
  },
  {
    word: "tickets",
    sentences: [
      { id: 8299423, text: "Can tickets for the concert be bought here?" },
      { id: 3554938, text: "Where do you buy bus tickets?" },
      { id: 11107316, text: "We lined up to get tickets for the concert." },
    ],
  },
  {
    word: "reaction",
    sentences: [
      { id: 60748, text: "What was his reaction to this news?" },
      { id: 8587248, text: "My first reaction was to laugh." },
      { id: 2470562, text: "A chemical reaction takes place in one or more steps." },
    ],
  },
  {
    word: "owners",
    sentences: [
      { id: 8456693, text: "Dogs often get very excited when their owners get home." },
      { id: 8456469, text: "Most dog owners treat their dogs well." },
      { id: 13816230, text: "Are you the owners of this house?" },
    ],
  },
  {
    word: "companion",
    sentences: [
      { id: 13756296, text: "A dog is a faithful companion." },
      { id: 8456544, text: "My dog is a good companion." },
      { id: 12995363, text: "Have you ever wished for a companion animal?" },
    ],
  },
  {
    word: "frogs",
    sentences: [
      { id: 12296691, text: "There are many frogs in this pond." },
      { id: 7920308, text: "How long do frogs live?" },
      { id: 11726755, text: "Do all frogs have webbed feet?" },
    ],
  },
  {
    word: "shallow",
    sentences: [
      { id: 11736378, text: "The water was too shallow for swimming." },
      { id: 273202, text: "The river is shallow here. We can walk across." },
      { id: 14040340, text: "The sea is deep; the stream is shallow." },
    ],
  },
  {
    word: "splendid",
    sentences: [
      { id: 54772, text: "I never saw such a splendid sunset." },
      { id: 1160203, text: "What a splendid city!" },
      { id: 44404, text: "We had a splendid dinner that evening." },
    ],
  },
  {
    word: "results",
    sentences: [
      { id: 681932, text: "What were the results of the test?" },
      { id: 6528699, text: "Tom is quite pleased with the results." },
      { id: 6153571, text: "Although we worked hard, we are not getting good results." },
    ],
  },
  {
    word: "gentlemen",
    sentences: [
      { id: 38531, text: "Please be seated, ladies and gentlemen." },
      { id: 5821013, text: "Ladies and gentlemen, welcome on board." },
      { id: 1597893, text: "Good evening, ladies and gentlemen." },
    ],
  },
  {
    word: "trade",
    sentences: [
      { id: 3439677, text: "Would you like to trade jobs?" },
      { id: 2252386, text: "Do you want to trade our two sheep, one for another?" },
      { id: 275280, text: "Foreign trade brings in a large income." },
    ],
  },
  {
    word: "blocks",
    sentences: [
      { id: 3577726, text: "Cells are the building blocks of life." },
      { id: 9289856, text: "Walk two blocks and turn right." },
      { id: 10618932, text: "I rode my bike seven blocks to school." },
    ],
  },
  {
    word: "design",
    sentences: [
      { id: 11892929, text: "Have you chosen a house design?" },
      { id: 12201580, text: "Tom helped design this building." },
      { id: 8381070, text: "Tom was the one that came up with the design." },
    ],
  },
  {
    word: "professional",
    sentences: [
      { id: 564488, text: "My son wants to become a professional golf player." },
      { id: 4014247, text: "Tom has always wanted to be a professional musician." },
      { id: 3959010, text: "As a young girl, Mary wanted to become a professional tennis player." },
    ],
  },
  {
    word: "pyjamas",
    sentences: [
      { id: 12075544, text: "Put your pyjamas on, and go and clean your teeth." },
      { id: 10639610, text: "Do you wear pyjamas when you sleep?" },
      { id: 10639545, text: "What colour are your pyjamas?" },
    ],
  },
  {
    word: "chains",
    sentences: [
      { id: 7472214, text: "Tom and Mary oiled their bicycles chains." },
      { id: 9823664, text: "We need to buy chains for our car." },
      { id: 886209, text: "The trap is made of strong chains." },
    ],
  },
  {
    word: "soil",
    sentences: [
      { id: 268575, text: "Plants take in water from the soil." },
      { id: 10369147, text: "Cover the seeds with a bit of soil." },
      { id: 11505157, text: "Children love to play in the soil." },
    ],
  },
  {
    word: "scarf",
    sentences: [
      { id: 10730997, text: "Put a scarf on and keep warm." },
      { id: 13598695, text: "Do you wear a scarf in winter?" },
      { id: 8099507, text: "Mary was wearing a blue scarf." },
    ],
  },
  {
    word: "forms",
    sentences: [
      { id: 4015853, text: "Please fill out these forms." },
      { id: 325517, text: "Travel is one of the better forms of education." },
      { id: 271366, text: "There are several forms of government." },
    ],
  },
  {
    word: "doctors",
    sentences: [
      { id: 10677306, text: "Experienced doctors and nurses helped them." },
      { id: 32794, text: "More and more doctors have begun to use the new medicine." },
      { id: 4663572, text: "Do you know any doctors who speak French?" },
    ],
  },
  {
    word: "striped",
    sentences: [
      { id: 8381241, text: "Tom is wearing a blue and white striped shirt." },
      { id: 13255720, text: "The man was wearing a striped shirt." },
      { id: 10044612, text: "The shirt is striped." },
    ],
  },
  {
    word: "amusement",
    sentences: [
      { id: 10504166, text: "There are many rides in this amusement park." },
      { id: 10324275, text: "We had fun at the amusement park." },
      { id: 4013856, text: "When was the last time you went to an amusement park?" },
    ],
  },
  {
    word: "scrap",
    sentences: [
      { id: 258061, text: "I wrote down his phone number on a scrap of paper." },
      { id: 9271067, text: "Tom sold his car for scrap." },
      { id: 2661465, text: "The old car was taken for scrap." },
    ],
  },
  {
    word: "bowls",
    sentences: [
      { id: 4132901, text: "How many bowls of soup did you eat?" },
      { id: 10959806, text: "Rice is often served in round bowls." },
      { id: 10345519, text: "All of our plates and bowls are white." },
    ],
  },
  {
    word: "puzzle",
    sentences: [
      { id: 2065271, text: "Can you guys solve the puzzle?" },
      { id: 276583, text: "No one could solve the puzzle." },
      { id: 11764656, text: "The puzzle pieces fell into place." },
    ],
  },
  {
    word: "oven",
    sentences: [
      { id: 34929, text: "Bread is baked in an oven." },
      { id: 5190608, text: "Tom put the cake in the oven." },
      { id: 2678270, text: "The bread is baking in the oven." },
    ],
  },
  {
    word: "mornings",
    sentences: [
      { id: 21166, text: "I find it hard to get up early on cold mornings." },
      { id: 2761502, text: "I love to walk along the river in the mornings." },
      { id: 13583417, text: "I only drink coffee in the mornings." },
    ],
  },
  {
    word: "relatives",
    sentences: [
      { id: 251262, text: "All my relatives live in this city." },
      { id: 8007064, text: "I have relatives who live in this area." },
      { id: 4786609, text: "Tom is staying with his relatives." },
    ],
  },
  {
    word: "sale",
    sentences: [
      { id: 9420310, text: "Are any of these boats for sale?" },
      { id: 5726156, text: "We held a yard sale last weekend." },
      { id: 7374950, text: "Mary is putting her house up for sale." },
    ],
  },
  {
    word: "cases",
    sentences: [
      { id: 11959709, text: "In most cases, her answers are right." },
      { id: 838717, text: "There are some cases where this rule does not apply." },
      { id: 875570, text: "In many cases, doing that is impossible." },
    ],
  },
  {
    word: "reward",
    sentences: [
      { id: 3186814, text: "Tom offered a reward for the return of his lost dog." },
      { id: 9954969, text: "There is a reward if you help find their missing dog." },
      { id: 11888970, text: "Set goals for yourself and reward yourself after completing each task." },
    ],
  },
  {
    word: "lions",
    sentences: [
      { id: 280235, text: "Some animals, such as lions, eat meat." },
      { id: 11344740, text: "I love going to the zoo to see lions." },
      { id: 6122928, text: "Adult male lions have a large mane." },
    ],
  },
  {
    word: "cameras",
    sentences: [
      { id: 8898963, text: "There are security cameras everywhere." },
      { id: 6497220, text: "Tom and Mary always carry cameras with them wherever they go." },
      { id: 11596355, text: "Every school in the area has security cameras." },
    ],
  },
  {
    word: "glory",
    sentences: [
      { id: 8174514, text: "Tom restored the garden to its former glory." },
      { id: 262944, text: "We ran for the glory of the school." },
    ],
  },
  {
    word: "elegant",
    sentences: [
      { id: 7285237, text: "Mary wore a simple, yet elegant dress." },
      { id: 8999751, text: "You look very elegant today." },
      { id: 10317944, text: "Mary has some elegant dresses." },
    ],
  },
  {
    word: "invitation",
    sentences: [
      { id: 10143058, text: "I got an invitation to join their club." },
      { id: 31992, text: "Mary declined an invitation to the concert." },
      { id: 10960201, text: "Admission will be by invitation only." },
    ],
  },
  {
    word: "handkerchief",
    sentences: [
      { id: 3496788, text: "Tom took out his handkerchief and blew his nose." },
      { id: 66096, text: "Always keep a handkerchief in your pocket." },
      { id: 11790677, text: "Tom dried his tears with his handkerchief." },
    ],
  },
  {
    word: "mobile",
    sentences: [
      { id: 1213535, text: "Most young people have mobile phones." },
      { id: 12755721, text: "Please turn off your mobile phones." },
      { id: 2693545, text: "Can I have your mobile number?" },
    ],
  },
  {
    word: "snacks",
    sentences: [
      { id: 11817672, text: "Make sure to bring snacks and plenty of water." },
      { id: 953269, text: "For snacks, she eats fruit or nuts." },
      { id: 13265367, text: "I make carrot sticks for school snacks." },
    ],
  },
  {
    word: "apples",
    sentences: [
      { id: 262689, text: "We picked apples so as to make a pie." },
      { id: 11303138, text: "I like to eat apples and oranges." },
      { id: 8388782, text: "Which do you like better, apples or pears?" },
    ],
  },
  {
    word: "loyal",
    sentences: [
      { id: 7732441, text: "Tom is very loyal to his friends." },
      { id: 13892473, text: "You can trust him, he is a loyal friend.", changed: true },
      { id: 6036328, text: "A loyal brother helps his sister." },
    ],
  },
  {
    word: "cleaner",
    sentences: [
      { id: 45763, text: "The river has become much cleaner than before." },
      { id: 8746756, text: "The air is much cleaner now." },
      { id: 6697628, text: "Tom is a window cleaner." },
    ],
  },
  {
    word: "layer",
    sentences: [
      { id: 10784705, text: "A thick layer of dust covered everything in the room." },
      { id: 1999296, text: "A fresh layer of snow covered the street." },
      { id: 7704416, text: "The layer of ice was thick enough to walk on." },
    ],
  },
  {
    word: "difficulty",
    sentences: [
      { id: 35339, text: "We had much difficulty in finding the bus stop." },
      { id: 12494531, text: "Did you have difficulty finding the way?" },
      { id: 6527520, text: "Tom should have no difficulty finding a job." },
    ],
  },
  {
    word: "storms",
    sentences: [
      { id: 682080, text: "There were many snow storms last winter." },
      { id: 13230365, text: "There is a chance of severe storms tonight." },
      { id: 1638054, text: "In the last weeks, there has been some strong storms." },
    ],
  },
  {
    word: "musical",
    sentences: [
      { id: 6772479, text: "Do you play any musical instruments?" },
      { id: 1327841, text: "Learning a musical instrument trains the mind." },
      { id: 9955397, text: "My favourite musical instrument is the electric guitar." },
    ],
  },
  {
    word: "ability",
    sentences: [
      { id: 10614784, text: "The ability to read faces is an essential skill." },
      { id: 6795271, text: "Intelligence is the ability to adapt to change." },
      { id: 1026458, text: "Tom did the job to the best of his ability." },
    ],
  },
  {
    word: "posters",
    sentences: [
      { id: 9826629, text: "I hung some posters on the wall." },
      { id: 11612604, text: "The walls of their room are covered in animal posters." },
    ],
  },
  {
    word: "packet",
    sentences: [
      { id: 10209264, text: "He opened a packet of biscuits." },
      { id: 10241782, text: "Another packet of sugar, please." },
      { id: 8788865, text: "This packet of sugar has holes in it." },
    ],
  },
  {
    word: "images",
    sentences: [
      { id: 7912018, text: "The university presents a photography exhibition with one hundred images." },
      { id: 11757036, text: "Why do certain images stick in the mind more than others?" },
      { id: 6133919, text: "Words that sound nice always contain beautiful images." },
    ],
  },
  {
    word: "twigs",
    sentences: [
      { id: 13753522, text: "The ground was covered with dry twigs." },
      { id: 13753520, text: "He broke some twigs for the fire." },
      { id: 62315, text: "Can you build a fire with twigs?" },
    ],
  },
  {
    word: "banks",
    sentences: [
      { id: 11217338, text: "What time do the banks open?" },
      { id: 273169, text: "The river flowed over its banks." },
      { id: 8826870, text: "The banks stay closed on Saturdays." },
    ],
  },
  {
    word: "wool",
    sentences: [
      { id: 249106, text: "We wear wool in winter." },
      { id: 684683, text: "Sheep are raised for their wool and meat." },
      { id: 9525152, text: "The shirt is made from pure wool." },
    ],
  },
  {
    word: "fascinating",
    sentences: [
      { id: 12169019, text: "What a fascinating place this is!" },
      { id: 11410444, text: "I find historic castles to be fascinating." },
      { id: 953456, text: "I found the subject fascinating." },
    ],
  },
  {
    word: "needle",
    sentences: [
      { id: 1017945, text: "Do you have needle and thread?" },
      { id: 11026625, text: "Please thread this needle for me." },
      { id: 436283, text: "I always carry a needle in case of an emergency." },
    ],
  },
  {
    word: "outfit",
    sentences: [
      { id: 12627000, text: "Do you have an outfit to wear to the dance?" },
      { id: 2643366, text: "Mary is wearing a new outfit." },
      { id: 13587238, text: "You look great in that white outfit." },
    ],
  },
  {
    word: "reassuring",
    sentences: [
      { id: 3591118, text: "That was very reassuring." },
      { id: 13259654, text: "He kept talking to her, reassuring her she was safe." },
      { id: 2543960, text: "Tom tried to be reassuring." },
    ],
  },
  {
    word: "slimy",
    sentences: [
      { id: 3170690, text: "Something green and slimy was on the rock." },
      { id: 11218719, text: "The creature was slimy and worm-like." },
      { id: 11005553, text: "Do not pick slimy things up off the ground.", changed: true },
    ],
  },
  {
    word: "boards",
    sentences: [
      { id: 13895354, text: "We use cutting boards to slice food on." },
      { id: 282777, text: "Boards are used to make floors." },
      { id: 268096, text: "The floor is made of boards." },
    ],
  },
  {
    word: "bees",
    sentences: [
      { id: 12004589, text: "The bees collect the pollen from the flowers." },
      { id: 11504957, text: "The bees are sitting on the flowers." },
      { id: 11999604, text: "How do bees survive the winter?" },
    ],
  },
  {
    word: "coins",
    sentences: [
      { id: 9621375, text: "Tom reached into his pocket and pulled out a few coins." },
      { id: 4665336, text: "I enjoy collecting rare coins." },
      { id: 13687902, text: "Tom showed me his collection of gold coins." },
    ],
  },
  {
    word: "doorbell",
    sentences: [
      { id: 40135, text: "I was about to leave when the doorbell rang." },
      { id: 8930844, text: "My dog started barking when the doorbell rang." },
      { id: 239524, text: "I heard the doorbell ring. Go and see who it is." },
    ],
  },
  {
    word: "candle",
    sentences: [
      { id: 2840930, text: "The room was lit by a single candle." },
      { id: 29464, text: "Please light a candle." },
      { id: 5852519, text: "I lit a candle so we could see." },
    ],
  },
  {
    word: "glances",
    sentences: [
      { id: 13446064, text: "We exchanged amused glances." },
      { id: 10212553, text: "The girls exchanged glances." },
      { id: 354283, text: "We exchanged glances with each other." },
    ],
  },
  {
    word: "mistaken",
    sentences: [
      { id: 3448718, text: "Tom is often mistaken for a student." },
      { id: 2406248, text: "I see now that I was mistaken." },
      { id: 7240655, text: "I know I was mistaken about that." },
    ],
  },
  {
    word: "charming",
    sentences: [
      { id: 12246925, text: "Tom lives in a charming old house." },
      { id: 10682294, text: "You have a charming smile." },
      { id: 7446755, text: "Tom is a charming young man." },
    ],
  },
  {
    word: "equal",
    sentences: [
      { id: 12875022, text: "Use equal parts butter and oil." },
      { id: 51723, text: "All men have equal rights." },
      { id: 6172600, text: "All humans are created equal." },
    ],
  },
  {
    word: "parties",
    sentences: [
      { id: 8975751, text: "I get invited to a lot of parties." },
      { id: 4664053, text: "I attended several parties last week." },
      { id: 13623529, text: "The cooperation has given both parties good results." },
    ],
  },
  {
    word: "dense",
    sentences: [
      { id: 8777871, text: "The trail enters into the dense forest." },
      { id: 10491017, text: "The forest was so dense, it was almost impossible to cross it." },
      { id: 322845, text: "The mist was so dense that I could not see even an inch ahead." },
    ],
  },
  {
    word: "bats",
    sentences: [
      { id: 1770535, text: "A lot of people think that bats are birds." },
      { id: 12904636, text: "During the day, the bats sleep." },
      { id: 8206584, text: "What sounds do bats make?" },
    ],
  },
  {
    word: "butterflies",
    sentences: [
      { id: 7766996, text: "Lots of butterflies are flying around the plants." },
      { id: 12768053, text: "I enjoy watching butterflies in the garden." },
      { id: 8972469, text: "The wings of butterflies are covered in small scales." },
    ],
  },
  {
    word: "drain",
    sentences: [
      { id: 10861075, text: "Pour that liquid down the drain." },
      { id: 270788, text: "The water will soon drain away." },
      { id: 12543336, text: "Because the drain is blocked, the water cannot flow away.", changed: true },
    ],
  },
  {
    word: "print",
    sentences: [
      { id: 5696037, text: "Can you print out this document for me?" },
      { id: 11006303, text: "Can you read this small print?" },
      { id: 1541491, text: "The book is out of print." },
    ],
  },
  {
    word: "restless",
    sentences: [
      { id: 13005696, text: "I get restless when I have to wait." },
      { id: 2427883, text: "Children are often impatient and restless." },
      { id: 13179182, text: "A mother tried to calm her restless child." },
    ],
  },
  {
    word: "slices",
    sentences: [
      { id: 12505091, text: "Tom cut the apple into thin slices." },
      { id: 9353388, text: "Please give me a couple of slices of bread." },
      { id: 35508, text: "Cut the pie into slices." },
    ],
  },
  {
    word: "tangle",
    sentences: [
      { id: 10900286, text: "My charging cable is in a tangle." },
      { id: 2877145, text: "Do not pull, or you will tangle the threads.", changed: true },
    ],
  },
  {
    word: "gesture",
    sentences: [
      { id: 8636574, text: "Thank you for your kind gesture." },
      { id: 11571789, text: "He raised his arms in the air in a gesture of victory." },
      { id: 13041066, text: "One gesture is often worth more than a thousand words." },
    ],
  },
  {
    word: "roast",
    sentences: [
      { id: 4499924, text: "I love roast chicken." },
      { id: 3622853, text: "The roast lamb is very good." },
      { id: 2747316, text: "Dad uses fire to roast a chicken." },
    ],
  },
  {
    word: "drawers",
    sentences: [
      { id: 48840, text: "The desk has three drawers." },
      { id: 1553538, text: "All the desk drawers were empty." },
      { id: 3735980, text: "Tom searched the kitchen drawers." },
    ],
  },
  {
    word: "gear",
    sentences: [
      { id: 11881722, text: "Do you need any hiking gear for your trip?" },
      { id: 26680, text: "Do you have rain gear with you?" },
      { id: 8659516, text: "The diver put on his diving gear." },
    ],
  },
  {
    word: "celebration",
    sentences: [
      { id: 14029258, text: "The celebration takes place in front of the town hall." },
      { id: 11516453, text: "Have a wonderful celebration!" },
      { id: 9308731, text: "Parents will be invited to the school celebration." },
    ],
  },
  {
    word: "trips",
    sentences: [
      { id: 12918806, text: "I enjoyed going on camping trips." },
      { id: 5548676, text: "We take a lot of trips together." },
      { id: 3260458, text: "Young people like to go on bike trips." },
    ],
  },
  {
    word: "daily",
    sentences: [
      { id: 13018874, text: "Strong habits can shape our daily lives." },
      { id: 4263043, text: "Music is ever present in our daily lives." },
      { id: 9820384, text: "Good use of technology can improve our daily life." },
    ],
  },
  {
    word: "travels",
    sentences: [
      { id: 11933249, text: "Tom often travels by train." },
      { id: 10355005, text: "My sister travels by bus to school." },
      { id: 240392, text: "Light travels much faster than sound." },
    ],
  },
  {
    word: "career",
    sentences: [
      { id: 10808020, text: "Try to pursue a career you will truly enjoy.", changed: true },
      { id: 10856978, text: "Do you want to get ahead in your career?" },
      { id: 6951186, text: "A university degree is the ticket to a successful career." },
    ],
  },
  {
    word: "announcement",
    sentences: [
      { id: 4529213, text: "I have an important announcement to make." },
      { id: 2358655, text: "I have a big announcement to make." },
      { id: 11711167, text: "The president made an official announcement." },
    ],
  },
  {
    word: "laundry",
    sentences: [
      { id: 7788256, text: "Do you do your own laundry?" },
      { id: 6249899, text: "I helped my mother fold the laundry." },
      { id: 11888946, text: "Fold your clean laundry and put it away." },
    ],
  },
  {
    word: "diamonds",
    sentences: [
      { id: 11944227, text: "Look at the way the diamonds are shining." },
      { id: 681842, text: "Perfect diamonds are extremely rare jewels." },
      { id: 6823329, text: "True friendships are even rarer than diamonds." },
    ],
  },
  {
    word: "lemon",
    sentences: [
      { id: 10782453, text: "Do you prefer tea with lemon or milk?" },
      { id: 3654061, text: "Lemons grow on lemon trees and oranges on orange trees." },
      { id: 11134742, text: "Hot tea with lemon will do your throat good." },
    ],
  },
  {
    word: "treats",
    sentences: [
      { id: 8655717, text: "The sweet treats are selling well." },
      { id: 11482629, text: "He always treats me with respect." },
      { id: 5542592, text: "Tom treats me like an adult." },
    ],
  },
  {
    word: "pipes",
    sentences: [
      { id: 2253280, text: "The cold froze the water in the pipes." },
      { id: 50800, text: "The house has pipes under the ground to carry dirty water away." },
      { id: 10350659, text: "Water was coming out of the damaged pipes." },
    ],
  },
  {
    word: "enthusiasm",
    sentences: [
      { id: 5726474, text: "Tom did everything with great enthusiasm." },
      { id: 5726219, text: "The kids showed great enthusiasm." },
      { id: 10534727, text: "Everyone did the work with enthusiasm." },
    ],
  },
  {
    word: "biscuit",
    sentences: [
      { id: 10857198, text: "A cup of tea and a biscuit, please." },
      { id: 8089136, text: "Who ate the last biscuit?" },
      { id: 8456668, text: "Tom rewarded his dog with a dog biscuit." },
    ],
  },
  {
    word: "passenger",
    sentences: [
      { id: 11894545, text: "Tom was sitting in the front passenger seat." },
      { id: 2956802, text: "Tom got out of the car on the passenger side." },
      { id: 7732153, text: "Tom is sitting in the passenger seat." },
    ],
  },
  {
    word: "fireplace",
    sentences: [
      { id: 5170178, text: "The living room has a fireplace." },
      { id: 6875984, text: "Come and warm yourself by the fireplace." },
      { id: 11523172, text: "We warmed ourselves in front of the fireplace." },
    ],
  },
  {
    word: "barrel",
    sentences: [
      { id: 10565136, text: "Is there much water in the barrel?" },
      { id: 5363459, text: "Tom floated down the river in a barrel." },
      { id: 10083248, text: "Tom hid behind a barrel." },
    ],
  },
  {
    word: "wrestling",
    sentences: [
      { id: 11622089, text: "When was the last time you saw a wrestling match?" },
      { id: 12999977, text: "We loved wrestling after school." },
      { id: 1025495, text: "Tom has a friend who is a wrestling coach." },
    ],
  },
  {
    word: "merry",
    sentences: [
      { id: 5716189, text: "I wish you all a Merry Christmas." },
      { id: 10119710, text: "The children are enjoying themselves on the merry-go-round." },
      { id: 10016421, text: "In the park, there are swings and merry-go-rounds." },
    ],
  },
  {
    word: "jewels",
    sentences: [
      { id: 9550068, text: "There were many jewels in the treasure chest." },
      { id: 681245, text: "On special occasions, some people wear jewels." },
      { id: 13715286, text: "My jewels are in the drawer." },
    ],
  },
  {
    word: "chickens",
    sentences: [
      { id: 1863232, text: "Cows give us milk and chickens give us eggs." },
      { id: 11276021, text: "A farm often has cows and chickens." },
      { id: 9669011, text: "I fed the pigs and the chickens." },
    ],
  },
  {
    word: "hush",
    sentences: [
      { id: 11545349, text: "A hush came over the crowd." },
      { id: 9943150, text: "A hush fell over the crowd." },
    ],
  },
  {
    word: "customers",
    sentences: [
      { id: 10585683, text: "About how many customers came into your shop today?" },
      { id: 11434067, text: "At least three customers come into our shop every day." },
      { id: 5618996, text: "We have really loyal repeat customers." },
    ],
  },
  {
    word: "photographs",
    sentences: [
      { id: 1113973, text: "Take a look at all the photographs!" },
      { id: 3932904, text: "Dan took photographs of his house." },
      { id: 12323178, text: "Did you take all these photographs?" },
    ],
  },
  {
    word: "needles",
    sentences: [
      { id: 5790198, text: "Do you have any needles in your pockets?" },
      { id: 6310010, text: "They are as sharp as needles." },
      { id: 11129649, text: "Tom is afraid of needles." },
    ],
  },
  {
    word: "beams",
    sentences: [
      { id: 2982280, text: "Beams of light shone through the clouds." },
      { id: 325801, text: "Beams bear the weight of the roof." },
      { id: 10612104, text: "The beams, held up by the columns, support and distribute the weight." },
    ],
  },
]
