// SPDX-License-Identifier: CC-BY-2.0-FR
//
// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).
// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>
//
// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.
// "changed: true" means that we expanded a contraction, for example "don't" to "do not".
// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.

import type { TatoebaEntry } from '../bank'

export const TATOEBA_0002_BANK: readonly TatoebaEntry[] = [
  {
    word: "glass",
    sentences: [
      { id: 64354, text: "May I have a glass of water?" },
      { id: 2406578, text: "I stepped on a piece of broken glass." },
      { id: 6554576, text: "Would you like a glass of milk?" },
    ],
  },
  {
    word: "radio",
    sentences: [
      { id: 255335, text: "I turned on the radio to listen to the news." },
      { id: 255911, text: "I also like listening to music on the radio." },
      { id: 6687304, text: "Turn off the radio and turn on the television!" },
    ],
  },
  {
    word: "ride",
    sentences: [
      { id: 6788833, text: "Do you know how to ride a bike?" },
      { id: 8147410, text: "I want to learn how to ride a horse." },
      { id: 2800718, text: "Would you like to go for a bike ride?" },
    ],
  },
  {
    word: "heavy",
    sentences: [
      { id: 3763807, text: "Why do children have to carry such a heavy bag?" },
      { id: 44465, text: "The box was so heavy I could not move it." },
      { id: 26958, text: "A heavy rain began to fall." },
    ],
  },
  {
    word: "chair",
    sentences: [
      { id: 2541710, text: "Tom found a chair and sat down." },
      { id: 13111004, text: "A girl sat in a chair at the kitchen table." },
      { id: 272863, text: "The teacher sat on the chair." },
    ],
  },
  {
    word: "video",
    sentences: [
      { id: 2014331, text: "I want you to watch this video." },
      { id: 2147096, text: "Check out this video I filmed with my friends." },
      { id: 8392378, text: "How often do you play video games?" },
    ],
  },
  {
    word: "weather",
    sentences: [
      { id: 9351493, text: "With this nice weather, I feel like taking a walk." },
      { id: 61567, text: "The weather will remain cold for several days." },
      { id: 73057, text: "The weather changes very often at this time of year." },
    ],
  },
  {
    word: "wonderful",
    sentences: [
      { id: 6781567, text: "What a wonderful day it was today!" },
      { id: 8279957, text: "I hope that you had a wonderful day." },
      { id: 3731360, text: "I hope you have a wonderful evening." },
    ],
  },
  {
    word: "flat",
    sentences: [
      { id: 3155594, text: "Put your hands flat on the table." },
      { id: 259606, text: "I live in a flat above a shop." },
      { id: 277262, text: "Do we have to lie flat on the ground?" },
    ],
  },
  {
    word: "farm",
    sentences: [
      { id: 3824756, text: "What animals do you have on your farm?" },
      { id: 3097137, text: "What do you grow on your farm?" },
      { id: 5648011, text: "We live on a farm near the village." },
    ],
  },
  {
    word: "band",
    sentences: [
      { id: 11902271, text: "Are you in a rock band?" },
      { id: 6076500, text: "Tom is the lead singer of his band." },
      { id: 11751685, text: "The band played a mix of covers and original songs." },
    ],
  },
  {
    word: "ship",
    sentences: [
      { id: 6352650, text: "Have you ever been on a ship?" },
      { id: 12227193, text: "We crossed the ocean on a small ship." },
      { id: 20244, text: "Which goes faster, a ship or a train?" },
    ],
  },
  {
    word: "leg",
    sentences: [
      { id: 6864844, text: "Tom fell and broke his leg." },
      { id: 1093521, text: "Tom hurt his leg and can barely walk." },
      { id: 1093591, text: "Tom has trouble standing on one leg." },
    ],
  },
  {
    word: "dinner",
    sentences: [
      { id: 5325375, text: "What would you like to eat for dinner?" },
      { id: 1696819, text: "What time do you eat dinner?" },
      { id: 3733834, text: "Tom and Mary eat dinner together almost every evening." },
    ],
  },
  {
    word: "slow",
    sentences: [
      { id: 12516064, text: "Why is the train going so slow?" },
      { id: 265581, text: "When you are driving, you should slow down on corners." },
      { id: 4014726, text: "Would you slow down a little?" },
    ],
  },
  {
    word: "dry",
    sentences: [
      { id: 846713, text: "Hang your clothes out to dry!" },
      { id: 4015928, text: "We need to let the paint dry first." },
      { id: 7806094, text: "Wet dogs smell worse than dry ones." },
    ],
  },
  {
    word: "horse",
    sentences: [
      { id: 282370, text: "Have you ever ridden a horse?" },
      { id: 46339, text: "The boy rode a horse for the first time." },
      { id: 6354057, text: "Can you still ride a horse?" },
    ],
  },
  {
    word: "reader",
    sentences: [
      { id: 30382, text: "A careful reader would have noticed the mistake." },
      { id: 3609289, text: "Tom is not a fast reader.", changed: true },
    ],
  },
  {
    word: "taxi",
    sentences: [
      { id: 2733280, text: "I took a taxi to the train station." },
      { id: 371890, text: "Should we go by car or by taxi?" },
      { id: 12874172, text: "We chose a taxi instead of a bus." },
    ],
  },
  {
    word: "cool",
    sentences: [
      { id: 8819656, text: "Let the cake cool down before serving." },
      { id: 6917034, text: "Stand in the shade and cool off." },
      { id: 267084, text: "Hot summer days ended and cool autumn days followed." },
    ],
  },
  {
    word: "library",
    sentences: [
      { id: 4753297, text: "I have to return some books to the library." },
      { id: 6240065, text: "Tom often goes to the library to read books." },
      { id: 3433223, text: "Does the school have a library?" },
    ],
  },
  {
    word: "lift",
    sentences: [
      { id: 681355, text: "Can you help me lift this?" },
      { id: 2300733, text: "I can give you a lift into town." },
      { id: 11219143, text: "The tent began to lift off the ground." },
    ],
  },
  {
    word: "river",
    sentences: [
      { id: 9237938, text: "The river flows through the centre of town." },
      { id: 3410732, text: "Have you ever tried to swim across this river?" },
      { id: 12186302, text: "Be careful when crossing this river." },
    ],
  },
  {
    word: "roll",
    sentences: [
      { id: 11602061, text: "Please roll down the window." },
      { id: 3318901, text: "Tears began to roll down her cheeks." },
    ],
  },
  {
    word: "photograph",
    sentences: [
      { id: 6417590, text: "Mary showed Tom a photograph of her father." },
      { id: 8839506, text: "When was this photograph taken?" },
      { id: 3826315, text: "Tom framed the photograph and hung it over the bed." },
    ],
  },
  {
    word: "artist",
    sentences: [
      { id: 6567508, text: "An artist must have an eye for colour." },
      { id: 253568, text: "I know the artist who painted this picture." },
      { id: 8485556, text: "Mary is an artist and paints portraits." },
    ],
  },
  {
    word: "corner",
    sentences: [
      { id: 11634336, text: "There was a light in one corner of the room." },
      { id: 9194631, text: "I sat down in a corner of the room." },
      { id: 7371715, text: "The bus turned the corner and stopped." },
    ],
  },
  {
    word: "quick",
    sentences: [
      { id: 2015191, text: "I just want to take a quick look." },
      { id: 1027077, text: "Tom ate a quick lunch then went back to work." },
      { id: 3328485, text: "Can I ask you a quick question?" },
    ],
  },
  {
    word: "cook",
    sentences: [
      { id: 4228305, text: "What kind of food do you like to cook?" },
      { id: 2377499, text: "I like to cook all kinds of food." },
      { id: 11685035, text: "I try to cook something different every day." },
    ],
  },
  {
    word: "driver",
    sentences: [
      { id: 8438229, text: "Why do you want to become a bus driver?" },
      { id: 12205512, text: "The vehicle stopped and the driver opened the door." },
      { id: 36966, text: "Every driver must follow the traffic rules." },
    ],
  },
  {
    word: "ball",
    sentences: [
      { id: 3534477, text: "Tom caught the ball and threw it back to Mary." },
      { id: 3434070, text: "Tom kicked the ball into the goal." },
      { id: 2374697, text: "I kicked the ball as far as I could." },
    ],
  },
  {
    word: "cry",
    sentences: [
      { id: 1026960, text: "Tom broke down and started to cry." },
      { id: 2981336, text: "I cry every time I watch that film." },
      { id: 3528308, text: "What makes you cry like that?" },
    ],
  },
  {
    word: "map",
    sentences: [
      { id: 45032, text: "Look up the town on the map." },
      { id: 8490799, text: "Do you have a map of the city?" },
      { id: 681425, text: "A world map shows all the countries." },
    ],
  },
  {
    word: "island",
    sentences: [
      { id: 6128532, text: "Have you ever wanted to live on an island?" },
      { id: 9795471, text: "How many people live on this island?" },
      { id: 6250113, text: "Tom and I swam to the island together." },
    ],
  },
  {
    word: "football",
    sentences: [
      { id: 4013410, text: "Tom plays football every day after school." },
      { id: 11797170, text: "Some boys play tennis and others play football." },
      { id: 11004781, text: "I always played football after school." },
    ],
  },
  {
    word: "neighbour",
    sentences: [
      { id: 12283167, text: "Tom is our next-door neighbour." },
      { id: 7954042, text: "Tom offered to help his neighbour." },
      { id: 12217927, text: "Have you met your new neighbour?" },
    ],
  },
  {
    word: "rain",
    sentences: [
      { id: 9954986, text: "We wanted to stay outside, but it began to rain." },
      { id: 2303407, text: "I love the sound of rain falling." },
      { id: 1190277, text: "I ran into the house because it started to rain." },
    ],
  },
  {
    word: "brain",
    sentences: [
      { id: 11452794, text: "You use your brain to think." },
      { id: 270226, text: "In humans, the eyes act together with the brain." },
      { id: 270224, text: "The human brain can adapt to new situations." },
    ],
  },
  {
    word: "funny",
    sentences: [
      { id: 5549667, text: "Tom told a very funny joke." },
      { id: 954131, text: "Let me tell you a funny story." },
      { id: 8018156, text: "A funny thing happened at school today." },
    ],
  },
  {
    word: "mountain",
    sentences: [
      { id: 1747393, text: "How about walking to the top of the mountain?" },
      { id: 1744802, text: "I have to climb this mountain." },
      { id: 5161364, text: "Do you want to climb the mountain?" },
    ],
  },
  {
    word: "hide",
    sentences: [
      { id: 2530543, text: "Do you want to play hide and seek?" },
      { id: 10506002, text: "Tom tried to hide behind his mother." },
      { id: 10323935, text: "I put it here to hide it from the cats." },
    ],
  },
  {
    word: "ticket",
    sentences: [
      { id: 6948439, text: "Where can I buy a train ticket?" },
      { id: 35361, text: "You must buy a ticket to get on the bus." },
      { id: 436191, text: "How much does a ticket cost for the concert?" },
    ],
  },
  {
    word: "meal",
    sentences: [
      { id: 12884382, text: "I eat rice with every meal." },
      { id: 5791654, text: "Tom prepared a healthy meal for Mary." },
      { id: 7010506, text: "Drink a glass of water before every meal." },
    ],
  },
  {
    word: "bag",
    sentences: [
      { id: 2892362, text: "Tom reached into his bag and pulled out a book." },
      { id: 41815, text: "I need a bag to carry it in." },
      { id: 3155630, text: "Put it in a brown paper bag." },
    ],
  },
  {
    word: "plane",
    sentences: [
      { id: 318040, text: "The plane will take off in one hour." },
      { id: 1821100, text: "How many passengers can this plane hold?" },
      { id: 12092146, text: "Have you ever flown a plane?" },
    ],
  },
  {
    word: "bird",
    sentences: [
      { id: 12255829, text: "Every day, a blue bird flies into our garden." },
      { id: 11153650, text: "I saw a bird fly over the tree." },
      { id: 323596, text: "Look at the bird singing in the tree." },
    ],
  },
  {
    word: "beach",
    sentences: [
      { id: 11289531, text: "I like to go to the beach in the summer." },
      { id: 6353181, text: "I love walking on the beach." },
      { id: 11642362, text: "We took a walk along the beach." },
    ],
  },
  {
    word: "flower",
    sentences: [
      { id: 6237981, text: "Mary picked a flower and put it in her hair." },
      { id: 13152438, text: "The flower grows in early spring." },
      { id: 11842062, text: "There are many different kinds of flower in the garden." },
    ],
  },
  {
    word: "boat",
    sentences: [
      { id: 6249940, text: "Tom crossed the river in a small boat." },
      { id: 33473, text: "We crossed the lake in a boat." },
      { id: 6907876, text: "Do you know how to sail a boat?" },
    ],
  },
  {
    word: "kitchen",
    sentences: [
      { id: 3066212, text: "Tom is in the kitchen making himself something to eat." },
      { id: 3260289, text: "We have a small table in the kitchen." },
      { id: 10771260, text: "Tom went into the kitchen to get something to eat." },
    ],
  },
  {
    word: "fresh",
    sentences: [
      { id: 8830613, text: "I stepped outside for some fresh air." },
      { id: 2207086, text: "Tom opened the window to let in some fresh air." },
      { id: 3183109, text: "Here we enjoy mountain walks and fresh air." },
    ],
  },
  {
    word: "engineer",
    sentences: [
      { id: 319107, text: "My father works at the factory as an engineer." },
      { id: 9999451, text: "Why do you want to be an engineer?" },
      { id: 5856449, text: "Tom is a very good sound engineer." },
    ],
  },
  {
    word: "quiet",
    sentences: [
      { id: 10512818, text: "Please be quiet for a few minutes." },
      { id: 2387461, text: "I need a quiet place to think." },
      { id: 9812804, text: "I just want to spend a quiet evening at home." },
    ],
  },
  {
    word: "nurse",
    sentences: [
      { id: 11003464, text: "At the hospital, I met a very nice nurse." },
      { id: 3304008, text: "Mary had always wanted to be a nurse." },
      { id: 13851308, text: "My aunt is a nurse in this hospital." },
    ],
  },
  {
    word: "jump",
    sentences: [
      { id: 11886535, text: "Always look before you jump into the pool." },
      { id: 239992, text: "We would run down to the lake and jump in." },
      { id: 10071572, text: "Do not jump over the fence!", changed: true },
    ],
  },
  {
    word: "winter",
    sentences: [
      { id: 9704876, text: "In the winter it gets very cold here." },
      { id: 4045679, text: "Does it often snow in the winter here?" },
      { id: 12307488, text: "The sun comes up earlier in summer than in winter." },
    ],
  },
  {
    word: "spring",
    sentences: [
      { id: 1235769, text: "Which season do you like best, spring or autumn?" },
      { id: 49206, text: "The flower comes out in early spring." },
      { id: 266905, text: "When spring comes, people go out to pick wild plants." },
    ],
  },
  {
    word: "lunch",
    sentences: [
      { id: 2538301, text: "We eat lunch together every day at school." },
      { id: 882552, text: "What will you have for lunch today?" },
      { id: 4054889, text: "Tom and Mary ate lunch outside." },
    ],
  },
  {
    word: "pool",
    sentences: [
      { id: 13545875, text: "In summer, I go to the swimming pool every day." },
      { id: 3259761, text: "To exercise, I swim in the pool every week." },
      { id: 3737071, text: "The swimming pool will be closed tomorrow." },
    ],
  },
  {
    word: "strange",
    sentences: [
      { id: 30150, text: "A strange thing happened last night." },
      { id: 12345773, text: "People do all kinds of strange things." },
    ],
  },
  {
    word: "afraid",
    sentences: [
      { id: 5800604, text: "Do not be afraid to ask if you need help.", changed: true },
      { id: 6272962, text: "Tom told Mary not to be afraid." },
      { id: 1184694, text: "You should not be afraid of the future." },
    ],
  },
  {
    word: "sun",
    sentences: [
      { id: 11864363, text: "When does the sun set today?" },
      { id: 11864398, text: "What time will the sun rise tomorrow?" },
      { id: 10999739, text: "I have to get home before the sun sets." },
    ],
  },
  {
    word: "healthy",
    sentences: [
      { id: 9860029, text: "You need to eat well to stay healthy." },
      { id: 11207146, text: "To stay healthy, you should eat a lot of fruit." },
      { id: 257220, text: "I exercise because I want to stay healthy." },
    ],
  },
  {
    word: "wash",
    sentences: [
      { id: 9679081, text: "How many times a day do you wash your hands?" },
      { id: 11886234, text: "Before you eat, make sure you wash your hands." },
      { id: 6024953, text: "How often do you wash the dishes?" },
    ],
  },
  {
    word: "stone",
    sentences: [
      { id: 8399340, text: "The house is surrounded by a stone wall." },
      { id: 3259755, text: "The well is built of stone." },
      { id: 11251534, text: "There was a bridge made of stone that crosses the river." },
    ],
  },
  {
    word: "egg",
    sentences: [
      { id: 49845, text: "The hen lays an egg almost every day." },
      { id: 35864, text: "The chicken laid an egg this morning." },
      { id: 1223897, text: "Can you break an egg with one hand?" },
    ],
  },
  {
    word: "concert",
    sentences: [
      { id: 8663918, text: "Do you like to go to a concert?" },
      { id: 11107316, text: "We lined up to get tickets for the concert." },
      { id: 12501991, text: "The crowd sang along to the music at the concert." },
    ],
  },
  {
    word: "pack",
    sentences: [
      { id: 4012275, text: "What do you think I should pack for my trip?" },
      { id: 2207306, text: "Did you pack your bags yourself?" },
      { id: 8589621, text: "You should pack a couple of extra changes of clothes." },
    ],
  },
  {
    word: "camera",
    sentences: [
      { id: 3061058, text: "Tom took out his camera and started taking pictures." },
      { id: 9181958, text: "Pay attention and smile for the camera!" },
      { id: 70104, text: "Do you know how to use this camera?" },
    ],
  },
  {
    word: "swim",
    sentences: [
      { id: 2013485, text: "Do you want to go for a swim?" },
      { id: 5618183, text: "You swim better than I do." },
      { id: 3734518, text: "Tom never really wanted to learn how to swim." },
    ],
  },
  {
    word: "theatre",
    sentences: [
      { id: 12070187, text: "Do you like going to the theatre?" },
      { id: 8830478, text: "Where can I buy tickets to the theatre?" },
      { id: 11231950, text: "Tom goes to the theatre every week." },
    ],
  },
  {
    word: "museum",
    sentences: [
      { id: 6699036, text: "Thousands of people visit this museum every month." },
      { id: 11205456, text: "Tom works at the town museum." },
      { id: 10646914, text: "When does the art museum open?" },
    ],
  },
  {
    word: "visitor",
    sentences: [
      { id: 681619, text: "The child offered a flower to the visitor." },
      { id: 245043, text: "The visitor asked the class a question." },
      { id: 19908, text: "You should prepare a room for the visitor." },
    ],
  },
  {
    word: "vehicle",
    sentences: [
      { id: 12205512, text: "The vehicle stopped and the driver opened the door." },
      { id: 682310, text: "Tom can drive almost any kind of vehicle." },
      { id: 10245478, text: "Tom opened the car door and stepped out of the vehicle." },
    ],
  },
  {
    word: "scientist",
    sentences: [
      { id: 8657375, text: "Tom is studying to be a scientist." },
      { id: 6912968, text: "Tom wanted to become a scientist." },
      { id: 6263544, text: "Tom is a bright young scientist." },
    ],
  },
  {
    word: "taste",
    sentences: [
      { id: 8419650, text: "Does the milk still taste good?" },
      { id: 12022708, text: "What does the apple taste like?" },
      { id: 9525070, text: "Do you like the taste of the soup?" },
    ],
  },
  {
    word: "dangerous",
    sentences: [
      { id: 11887505, text: "Stay away from the river, it can be dangerous." },
      { id: 682082, text: "Driving during a storm can be dangerous." },
      { id: 11888797, text: "Watch out for the swings, they can be dangerous!" },
    ],
  },
  {
    word: "gift",
    sentences: [
      { id: 3153710, text: "I plan to give this to Tom as a gift." },
      { id: 5332241, text: "I bought this book as a gift for Tom." },
      { id: 2652923, text: "Thank you for this wonderful gift." },
    ],
  },
  {
    word: "guest",
    sentences: [
      { id: 7126281, text: "Tom is our special guest today." },
      { id: 11942460, text: "Do you have a guest room?" },
      { id: 1115749, text: "The young girl gave the guest a little flower." },
    ],
  },
  {
    word: "bedroom",
    sentences: [
      { id: 8226857, text: "Can you see the ocean from your bedroom window?" },
      { id: 13897687, text: "I do not have a television in my bedroom.", changed: true },
      { id: 5350253, text: "You can sleep in the spare bedroom." },
    ],
  },
  {
    word: "climb",
    sentences: [
      { id: 6555143, text: "Do you think you could climb to the top of this tree?" },
      { id: 7594615, text: "The cat is trying to climb the tree." },
      { id: 12522183, text: "How high can you climb that tree?" },
    ],
  },
  {
    word: "mouth",
    sentences: [
      { id: 1190161, text: "When eating, do not speak with food in your mouth.", changed: true },
      { id: 2641101, text: "Tom opened his mouth to say something." },
    ],
  },
  {
    word: "square",
    sentences: [
      { id: 12004382, text: "Lots of tourists walk around the square." },
    ],
  },
  {
    word: "gold",
    sentences: [
      { id: 8771140, text: "I have a gold ring and another that is silver." },
      { id: 681083, text: "Is that ring made of real gold?" },
      { id: 8533311, text: "Silver is worth less than gold." },
    ],
  },
  {
    word: "skin",
    sentences: [
      { id: 13908800, text: "I have brown skin, straight hair and big eyes." },
    ],
  },
  {
    word: "wood",
    sentences: [
      { id: 12980625, text: "We gathered some wood to build a fire." },
      { id: 42058, text: "Is it made of wood or metal?" },
      { id: 10895515, text: "The house is made of wood." },
    ],
  },
  {
    word: "shake",
    sentences: [
      { id: 1713903, text: "The ground started to shake and the alarm rang." },
      { id: 30147, text: "Did you feel the earth shake last night?" },
      { id: 28511, text: "Let us shake hands and be friends.", changed: true },
    ],
  },
  {
    word: "shoe",
    sentences: [
      { id: 8313894, text: "What size shoe do you wear?" },
      { id: 3409307, text: "Tom could not find his left shoe.", changed: true },
    ],
  },
  {
    word: "hall",
    sentences: [
      { id: 13738359, text: "The bus stops in front of the town hall." },
      { id: 12888213, text: "Do you work at the town hall?" },
    ],
  },
  {
    word: "cup",
    sentences: [
      { id: 1447567, text: "Would you like to have another cup of tea?" },
      { id: 3343265, text: "Who will win the World Cup?" },
    ],
  },
  {
    word: "finger",
    sentences: [
      { id: 10665497, text: "Touch your nose with your left index finger." },
      { id: 6426646, text: "Mary pointed her finger at Tom." },
    ],
  },
  {
    word: "bright",
    sentences: [
      { id: 11221055, text: "The sky is bright and clear now." },
      { id: 13390189, text: "The moon is not as bright as the sun.", changed: true },
      { id: 8624975, text: "Why is the sun so bright?" },
    ],
  },
  {
    word: "tie",
    sentences: [
      { id: 6821884, text: "Do you usually wear a tie to work?" },
      { id: 1526515, text: "I wear a suit, but not a tie." },
    ],
  },
  {
    word: "forest",
    sentences: [
      { id: 324123, text: "Wild animals live in the forest." },
      { id: 11333152, text: "There are a lot of trees in the forest." },
      { id: 248912, text: "We went for a walk in the forest." },
    ],
  },
  {
    word: "factory",
    sentences: [
      { id: 477355, text: "My father works in a factory." },
      { id: 11618151, text: "Which way leads to the chocolate factory?" },
      { id: 11573239, text: "Tom used to work at a paint factory." },
    ],
  },
  {
    word: "friendly",
    sentences: [
      { id: 6348922, text: "Tom is very friendly and helpful." },
      { id: 1970223, text: "I am happy to see so many friendly faces.", changed: true },
      { id: 1970224, text: "I looked around hoping to spot a friendly face." },
    ],
  },
  {
    word: "bridge",
    sentences: [
      { id: 10240076, text: "The boat passed under a bridge." },
      { id: 10523005, text: "We need to cross the bridge." },
      { id: 1884524, text: "Tom crosses this bridge at least once a week." },
    ],
  },
  {
    word: "farmer",
    sentences: [
      { id: 10043551, text: "The farmer brings us fresh milk every morning." },
      { id: 2794708, text: "The farmer dug a hole so he could plant a tree." },
      { id: 9522753, text: "We buy our vegetables from the farmer." },
    ],
  },
  {
    word: "narrow",
    sentences: [
      { id: 11729482, text: "The street is too narrow for two cars to pass." },
      { id: 323931, text: "The gate is too narrow for the car." },
      { id: 681700, text: "We walked down a narrow and winding path." },
    ],
  },
  {
    word: "desk",
    sentences: [
      { id: 3223163, text: "Tom sat down at his desk and started working." },
      { id: 6579089, text: "Mary sat down at the desk and began to write." },
      { id: 11679629, text: "I sit at a desk most of the day." },
    ],
  },
  {
    word: "wild",
    sentences: [
      { id: 1308109, text: "There are many wild animals around here." },
      { id: 11889113, text: "Keep your distance from any wild animals you encounter." },
      { id: 266905, text: "When spring comes, people go out to pick wild plants." },
    ],
  },
  {
    word: "empty",
    sentences: [
      { id: 18303, text: "Find an empty bottle and fill it with water." },
      { id: 10860995, text: "There are lots of empty seats in the room." },
      { id: 4823841, text: "So, is the glass half full or half empty?" },
    ],
  },
  {
    word: "tea",
    sentences: [
      { id: 10722362, text: "How often do you drink green tea?" },
      { id: 2544263, text: "I will make you a cup of tea.", changed: true },
      { id: 3722473, text: "Tom placed some cups of tea on the table." },
    ],
  },
  {
    word: "lovely",
    sentences: [
      { id: 36122, text: "What a lovely day it is!" },
      { id: 7414147, text: "What a lovely thing a rose is!" },
      { id: 12146508, text: "What a lovely shade of blue!" },
    ],
  },
  {
    word: "soft",
    sentences: [
      { id: 7175522, text: "Tom thought that the bed was too soft." },
      { id: 9444446, text: "Do you prefer hard or soft cheese?" },
      { id: 7305693, text: "Lead is soft and heavy. Iron is hard and steel harder." },
    ],
  },
  {
    word: "lock",
    sentences: [
      { id: 720519, text: "Do not forget to lock the door!", changed: true },
      { id: 11751593, text: "I slipped the key into the lock and turned it." },
      { id: 2321166, text: "We lock the doors at night." },
    ],
  },
  {
    word: "shoulder",
    sentences: [
      { id: 11779947, text: "I felt a hand on my shoulder." },
      { id: 276154, text: "Someone tapped me on the shoulder." },
      { id: 11695151, text: "I was carrying my bag over my shoulder." },
    ],
  },
  {
    word: "bottle",
    sentences: [
      { id: 2712563, text: "Tom picked up the water bottle and took a drink." },
      { id: 7206830, text: "Fill up this water bottle, please!" },
      { id: 12618695, text: "Where can I buy a bottle of water?" },
    ],
  },
  {
    word: "engine",
    sentences: [
      { id: 2956800, text: "Tom got into his car, started the engine, and drove away." },
      { id: 2537850, text: "Tom stopped the car and turned off the engine." },
      { id: 7127715, text: "How long did it take the first fire engine to arrive?" },
    ],
  },
  {
    word: "journey",
    sentences: [
      { id: 263313, text: "We are going on a journey next month." },
      { id: 13618175, text: "Our journey on foot lasted nine days." },
      { id: 24401, text: "I want to go on a journey around the world if possible." },
    ],
  },
  {
    word: "dad",
    sentences: [
      { id: 958767, text: "My dad owns a lot of books." },
      { id: 6670119, text: "Tom helps his dad out on the farm." },
      { id: 11627961, text: "Tom looks a lot like his dad." },
    ],
  },
  {
    word: "tiny",
    sentences: [
      { id: 18347, text: "The houses and cars looked tiny from the sky." },
      { id: 272395, text: "The baby held out his tiny hand." },
      { id: 2864133, text: "Fifty families live in this tiny village." },
    ],
  },
  {
    word: "careful",
    sentences: [
      { id: 3826635, text: "We need to be very careful not to break anything." },
      { id: 4597324, text: "You best be careful where you step." },
      { id: 2994927, text: "Be careful that you do not get lost.", changed: true },
    ],
  },
  {
    word: "fruit",
    sentences: [
      { id: 10046755, text: "Do you tend to eat fruit and vegetables daily?" },
      { id: 10826351, text: "Mary brought fresh fruit from the market." },
      { id: 7736537, text: "What fruit do you eat most often?" },
    ],
  },
  {
    word: "terrible",
    sentences: [
      { id: 34712, text: "I have caught a terrible cold.", changed: true },
      { id: 7175026, text: "Tom thought that it was a terrible idea." },
      { id: 272705, text: "A terrible thing happened last week." },
    ],
  },
  {
    word: "ear",
    sentences: [
      { id: 6689424, text: "Tom put the phone to his ear." },
      { id: 13115144, text: "The eye sees and the ear hears." },
      { id: 2640731, text: "Tom put his ear to the door and listened." },
    ],
  },
  {
    word: "shout",
    sentences: [
      { id: 995182, text: "Do not shout, the neighbours will hear you!", changed: true },
      { id: 3722004, text: "Tom had to shout to be heard." },
      { id: 13859972, text: "If you shout, she will hear you." },
    ],
  },
  {
    word: "hill",
    sentences: [
      { id: 5737432, text: "Tom drove slowly up the hill." },
      { id: 11650252, text: "Our house is at the very top of the hill." },
      { id: 68463, text: "There used to be a great castle on that hill." },
    ],
  },
  {
    word: "cat",
    sentences: [
      { id: 1044867, text: "The little cat wants to sleep." },
      { id: 48224, text: "The dog ran after the cat." },
      { id: 12554511, text: "Seeing the dog, the cat ran away." },
    ],
  },
  {
    word: "thin",
    sentences: [
      { id: 13344184, text: "Do you want a thick piece or a thin piece?" },
      { id: 44324, text: "The ice is too thin to bear your weight." },
      { id: 6639376, text: "Cut the meat into thin strips." },
    ],
  },
  {
    word: "plate",
    sentences: [
      { id: 2956071, text: "Tom ate everything that was on his plate." },
      { id: 7899876, text: "Tom put the slices on a plate." },
      { id: 620817, text: "Serve the meal on a plate." },
    ],
  },
  {
    word: "sad",
    sentences: [
      { id: 4501650, text: "We received some sad news today." },
      { id: 1449785, text: "Why does she look so sad?" },
      { id: 3513453, text: "Everyone seemed sad to see Tom go." },
    ],
  },
  {
    word: "circle",
    sentences: [
      { id: 3223153, text: "All the children were sitting in a circle." },
      { id: 5293081, text: "Tom drew a circle in the sand with a stick." },
      { id: 12374027, text: "Draw a circle on the floor." },
    ],
  },
  {
    word: "sick",
    sentences: [
      { id: 3890969, text: "If you get sick, go to the doctor." },
      { id: 41508, text: "If you eat so much, you will get sick.", changed: true },
      { id: 1164360, text: "Tom never seems to get sick." },
    ],
  },
  {
    word: "joke",
    sentences: [
      { id: 62922, text: "The whole class laughed at his joke." },
      { id: 9004537, text: "I always laugh when someone tells a joke." },
      { id: 11225787, text: "To lighten the mood, I told a joke." },
    ],
  },
  {
    word: "sky",
    sentences: [
      { id: 12768230, text: "The stars filled the night sky." },
      { id: 2123489, text: "The bird flew up into the blue sky." },
      { id: 10551592, text: "The sky darkened, and it began to rain." },
    ],
  },
  {
    word: "coast",
    sentences: [
      { id: 273436, text: "The ship sailed along the coast." },
      { id: 44740, text: "The island is about two miles off the coast." },
    ],
  },
  {
    word: "kick",
    sentences: [
      { id: 11605013, text: "How far can you kick that ball?" },
      { id: 11605015, text: "How high can you kick this ball?" },
      { id: 11885767, text: "Do not kick the ball too hard.", changed: true },
    ],
  },
  {
    word: "hat",
    sentences: [
      { id: 5936594, text: "I almost always wear a hat when I go outside." },
      { id: 434538, text: "Do you have a coat and a hat?" },
      { id: 12142862, text: "I asked Tom to take off his hat." },
    ],
  },
  {
    word: "alive",
    sentences: [
      { id: 7131840, text: "Do you feel lucky to be alive?" },
      { id: 326409, text: "Although old, he is still very much alive." },
    ],
  },
  {
    word: "sweet",
    sentences: [
      { id: 11165427, text: "I like chocolate if it is not too sweet.", changed: true },
      { id: 12646545, text: "What do you prefer? Sweet or salty." },
    ],
  },
  {
    word: "tall",
    sentences: [
      { id: 10918514, text: "How tall would you say that tree is?" },
      { id: 3304951, text: "The tall girl picked up the small child." },
      { id: 6936836, text: "How tall is the building where you work?" },
    ],
  },
  {
    word: "milk",
    sentences: [
      { id: 8420318, text: "How much milk do you drink every day?" },
      { id: 12219252, text: "Before going to bed, I drink a glass of milk." },
      { id: 880551, text: "May I have a glass of milk, please?" },
    ],
  },
  {
    word: "smell",
    sentences: [
      { id: 12106451, text: "The smell of food filled the air." },
      { id: 35085, text: "The smell of roses filled the room." },
      { id: 2855301, text: "You can smell the chocolate from outside!" },
    ],
  },
  {
    word: "pilot",
    sentences: [
      { id: 1056424, text: "The pilot will land the plane." },
      { id: 3123896, text: "The pilot landed the plane safely." },
      { id: 11055983, text: "The pilot managed to make a perfect landing." },
    ],
  },
  {
    word: "angry",
    sentences: [
      { id: 2892934, text: "Why does it make you angry?" },
      { id: 6904869, text: "What kind of things make you angry?" },
      { id: 3819381, text: "Do not get angry with Tom.", changed: true },
    ],
  },
  {
    word: "knock",
    sentences: [
      { id: 4016274, text: "Why not just knock on the door?" },
      { id: 239933, text: "I heard a knock at the door." },
    ],
  },
  {
    word: "seed",
    sentences: [
      { id: 2761307, text: "The small seed became a large tree." },
      { id: 681742, text: "If you plant an apple seed, it might grow into a tree." },
      { id: 9433829, text: "This fruit contains one single seed." },
    ],
  },
  {
    word: "breakfast",
    sentences: [
      { id: 411296, text: "What do you eat for breakfast?" },
      { id: 2059864, text: "Tom eats a healthy breakfast every morning." },
      { id: 3836057, text: "The next morning, we ate breakfast together." },
    ],
  },
  {
    word: "lake",
    sentences: [
      { id: 248224, text: "We sometimes swim in the lake." },
      { id: 3258178, text: "We must go across the lake by boat." },
      { id: 13610081, text: "The fish swam in the lake." },
    ],
  },
  {
    word: "yellow",
    sentences: [
      { id: 2976130, text: "Apples are usually green, yellow, or red." },
      { id: 323603, text: "The leaves began to turn red and yellow." },
      { id: 11817524, text: "First the traffic light turns yellow, then red." },
    ],
  },
  {
    word: "metal",
    sentences: [
      { id: 42058, text: "Is it made of wood or metal?" },
    ],
  },
  {
    word: "bone",
    sentences: [
      { id: 256149, text: "I broke a bone in my foot while exercising." },
      { id: 953291, text: "Have you ever broken a bone?" },
      { id: 13815107, text: "What is the longest bone in the human body?", changed: true },
    ],
  },
  {
    word: "sharp",
    sentences: [
      { id: 7806982, text: "The car made a sharp turn." },
      { id: 9801149, text: "I feel a sharp pain when I bend my knee." },
    ],
  },
  {
    word: "grey",
    sentences: [
      { id: 12506735, text: "The sky is grey and cloudy." },
      { id: 12434904, text: "Age makes your hair turn grey." },
      { id: 10455393, text: "The evening sky is turning grey." },
    ],
  },
  {
    word: "plastic",
    sentences: [
      { id: 7746092, text: "I refuse to use plastic bags." },
      { id: 577369, text: "I prefer paper cups to plastic ones." },
      { id: 689905, text: "Would you like a plastic bag or a paper bag?" },
    ],
  },
]
