// SPDX-License-Identifier: CC-BY-2.0-FR
//
// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).
// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>
//
// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.
// "changed: true" means that we expanded a contraction, for example "don't" to "do not".
// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.

import type { TatoebaEntry } from '../bank'

export const TATOEBA_0007_BANK: readonly TatoebaEntry[] = [
  {
    word: "hutch",
    sentences: [
      { id: 13567860, text: "The boy went into the rabbit hutch." },
    ],
  },
  {
    word: "blackberry",
    sentences: [
      { id: 6907493, text: "The baker made a delicious blackberry pie." },
    ],
  },
  {
    word: "tinsel",
    sentences: [
      { id: 13664013, text: "I bought some purple tinsel." },
    ],
  },
  {
    word: "vicious",
    sentences: [
      { id: 1655458, text: "Watch out! This monkey is vicious." },
    ],
  },
  {
    word: "redo",
    sentences: [
      { id: 11707987, text: "Tom had to redo his homework." },
      { id: 10550672, text: "It took about a month to redo everything." },
      { id: 12458621, text: "We had to redo everything after Tom." },
    ],
  },
  {
    word: "refresh",
    sentences: [
      { id: 5733210, text: "Can someone refresh my memory?" },
      { id: 4794508, text: "Does this document refresh your memory?" },
      { id: 278714, text: "Moderate exercise will refresh both mind and body." },
    ],
  },
  {
    word: "return",
    sentences: [
      { id: 256050, text: "I must return home within a week." },
      { id: 2953617, text: "We expect Tom to return home soon." },
      { id: 4258934, text: "What can I give you in return?" },
    ],
  },
  {
    word: "redecorate",
    sentences: [
      { id: 1024903, text: "Tom is planning to redecorate his bedroom." },
      { id: 12564807, text: "I want to redecorate my house." },
      { id: 3490489, text: "You need to redecorate your room." },
    ],
  },
  {
    word: "submarine",
    sentences: [
      { id: 1477910, text: "A submarine can travel over and under the water." },
      { id: 2725830, text: "The submarine hid in the depths of the ocean." },
      { id: 3060810, text: "The submarine finally came to the surface." },
    ],
  },
  {
    word: "interact",
    sentences: [
      { id: 5882818, text: "They need to interact with other kids." },
      { id: 10834258, text: "Take some time to interact with your dog." },
      { id: 13215765, text: "Online games provide fun ways for friends to interact together." },
    ],
  },
  {
    word: "international",
    sentences: [
      { id: 6046787, text: "Have you ever seen the International Space Station?" },
      { id: 12331888, text: "Today is International Mother Language Day." },
      { id: 11035414, text: "Today is the International Day of Friendship." },
    ],
  },
  {
    word: "related",
    sentences: [
      { id: 10039925, text: "Monkeys are closely related to humans." },
      { id: 5836377, text: "How are you related to Tom?" },
      { id: 3738918, text: "Do you know how Tom is related to Mary?" },
    ],
  },
  {
    word: "supermarket",
    sentences: [
      { id: 7969482, text: "Tom went to the supermarket to buy some food." },
      { id: 2589124, text: "I often go shopping at the supermarket near my house." },
      { id: 12391364, text: "I bought milk at the supermarket today." },
    ],
  },
  {
    word: "superman",
    sentences: [
      { id: 2020401, text: "Superman can see through walls." },
      { id: 11556860, text: "Superman can bend iron." },
      { id: 13671213, text: "Do you want to be like Superman?" },
    ],
  },
  {
    word: "antiseptic",
    sentences: [
      { id: 5791086, text: "Wash his wound with this antiseptic." },
    ],
  },
  {
    word: "clockwise",
    sentences: [
      { id: 10503626, text: "The top part is turning clockwise." },
      { id: 928517, text: "The top is turning clockwise." },
      { id: 9966901, text: "It moves in a clockwise motion." },
    ],
  },
  {
    word: "antisocial",
    sentences: [
      { id: 318687, text: "I do not mean to be antisocial, but I am tired.", changed: true },
    ],
  },
  {
    word: "autobiography",
    sentences: [
      { id: 3826458, text: "Tom is writing an autobiography." },
      { id: 11558162, text: "I want to write my autobiography." },
      { id: 12818503, text: "Tom started to write an autobiography." },
    ],
  },
  {
    word: "autograph",
    sentences: [
      { id: 8174099, text: "Tom asked Mary for her autograph." },
      { id: 284572, text: "The fan asked for his autograph." },
      { id: 430483, text: "I can give you an autograph if you want." },
    ],
  },
  {
    word: "information",
    sentences: [
      { id: 10010400, text: "Where can I find more information about this subject?" },
      { id: 11475260, text: "For more information, call this number." },
      { id: 11887163, text: "You should take notes to remember important information." },
    ],
  },
  {
    word: "adoration",
    sentences: [
      { id: 7743548, text: "I looked at the sweet child with adoration." },
    ],
  },
  {
    word: "sensation",
    sentences: [
      { id: 10685191, text: "I can feel a burning sensation in my stomach." },
      { id: 273775, text: "I felt a burning sensation all over." },
      { id: 4759196, text: "Pain is an entirely personal sensation." },
    ],
  },
  {
    word: "preparation",
    sentences: [
      { id: 263056, text: "We are studying hard in preparation for the exams." },
      { id: 311930, text: "She was cleaning the house in preparation for a party." },
      { id: 248335, text: "We all made preparation for the meeting." },
    ],
  },
  {
    word: "admiration",
    sentences: [
      { id: 286378, text: "I feel admiration for his talent." },
      { id: 9638923, text: "She looks at me with admiration." },
      { id: 11496925, text: "I have a lot of admiration for you." },
    ],
  },
  {
    word: "sadly",
    sentences: [
      { id: 317739, text: "Sadly, his dream did not come true.", changed: true },
      { id: 7792763, text: "Tom looked sadly out of the window." },
      { id: 317755, text: "Smiling sadly, she began to talk." },
    ],
  },
  {
    word: "completely",
    sentences: [
      { id: 7793748, text: "You look like a completely different person." },
      { id: 6900592, text: "In a year, everything will be completely different." },
      { id: 12211546, text: "Not long ago, you told me something completely different." },
    ],
  },
  {
    word: "usually",
    sentences: [
      { id: 277768, text: "When do you usually get up?" },
      { id: 5592291, text: "What time do you usually leave for work?" },
      { id: 4049102, text: "What kind of food do you usually eat?" },
    ],
  },
  {
    word: "finally",
    sentences: [
      { id: 1332069, text: "We finally reached the top of the mountain." },
      { id: 13799257, text: "After another hour and a half we finally arrived." },
      { id: 327338, text: "I finally got hold of that book I wanted." },
    ],
  },
  {
    word: "final",
    sentences: [
      { id: 4135276, text: "What was the final score of the game?" },
      { id: 2360175, text: "I have one final question for you." },
      { id: 243952, text: "The final score was two to nothing." },
    ],
  },
  {
    word: "comical",
    sentences: [
      { id: 5269889, text: "The situation was very comical." },
      { id: 10823278, text: "This led to a very comical situation." },
    ],
  },
  {
    word: "angrily",
    sentences: [
      { id: 3688245, text: "He shut the door angrily." },
      { id: 11145069, text: "Tom walked away angrily." },
      { id: 11813890, text: "When I ask her a question, she looks at me angrily." },
    ],
  },
  {
    word: "basically",
    sentences: [
      { id: 5738581, text: "Tom is basically a nice man." },
      { id: 6310169, text: "Humans are basically all the same." },
      { id: 3870080, text: "I basically like your plan." },
    ],
  },
  {
    word: "frantically",
    sentences: [
      { id: 2642901, text: "Tom looked around frantically." },
      { id: 5735945, text: "I cried frantically for help." },
      { id: 2659678, text: "He works frantically to achieve his goal." },
    ],
  },
  {
    word: "dramatically",
    sentences: [
      { id: 263797, text: "The situation has changed dramatically." },
      { id: 1556881, text: "The cost of living increased dramatically." },
      { id: 5725309, text: "Our technology has advanced dramatically." },
    ],
  },
  {
    word: "measure",
    sentences: [
      { id: 638167, text: "A ruler can measure something up to twelve inches in length." },
      { id: 7158240, text: "How can we measure the depth of a valley?" },
      { id: 11479422, text: "How do you measure success?" },
    ],
  },
  {
    word: "pleasure",
    sentences: [
      { id: 12506882, text: "What a pleasure to see you again!" },
      { id: 10929108, text: "Good day! A pleasure to meet you." },
      { id: 264616, text: "Nothing gives us so much pleasure as making things ourselves." },
    ],
  },
  {
    word: "enclosure",
    sentences: [
      { id: 60293, text: "There are many kinds of animals inside this enclosure." },
      { id: 13613837, text: "The enclosure offers the animals plenty of space." },
    ],
  },
  {
    word: "creature",
    sentences: [
      { id: 3468021, text: "Without water, no creature could live." },
      { id: 3672869, text: "No creature can live without air." },
      { id: 11711629, text: "The bird-like creature flew away." },
    ],
  },
  {
    word: "nature",
    sentences: [
      { id: 11882301, text: "Have you ever gone on a nature walk in the forest?" },
      { id: 10017193, text: "Morning is when we can notice how beautiful nature is." },
      { id: 8803681, text: "Being out in nature can have a calming effect." },
    ],
  },
  {
    word: "division",
    sentences: [
      { id: 2549906, text: "The children have not studied division yet.", changed: true },
      { id: 2549884, text: "What division of the company do you work in?" },
    ],
  },
  {
    word: "confusion",
    sentences: [
      { id: 10208802, text: "What he said caused a lot of confusion." },
      { id: 11881994, text: "You should label your keys to avoid confusion." },
      { id: 47186, text: "The accident threw traffic into great confusion." },
    ],
  },
  {
    word: "decision",
    sentences: [
      { id: 12140884, text: "We have a difficult decision to make." },
      { id: 13231552, text: "Think for yourself and come to a decision." },
      { id: 12600779, text: "Consider the options carefully before making a decision." },
    ],
  },
  {
    word: "collision",
    sentences: [
      { id: 9476158, text: "They managed to avoid a collision." },
      { id: 3891213, text: "The two planes were on a collision course." },
      { id: 11507588, text: "He had a head-on collision with a bus." },
    ],
  },
  {
    word: "poisonous",
    sentences: [
      { id: 44662, text: "We should keep away from the poisonous plants." },
      { id: 11028297, text: "All these plants here are poisonous." },
      { id: 6731875, text: "The dog ate chocolate, which is poisonous to dogs." },
    ],
  },
  {
    word: "mountainous",
    sentences: [
      { id: 6085771, text: "I used to live in a mountainous area." },
      { id: 2549942, text: "The town is in a mountainous district." },
      { id: 11184801, text: "The mountainous landscape is beautiful, like a painting." },
    ],
  },
  {
    word: "tremendous",
    sentences: [
      { id: 1519607, text: "Tom did an absolutely tremendous job." },
      { id: 7114630, text: "They do a tremendous job." },
      { id: 6088119, text: "I think we had a tremendous year." },
    ],
  },
  {
    word: "enormous",
    sentences: [
      { id: 875614, text: "The work took an enormous amount of time to finish." },
      { id: 12228714, text: "Putting together a dictionary demands an enormous amount of time." },
      { id: 631396, text: "Ordinary people possess enormous power." },
    ],
  },
  {
    word: "jealous",
    sentences: [
      { id: 2954546, text: "You have nothing to be jealous of." },
      { id: 12934544, text: "I have no reason to be jealous." },
      { id: 10073804, text: "Be careful. You might make Tom jealous." },
    ],
  },
  {
    word: "humorous",
    sentences: [
      { id: 47785, text: "The writer is very humorous." },
      { id: 10948760, text: "The story of their encounter is somewhat humorous." },
      { id: 308452, text: "She gave me a humorous account of her encounter with him." },
    ],
  },
  {
    word: "glamorous",
    sentences: [
      { id: 7126491, text: "Mary is a glamorous girl." },
      { id: 8174464, text: "Mary leads a glamorous life." },
      { id: 327048, text: "Show business is really glamorous." },
    ],
  },
  {
    word: "vigorous",
    sentences: [
      { id: 26560, text: "You will be more vigorous if you exercise." },
      { id: 282157, text: "He looks very vigorous, considering his age." },
      { id: 248230, text: "We had a very vigorous debate." },
    ],
  },
  {
    word: "courageous",
    sentences: [
      { id: 322224, text: "You were courageous to tell the truth." },
      { id: 10666528, text: "The proud and courageous knights sat around a great round table." },
      { id: 11902429, text: "I am strong and courageous." },
    ],
  },
  {
    word: "outrageous",
    sentences: [
      { id: 960805, text: "These prices are outrageous!" },
      { id: 12354715, text: "He was selling it at an outrageous price." },
      { id: 5355765, text: "The price was outrageous." },
    ],
  },
  {
    word: "serious",
    sentences: [
      { id: 1929126, text: "The matter is more serious than you think." },
      { id: 318649, text: "Carelessness can lead to a serious accident." },
      { id: 9937097, text: "I have serious things to talk about." },
    ],
  },
  {
    word: "obvious",
    sentences: [
      { id: 9698219, text: "I thought it was obvious what I wanted." },
      { id: 2777628, text: "Tom was simply stating the obvious." },
      { id: 12125511, text: "Have I not made that obvious?" },
    ],
  },
  {
    word: "hideous",
    sentences: [
      { id: 6973455, text: "That shirt looks hideous." },
      { id: 8398301, text: "She was wearing hideous boots." },
      { id: 10064896, text: "They built a hideous new building in our village." },
    ],
  },
  {
    word: "spontaneous",
    sentences: [
      { id: 12771383, text: "When was the last time you did something spontaneous?" },
      { id: 953521, text: "I like to be spontaneous." },
      { id: 298509, text: "He made a spontaneous offer of help." },
    ],
  },
  {
    word: "courteous",
    sentences: [
      { id: 2744126, text: "Be courteous and respectful." },
      { id: 11913456, text: "Be courteous to each other." },
      { id: 8200934, text: "Tom is courteous to everybody." },
    ],
  },
  {
    word: "invention",
    sentences: [
      { id: 273362, text: "The washing machine is a wonderful invention." },
      { id: 9331177, text: "The radio was a great invention." },
      { id: 279293, text: "The invention of the telephone made it possible to communicate with people far away." },
    ],
  },
  {
    word: "injection",
    sentences: [
      { id: 10577552, text: "The doctor gave me an injection." },
      { id: 10999911, text: "The nurse gave the patient an injection." },
      { id: 12089636, text: "I felt no pain when the nurse gave me the injection." },
    ],
  },
  {
    word: "action",
    sentences: [
      { id: 11449189, text: "Everyone in the meeting agreed on a course of action." },
      { id: 240544, text: "You are all talk and no action!", changed: true },
      { id: 4660482, text: "Our country must take action against climate change." },
    ],
  },
  {
    word: "hesitation",
    sentences: [
      { id: 11456041, text: "Tom answered without hesitation." },
      { id: 10131568, text: "Tom accepted the job offer without hesitation." },
      { id: 254989, text: "Without hesitation, I granted his request." },
    ],
  },
  {
    word: "completion",
    sentences: [
      { id: 59444, text: "This building is near completion." },
      { id: 10128600, text: "The first stage is nearing completion." },
      { id: 240732, text: "The construction work is steadily nearing completion." },
    ],
  },
  {
    word: "expression",
    sentences: [
      { id: 7130205, text: "Tom had a surprised expression on his face." },
      { id: 1930063, text: "Judging from the expression on her face, she was worried." },
      { id: 6989045, text: "The meaning of an expression can change over time." },
    ],
  },
  {
    word: "discussion",
    sentences: [
      { id: 6104454, text: "When can we have a discussion about this?" },
      { id: 2641241, text: "We need to have a serious discussion." },
      { id: 248169, text: "We had a heated discussion about it." },
    ],
  },
  {
    word: "permission",
    sentences: [
      { id: 2955926, text: "Tom asked for permission to use the phone." },
      { id: 9074612, text: "Tom asked permission to leave the room." },
      { id: 10112488, text: "Do you have permission to be here?" },
    ],
  },
  {
    word: "admission",
    sentences: [
      { id: 11038806, text: "How much is the admission fee?" },
      { id: 10558209, text: "Admission to the event is free." },
      { id: 72520, text: "There is no admission fee for children under five." },
    ],
  },
  {
    word: "extension",
    sentences: [
      { id: 13399019, text: "The extension lead for the computer is too short." },
      { id: 12245540, text: "I need an extension cable." },
      { id: 1507916, text: "What is the file extension?" },
    ],
  },
  {
    word: "comprehension",
    sentences: [
      { id: 13240414, text: "Listening comprehension is tough for me." },
      { id: 2228403, text: "English is too difficult for my comprehension." },
      { id: 8224328, text: "The more phrases you learn, the easier your comprehension will be." },
    ],
  },
  {
    word: "tension",
    sentences: [
      { id: 286764, text: "His joke eased the tension in the room." },
      { id: 8100914, text: "I have a lot of tension in my shoulders." },
      { id: 2958381, text: "Tom tried to ease the tension." },
    ],
  },
  {
    word: "electrician",
    sentences: [
      { id: 749787, text: "Next week the electrician is coming to fix the wires." },
      { id: 8575296, text: "Tom works as an electrician." },
      { id: 2860051, text: "The electrician will come and fix the cable next week." },
    ],
  },
  {
    word: "magician",
    sentences: [
      { id: 11178139, text: "The magician pulled a rabbit out of his hat." },
      { id: 12114769, text: "That magician knows a lot of tricks." },
      { id: 9433837, text: "A good magician never reveals his tricks." },
    ],
  },
  {
    word: "politician",
    sentences: [
      { id: 271386, text: "A politician should serve the people." },
      { id: 12369214, text: "When I grow up, I want to become a politician." },
      { id: 45946, text: "The politician first made a name for himself as an actor." },
    ],
  },
  {
    word: "mathematician",
    sentences: [
      { id: 9460808, text: "Tom is a good mathematician." },
      { id: 8775016, text: "I want to be a mathematician." },
      { id: 11935786, text: "How do you become a mathematician?" },
    ],
  },
  {
    word: "scheme",
    sentences: [
      { id: 49138, text: "There is a scheme to expand the company." },
      { id: 306022, text: "They devised a scheme to make money with little effort." },
      { id: 5218501, text: "Everybody has a scheme for perfecting the world." },
    ],
  },
  {
    word: "chorus",
    sentences: [
      { id: 6887067, text: "Tom sings in the school chorus." },
      { id: 9752118, text: "Everyone sang the chorus." },
      { id: 22856, text: "We sang songs in chorus." },
    ],
  },
  {
    word: "chemist",
    sentences: [
      { id: 9004276, text: "The chemist sold me the medicines." },
      { id: 11084335, text: "You can get it from any chemist." },
      { id: 13064149, text: "Which chemist is open late this evening?" },
    ],
  },
  {
    word: "echo",
    sentences: [
      { id: 247590, text: "We heard the echo of our voices from the other side of the valley." },
      { id: 12275476, text: "Did you hear an echo?" },
      { id: 6576727, text: "Do I hear an echo in here?" },
    ],
  },
  {
    word: "character",
    sentences: [
      { id: 9511157, text: "Which character in this book do you like most?" },
      { id: 706873, text: "The main character is a man whose name we do not know." },
      { id: 12244681, text: "Tom voiced the main character of the film." },
    ],
  },
  {
    word: "chef",
    sentences: [
      { id: 9023426, text: "Tom is the best chef in town." },
      { id: 12218641, text: "The chef has prepared something special." },
      { id: 4999962, text: "Tom is a good chef." },
    ],
  },
  {
    word: "brochure",
    sentences: [
      { id: 13406285, text: "The brochure contains all the information about the trip." },
      { id: 28396, text: "Could you send me a brochure?" },
      { id: 12272749, text: "Did you read the whole brochure?" },
    ],
  },
  {
    word: "league",
    sentences: [
      { id: 241627, text: "Our team has topped the league this season." },
      { id: 6241558, text: "Our team is the worst team in the league." },
      { id: 750691, text: "Do you know who the best player in the league is?" },
    ],
  },
  {
    word: "antique",
    sentences: [
      { id: 27272, text: "Can you tell me where the nearest antique shop is?" },
      { id: 316619, text: "She has some beautiful antique furniture." },
      { id: 6243685, text: "I bought this watch at an antique store." },
    ],
  },
  {
    word: "unique",
    sentences: [
      { id: 13208475, text: "Every individual has a unique story to tell." },
      { id: 13113420, text: "Everyone has qualities that make them unique." },
      { id: 11892815, text: "Do you own a belt with a unique pattern?" },
    ],
  },
  {
    word: "science",
    sentences: [
      { id: 3023360, text: "Tom sits behind Mary in science class." },
      { id: 269373, text: "The new discovery proved useful to science." },
      { id: 270651, text: "Man hopes to master nature with science and technology." },
    ],
  },
  {
    word: "discipline",
    sentences: [
      { id: 11630601, text: "Discipline at the school was strict." },
      { id: 21570, text: "School discipline is not as it should be." },
      { id: 4543291, text: "Discipline is the most important part of success." },
    ],
  },
  {
    word: "fascinate",
    sentences: [
      { id: 6147022, text: "Stories like that fascinate me." },
      { id: 5953405, text: "Word origins fascinate me." },
      { id: 11328015, text: "Plastic seems to fascinate cats." },
    ],
  },
  {
    word: "crescent",
    sentences: [
      { id: 11227498, text: "There was a crescent moon that night." },
      { id: 12646816, text: "The crescent moon is visible." },
    ],
  },
  {
    word: "weigh",
    sentences: [
      { id: 12373534, text: "How much does this box weigh?" },
      { id: 11605011, text: "How much does a football weigh?" },
      { id: 9629610, text: "I weigh myself on a scale every day." },
    ],
  },
  {
    word: "obey",
    sentences: [
      { id: 7060985, text: "The players must obey the rules." },
      { id: 954802, text: "You should obey all traffic laws." },
      { id: 1177063, text: "All drivers should obey the rules of the road." },
    ],
  },
  {
    word: "accept",
    sentences: [
      { id: 46065, text: "I had no choice but to accept the offer." },
      { id: 12981375, text: "I think you should accept the offer." },
      { id: 10278469, text: "At the store, they only accept cash payments." },
    ],
  },
  {
    word: "except",
    sentences: [
      { id: 7537730, text: "There was no one in the room except Tom." },
      { id: 4267468, text: "Everybody except Tom seems to be having fun." },
      { id: 5547627, text: "I have read every page except the last one.", changed: true },
    ],
  },
  {
    word: "affect",
    sentences: [
      { id: 26716, text: "Does the amount of rain affect the growth of crops?" },
      { id: 4264458, text: "What you eat and drink before bed can affect your sleep." },
      { id: 10358676, text: "The size of the board does not affect the rules." },
    ],
  },
  {
    word: "effect",
    sentences: [
      { id: 43552, text: "The medicine seemed to have no effect on the patient." },
      { id: 10239066, text: "Thankfully, the medicine quickly started to take effect." },
      { id: 8803677, text: "Looking at nature has a calming effect." },
    ],
  },
  {
    word: "berry",
    sentences: [
      { id: 58802, text: "This berry is good to eat." },
    ],
  },
  {
    word: "bury",
    sentences: [
      { id: 9312454, text: "Dogs always find the bones they bury." },
      { id: 10910071, text: "I would bury it in the garden." },
      { id: 2064941, text: "Did you bury something on that island?" },
    ],
  },
  {
    word: "brake",
    sentences: [
      { id: 52826, text: "John put his foot on the brake and we stopped suddenly." },
      { id: 5738351, text: "Tom pressed the brake pedal." },
      { id: 12187815, text: "Which foot do you brake with?" },
    ],
  },
  {
    word: "break",
    sentences: [
      { id: 1536382, text: "You work too much. Take a break!" },
      { id: 3047055, text: "Tom tried to break down the door." },
      { id: 3719604, text: "Can I take a break now?" },
    ],
  },
  {
    word: "fare",
    sentences: [
      { id: 35222, text: "How much is the bus fare?" },
      { id: 12084163, text: "If you travel by bus or train, you have to pay a fare." },
      { id: 40938, text: "Before we get out of the taxi, we pay the fare." },
    ],
  },
  {
    word: "grate",
    sentences: [
      { id: 10953856, text: "Grate the carrots finely." },
      { id: 10836268, text: "Grate cheese over the top and serve." },
      { id: 11507610, text: "Can you grate bread?" },
    ],
  },
  {
    word: "great",
    sentences: [
      { id: 1324026, text: "I hope you have a great day!" },
    ],
  },
  {
    word: "groan",
    sentences: [
      { id: 5756798, text: "Tom let out a groan." },
      { id: 4499081, text: "What was that groan for?" },
    ],
  },
]
