// SPDX-License-Identifier: CC-BY-2.0-FR
//
// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).
// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>
//
// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.
// "changed: true" means that we expanded a contraction, for example "don't" to "do not".
// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.

import type { TatoebaEntry } from '../bank'

export const TATOEBA_0003_BANK: readonly TatoebaEntry[] = [
  {
    word: "freeze",
    sentences: [
      { id: 13800627, text: "To make pure ice, you freeze water." },
      { id: 12240210, text: "At what temperature does water freeze?" },
      { id: 9440584, text: "During lengthy cold spells, the lakes and rivers freeze over." },
    ],
  },
  {
    word: "coat",
    sentences: [
      { id: 13421805, text: "Put on a coat, or you will catch cold.", changed: true },
      { id: 1486353, text: "Mary bought a new winter coat." },
      { id: 2741286, text: "Tom put on his coat and left." },
    ],
  },
  {
    word: "pocket",
    sentences: [
      { id: 3155745, text: "Tom put the letter in his coat pocket." },
      { id: 3474596, text: "Tom pulled a coin out of his pocket." },
      { id: 6341222, text: "How much money do you have in your pocket now?" },
    ],
  },
  {
    word: "lucky",
    sentences: [
      { id: 3133811, text: "You are so lucky to have such good friends." },
      { id: 8440233, text: "You are very lucky to have a home like this.", changed: true },
    ],
  },
  {
    word: "meat",
    sentences: [
      { id: 281004, text: "Which do you like better, meat or fish?" },
      { id: 8811385, text: "Do you eat a lot of meat?" },
      { id: 248008, text: "We have eaten no meat for several days." },
    ],
  },
  {
    word: "king",
    sentences: [
      { id: 10166713, text: "The king lived in an old castle." },
      { id: 13684326, text: "The king and queen had twenty children." },
      { id: 13678072, text: "The king built a house." },
    ],
  },
  {
    word: "dish",
    sentences: [
      { id: 11698955, text: "Can you show me how to cook this dish?" },
      { id: 6825603, text: "The dish you prepared for dinner last night was very salty." },
      { id: 1717631, text: "Have you ever eaten this dish?" },
    ],
  },
  {
    word: "proud",
    sentences: [
      { id: 39577, text: "Well done! Your parents must be proud of you." },
      { id: 8593142, text: "We have many reasons to be proud of our team." },
      { id: 4665627, text: "Tom will be so proud of you." },
    ],
  },
  {
    word: "slide",
    sentences: [
      { id: 3375268, text: "Do you want to go down the slide?" },
      { id: 11886979, text: "Be careful on the slide, go down slowly!" },
      { id: 5362851, text: "Tom slid down the water slide." },
    ],
  },
  {
    word: "shirt",
    sentences: [
      { id: 2799084, text: "I usually wear a white shirt." },
      { id: 242741, text: "What shirt will you wear to school today?" },
      { id: 6263894, text: "What size shirt do you wear?" },
    ],
  },
  {
    word: "winner",
    sentences: [
      { id: 238554, text: "The gold cup was given to the winner of the final match." },
      { id: 11498662, text: "The judges stood to announce the winner." },
      { id: 13864380, text: "I gave the prize to the first winner." },
    ],
  },
  {
    word: "brown",
    sentences: [
      { id: 44567, text: "One of the cats is black, the other is brown." },
      { id: 259432, text: "I want brown shoes, not black ones." },
      { id: 9921792, text: "The wall was painted light brown." },
    ],
  },
  {
    word: "tennis",
    sentences: [
      { id: 68923, text: "How long do you play tennis every day?" },
      { id: 2890384, text: "We played a good game of tennis." },
      { id: 2738181, text: "Who does he play tennis with?" },
    ],
  },
  {
    word: "mouse",
    sentences: [
      { id: 35791, text: "The mouse ran and the cat ran after him." },
      { id: 8968481, text: "A mouse is smaller than a rat." },
      { id: 13950439, text: "The cat chased the mouse around the house." },
    ],
  },
  {
    word: "snow",
    sentences: [
      { id: 9686945, text: "We get a lot of snow in the winter." },
      { id: 4853286, text: "Tom looked out of the window at the snow falling." },
      { id: 275819, text: "The heavy snow stopped the train from running on time." },
    ],
  },
  {
    word: "neck",
    sentences: [
      { id: 5726483, text: "Tom wore a silver chain around his neck." },
      { id: 12179596, text: "Tom hurt his neck and back." },
    ],
  },
  {
    word: "calm",
    sentences: [
      { id: 8013262, text: "Tom tried to calm the baby down." },
      { id: 10767079, text: "The weather will begin to calm down soon." },
      { id: 6647257, text: "Tom told everybody to remain calm." },
    ],
  },
  {
    word: "bike",
    sentences: [
      { id: 3153641, text: "I ride a bike to work." },
      { id: 11891703, text: "How fast can you ride a bike?" },
      { id: 2961164, text: "Tom got off the bike and started to run." },
    ],
  },
  {
    word: "wheel",
    sentences: [
      { id: 26593, text: "The driver turned the wheel to the right." },
      { id: 12391230, text: "Put some air in the back wheel of your bike." },
    ],
  },
  {
    word: "toy",
    sentences: [
      { id: 7899864, text: "Put your toys back into the toy box." },
      { id: 3938813, text: "Tom likes playing with his toy cars." },
      { id: 7794506, text: "Tom asked his mother to buy him a new toy." },
    ],
  },
  {
    word: "storm",
    sentences: [
      { id: 11560034, text: "The storm caused great damage to the city." },
      { id: 12768213, text: "The sky darkened as the storm approached." },
      { id: 12141079, text: "Our plane could not take off because of the storm.", changed: true },
    ],
  },
  {
    word: "thick",
    sentences: [
      { id: 320350, text: "One book is thin, and the other is thick." },
      { id: 46268, text: "The floor is covered with a thick carpet." },
      { id: 318324, text: "The ice is two inches thick." },
    ],
  },
  {
    word: "prize",
    sentences: [
      { id: 1728201, text: "Have you ever won a prize?" },
      { id: 2721668, text: "I won a prize in the spelling competition." },
      { id: 27246, text: "The boy who writes best wins the prize." },
    ],
  },
  {
    word: "roof",
    sentences: [
      { id: 13369347, text: "Tom slept on the roof of his house." },
      { id: 49401, text: "The roof of the house let in the rain." },
      { id: 2777002, text: "Tom hit his head on the roof of the car." },
    ],
  },
  {
    word: "tooth",
    sentences: [
      { id: 273626, text: "My front tooth fell out." },
      { id: 4654465, text: "Tom broke a tooth biting into an apple." },
      { id: 11891905, text: "Do not rush, take your time to brush each tooth carefully.", changed: true },
    ],
  },
  {
    word: "silver",
    sentences: [
      { id: 11692989, text: "One of the rings was gold and the other was silver." },
      { id: 13083549, text: "Gold and silver are metals." },
      { id: 6317788, text: "Gold is more valuable than silver." },
    ],
  },
  {
    word: "nervous",
    sentences: [
      { id: 51829, text: "I can hardly make a speech without feeling nervous." },
      { id: 3346733, text: "Mary gets nervous when Tom drives too fast." },
      { id: 6232193, text: "One of the men waiting in line seemed very nervous." },
    ],
  },
  {
    word: "wet",
    sentences: [
      { id: 932542, text: "I got caught in the rain and got all wet." },
      { id: 6398102, text: "Take off your wet clothes and change into something dry." },
      { id: 281990, text: "I stood under a tree to avoid getting wet." },
    ],
  },
  {
    word: "cloud",
    sentences: [
      { id: 18309, text: "There was not a cloud in the sky.", changed: true },
      { id: 2900615, text: "The sun suddenly appeared from behind a cloud." },
      { id: 7758376, text: "A dark cloud is approaching from the west." },
    ],
  },
  {
    word: "pupil",
    sentences: [
      { id: 62910, text: "Every pupil in the class is present." },
      { id: 273021, text: "The teacher acknowledged the pupil with a smile." },
      { id: 12891872, text: "The teacher considers the pupil the best in the class." },
    ],
  },
  {
    word: "hero",
    sentences: [
      { id: 12888202, text: "Who is the main hero of the novel?" },
      { id: 8813634, text: "I think Tom is a hero for what he did." },
      { id: 11555128, text: "Everyone in town considers Tom a hero." },
    ],
  },
  {
    word: "nose",
    sentences: [
      { id: 4823937, text: "I eat with my mouth and smell with my nose." },
      { id: 5961644, text: "Breathe through your nose, not your mouth." },
      { id: 11892825, text: "You need to wash your hands after blowing your nose." },
    ],
  },
  {
    word: "sail",
    sentences: [
      { id: 6907876, text: "Do you know how to sail a boat?" },
      { id: 273400, text: "I would like to sail around the world.", changed: true },
      { id: 4134516, text: "Who taught you how to sail?" },
    ],
  },
  {
    word: "pour",
    sentences: [
      { id: 8837321, text: "Please pour me a glass of water." },
      { id: 7899852, text: "Please pour yourself a cup of tea." },
      { id: 12768482, text: "The rain started to pour down hard." },
    ],
  },
  {
    word: "sweep",
    sentences: [
      { id: 71434, text: "I will sweep the floor while you wash the dishes.", changed: true },
      { id: 12115747, text: "Can someone please sweep the floor in the kitchen?" },
      { id: 680757, text: "We need to sweep up the dust." },
    ],
  },
  {
    word: "stream",
    sentences: [
      { id: 20787, text: "A small stream ran down among the rocks." },
      { id: 495618, text: "The stream flows into the pond." },
      { id: 3060934, text: "Where can we cross the stream?" },
    ],
  },
  {
    word: "muscle",
    sentences: [
      { id: 11586406, text: "I think I have pulled a muscle in my leg.", changed: true },
      { id: 12361486, text: "The tongue is the strongest muscle in the body." },
    ],
  },
  {
    word: "scream",
    sentences: [
      { id: 280722, text: "All at once, I heard a scream." },
      { id: 10064871, text: "I let out a high-pitched scream when I saw the mouse." },
      { id: 8350134, text: "The silence of the night was broken by a scream." },
    ],
  },
  {
    word: "furniture",
    sentences: [
      { id: 319487, text: "There was little furniture in the room." },
      { id: 13232660, text: "I moved all the furniture out of my old house." },
      { id: 5811750, text: "All the furniture in our house was made by Tom." },
    ],
  },
  {
    word: "cake",
    sentences: [
      { id: 5099817, text: "Would you like a piece of cake?" },
      { id: 3674936, text: "Have you ever eaten this kind of cake before?" },
      { id: 62633, text: "Do not eat too much cake." },
    ],
  },
  {
    word: "singer",
    sentences: [
      { id: 3098778, text: "I have always wanted to be a singer." },
      { id: 8131030, text: "I want to become a famous singer." },
      { id: 23913, text: "A bad cold caused the singer to lose his voice." },
    ],
  },
  {
    word: "grass",
    sentences: [
      { id: 11216394, text: "The field was full of tall grass." },
      { id: 5793201, text: "The field is covered in nice green grass." },
      { id: 7668027, text: "I like the smell of freshly cut grass." },
    ],
  },
  {
    word: "mirror",
    sentences: [
      { id: 2979990, text: "How often do you look at yourself in the mirror?" },
      { id: 3066870, text: "Tom looked at his reflection in the mirror." },
      { id: 3324310, text: "Do you like looking in the mirror?" },
    ],
  },
  {
    word: "awful",
    sentences: [
      { id: 11537736, text: "I have some awful news for you." },
    ],
  },
  {
    word: "poem",
    sentences: [
      { id: 13369208, text: "Today I read a poem." },
      { id: 1042629, text: "Who was this poem written by?" },
      { id: 10372102, text: "What a beautiful poem! Did you write this?" },
    ],
  },
  {
    word: "festival",
    sentences: [
      { id: 11698991, text: "Have you ever been to a music festival before?" },
      { id: 3428326, text: "There were a lot of great bands at the festival." },
      { id: 66439, text: "In Italy, each village holds a festival once a year." },
    ],
  },
  {
    word: "vegetable",
    sentences: [
      { id: 7783583, text: "Tom and Mary have a small vegetable garden." },
      { id: 13078555, text: "How many types of vegetable do you grow in your garden?" },
      { id: 7543488, text: "Tom had vegetable soup for lunch." },
    ],
  },
  {
    word: "van",
    sentences: [
      { id: 11513453, text: "John was loading his things into a van." },
      { id: 5915281, text: "I opened the door and got out of the van." },
      { id: 1717371, text: "Have you ever driven a van?" },
    ],
  },
  {
    word: "planet",
    sentences: [
      { id: 3955480, text: "We live on the planet Earth." },
      { id: 10500569, text: "Earth is the third planet in our solar system." },
      { id: 259264, text: "I cannot imagine life on another planet.", changed: true },
    ],
  },
  {
    word: "knee",
    sentences: [
      { id: 6437940, text: "Tom fell down and hurt his knee." },
      { id: 11444190, text: "I hurt my knee while playing football." },
    ],
  },
  {
    word: "giant",
    sentences: [
      { id: 8132887, text: "The sun is a giant ball of gas." },
      { id: 11219206, text: "The giant creature pushed the tree over." },
      { id: 11171208, text: "The giant creature was looking for its baby." },
    ],
  },
  {
    word: "sugar",
    sentences: [
      { id: 2912637, text: "How much sugar do you put in your tea?" },
      { id: 6108916, text: "To make a cake, you need egg, butter and sugar." },
      { id: 8859074, text: "Do you want milk and sugar?" },
    ],
  },
  {
    word: "pink",
    sentences: [
      { id: 9288802, text: "Mary was wearing a pink dress." },
      { id: 12386684, text: "The sun went down, making the sky orange and pink." },
      { id: 11573276, text: "We plan to either paint this bedroom pink or light blue." },
    ],
  },
  {
    word: "shadow",
    sentences: [
      { id: 43781, text: "The tree cast a long shadow." },
      { id: 1683033, text: "I saw a shadow move behind that tree!" },
      { id: 12768457, text: "A shadow moved across the wall." },
    ],
  },
  {
    word: "smooth",
    sentences: [
      { id: 22225, text: "The sea was as smooth as glass." },
      { id: 9692368, text: "Its surface can be smooth or rough." },
      { id: 265558, text: "The car came to a smooth stop." },
    ],
  },
  {
    word: "loud",
    sentences: [
      { id: 2761752, text: "Speak loud enough to be heard." },
      { id: 10157620, text: "I always read books out loud before sleeping." },
    ],
  },
  {
    word: "jacket",
    sentences: [
      { id: 9165328, text: "Put on a jacket. It is cold.", changed: true },
      { id: 8909327, text: "The man wearing the green jacket is Tom." },
      { id: 2958348, text: "Tom took off his leather jacket and sat down." },
    ],
  },
  {
    word: "dirty",
    sentences: [
      { id: 5821662, text: "Tom leaves his dirty clothes lying all over the house." },
      { id: 13598582, text: "Do not touch it with dirty hands.", changed: true },
      { id: 11881916, text: "Please avoid touching the windows with dirty hands." },
    ],
  },
  {
    word: "iron",
    sentences: [
      { id: 9813577, text: "Gold is more valuable than iron." },
      { id: 2738993, text: "Is it made of iron?" },
      { id: 18578, text: "Gold is heavier than iron." },
    ],
  },
  {
    word: "bread",
    sentences: [
      { id: 2912559, text: "How much bread do you eat every day?" },
      { id: 9387672, text: "Tom ate a piece of bread." },
      { id: 681017, text: "Where can you get the best fresh bread?" },
    ],
  },
  {
    word: "bend",
    sentences: [
      { id: 5127333, text: "My knee hurts when I bend it." },
      { id: 3826542, text: "I can barely bend my left arm." },
    ],
  },
  {
    word: "flood",
    sentences: [
      { id: 11173584, text: "The flood washed away the bridge." },
      { id: 10933429, text: "The flood affected everyone living by the river." },
      { id: 8326126, text: "The city was damaged by the flood." },
    ],
  },
  {
    word: "boot",
    sentences: [
      { id: 8422926, text: "Tom got out of his car and opened the boot." },
      { id: 11149727, text: "My guitar is in the boot of my car." },
      { id: 12550404, text: "I pull off my boot." },
    ],
  },
  {
    word: "button",
    sentences: [
      { id: 10019210, text: "When you press this button, the door opens." },
      { id: 1424468, text: "Push the green button and the light will go on." },
      { id: 20475, text: "Press this button to start the machine." },
    ],
  },
  {
    word: "desert",
    sentences: [
      { id: 7697512, text: "There is a lot of sand in the desert.", changed: true },
      { id: 13025246, text: "The sand cat is a rare animal that lives in the desert." },
      { id: 12072859, text: "In the desert, permanent water is like gold." },
    ],
  },
  {
    word: "bowl",
    sentences: [
      { id: 13367556, text: "Would you like a bowl of soup?" },
      { id: 6415554, text: "Mary poured some milk into a bowl for her cat." },
      { id: 1164293, text: "Tom put some rice in a bowl." },
    ],
  },
  {
    word: "bath",
    sentences: [
      { id: 7712687, text: "I take a hot bath every night before bed." },
      { id: 319801, text: "Run hot water into the bath." },
      { id: 11352216, text: "I feel clean after taking a bath." },
    ],
  },
  {
    word: "rough",
    sentences: [
      { id: 45685, text: "The ship encountered rough seas." },
    ],
  },
  {
    word: "pen",
    sentences: [
      { id: 2387456, text: "I need a pen and paper." },
      { id: 3002091, text: "Tom picked up a pen and started to write." },
      { id: 33805, text: "Please write your name in pen." },
    ],
  },
  {
    word: "tower",
    sentences: [
      { id: 7902574, text: "Tom climbed all the way to the top of the tower." },
      { id: 47724, text: "There was a tower on the top of the mountain." },
      { id: 11943546, text: "The tower is close to the old castle." },
    ],
  },
  {
    word: "spin",
    sentences: [
      { id: 9040094, text: "Why does the Earth spin?" },
      { id: 10651604, text: "Tom gave the ball a spin." },
    ],
  },
  {
    word: "dig",
    sentences: [
      { id: 2033159, text: "I want you to dig a hole." },
      { id: 2956849, text: "Tom had to dig his car out of the snow." },
      { id: 7936786, text: "Birds dig around in the ground." },
    ],
  },
  {
    word: "wrap",
    sentences: [
      { id: 55141, text: "Please wrap these gifts up together." },
    ],
  },
  {
    word: "chicken",
    sentences: [
      { id: 238426, text: "Which do you like better, chicken or fish?" },
      { id: 12204428, text: "How long did you cook the chicken?" },
      { id: 6430437, text: "Tom made some chicken soup for Mary." },
    ],
  },
  {
    word: "musician",
    sentences: [
      { id: 46323, text: "The boy grew up to be a famous musician." },
      { id: 13636026, text: "The musician wrote music for the play." },
      { id: 7542703, text: "Tom started out as a street musician." },
    ],
  },
  {
    word: "shower",
    sentences: [
      { id: 11149243, text: "In summer, I take a shower every morning." },
      { id: 8505997, text: "How many times a day do you take a shower?" },
      { id: 11277635, text: "I like to shower at night." },
    ],
  },
  {
    word: "cousin",
    sentences: [
      { id: 65949, text: "My cousin works in a shop near our home." },
      { id: 250213, text: "My cousin is a little older than I." },
      { id: 1224183, text: "My cousin is four, but he eats as much as I do." },
    ],
  },
  {
    word: "sand",
    sentences: [
      { id: 318495, text: "The sand on the beach was white." },
      { id: 680688, text: "Children love to dig in the sand." },
      { id: 1010130, text: "The children built a sand castle on the beach." },
    ],
  },
  {
    word: "valley",
    sentences: [
      { id: 12130170, text: "The water flows down the mountain and into the valley." },
      { id: 2841184, text: "We took a walk in a beautiful green valley." },
      { id: 276090, text: "A river runs down through the valley." },
    ],
  },
  {
    word: "float",
    sentences: [
      { id: 3393758, text: "In water, wood will float and stone will sink." },
      { id: 6266913, text: "Can you float on your back?" },
      { id: 680976, text: "An astronaut can float in space." },
    ],
  },
  {
    word: "electric",
    sentences: [
      { id: 1342132, text: "I have an electric guitar." },
      { id: 5821850, text: "In the future, everyone will drive an electric car." },
    ],
  },
  {
    word: "dust",
    sentences: [
      { id: 11616200, text: "I blew the dust off the old book." },
      { id: 10784704, text: "There was dust on all the furniture." },
      { id: 18111, text: "Brush off the dust from your shoes." },
    ],
  },
  {
    word: "skirt",
    sentences: [
      { id: 11159680, text: "I wear a yellow skirt and white shoes." },
      { id: 57281, text: "I like this skirt. May I try it on?" },
      { id: 3560903, text: "Mary wore a flowery skirt." },
    ],
  },
  {
    word: "salt",
    sentences: [
      { id: 52336, text: "Add more salt to the soup." },
      { id: 64749, text: "Would you bring me some salt?" },
      { id: 681476, text: "Some salt comes from mines, some from water." },
    ],
  },
  {
    word: "brush",
    sentences: [
      { id: 3109946, text: "How many times a day do you brush your teeth?" },
      { id: 258765, text: "I always brush my teeth before I go to bed." },
      { id: 27432, text: "You should brush your teeth at least twice a day." },
    ],
  },
  {
    word: "chest",
    sentences: [
      { id: 12218136, text: "Cross your arms over your chest." },
      { id: 7857726, text: "Tom held his books close to his chest." },
    ],
  },
  {
    word: "fantastic",
    sentences: [
      { id: 2331575, text: "I had a fantastic time at your party." },
      { id: 12065290, text: "What a fantastic idea this is!" },
      { id: 7517759, text: "I know that Tom is a fantastic cook." },
    ],
  },
  {
    word: "orange",
    sentences: [
      { id: 11205693, text: "The sky started to turn orange." },
      { id: 5308263, text: "My favourite colour is orange." },
      { id: 3321668, text: "I have an orange and an apple." },
    ],
  },
  {
    word: "throat",
    sentences: [
      { id: 9725712, text: "Food goes from the throat to the stomach." },
      { id: 10977072, text: "The food got stuck in his throat." },
      { id: 7131129, text: "Tom stopped and cleared his throat." },
    ],
  },
  {
    word: "pig",
    sentences: [
      { id: 12722420, text: "What food did you feed the pig?" },
      { id: 6936813, text: "Tom has a pet pig." },
      { id: 12614625, text: "How many teeth does a pig have?" },
    ],
  },
  {
    word: "shelf",
    sentences: [
      { id: 43882, text: "Put the book back on the shelf." },
      { id: 43934, text: "Put the book on the top shelf." },
      { id: 6048687, text: "How many books are on the shelf?" },
    ],
  },
  {
    word: "tail",
    sentences: [
      { id: 5325920, text: "The fox has a long tail and pointed ears." },
      { id: 1650744, text: "A cat has a tail and four legs." },
      { id: 1456827, text: "The fish swims by moving its tail." },
    ],
  },
  {
    word: "curious",
    sentences: [
      { id: 245953, text: "Children are very curious and ask many questions." },
      { id: 1237431, text: "I am very curious about it!" },
      { id: 12391950, text: "I was curious about what that could be." },
    ],
  },
  {
    word: "wooden",
    sentences: [
      { id: 44961, text: "The garden was surrounded by a wooden fence." },
      { id: 274599, text: "The village people built a wooden bridge across the river." },
      { id: 3174723, text: "The children played with wooden blocks." },
    ],
  },
  {
    word: "pot",
    sentences: [
      { id: 3695304, text: "I use a big pot to cook soup." },
      { id: 36285, text: "The soup in the pot tasted very salty." },
      { id: 9444365, text: "The big cooking pot is on the kitchen table." },
    ],
  },
  {
    word: "cow",
    sentences: [
      { id: 9208744, text: "Do you know how to milk a cow?" },
      { id: 6921170, text: "The cow was milked twice a day." },
      { id: 1719234, text: "Have you ever milked a cow?" },
    ],
  },
  {
    word: "fold",
    sentences: [
      { id: 8204493, text: "Can you help me fold the clothes?" },
      { id: 9418842, text: "Fold the paper in half." },
      { id: 10738798, text: "What else can you fold from paper?" },
    ],
  },
  {
    word: "bin",
    sentences: [
      { id: 9721923, text: "I threw the book in the bin." },
      { id: 11970202, text: "Throw it in the bin." },
      { id: 13866030, text: "We need a bigger bin." },
    ],
  },
  {
    word: "shell",
    sentences: [
      { id: 256744, text: "I found a beautiful shell on the shore." },
    ],
  },
  {
    word: "cheese",
    sentences: [
      { id: 19457, text: "We make milk into cheese and butter." },
      { id: 453075, text: "I bought some cheese and milk." },
      { id: 6439291, text: "How much cheese did you eat?" },
    ],
  },
  {
    word: "pipe",
    sentences: [
      { id: 270742, text: "Water poured from the broken pipe." },
      { id: 681732, text: "Water was coming out of the damaged pipe." },
      { id: 272242, text: "The oil ran through a thick pipe." },
    ],
  },
  {
    word: "guitar",
    sentences: [
      { id: 5818021, text: "I like singing and playing the guitar." },
      { id: 3474351, text: "Tom played the guitar and Mary sang." },
      { id: 6074489, text: "Would you like to learn to play the guitar?" },
    ],
  },
  {
    word: "flag",
    sentences: [
      { id: 13203813, text: "When the school day starts, the students raise the national flag." },
      { id: 3170729, text: "I see someone waving a white flag." },
      { id: 11182042, text: "Which flag is white, red, and blue?" },
    ],
  },
  {
    word: "piano",
    sentences: [
      { id: 5995406, text: "Would you like to learn to play the piano?" },
      { id: 4013795, text: "I could hear Tom playing the piano." },
      { id: 69786, text: "I hear that you play the piano." },
    ],
  },
  {
    word: "magic",
    sentences: [
      { id: 12863988, text: "Do you know how to do any magic tricks?" },
      { id: 250181, text: "I wish I could use magic." },
      { id: 6520571, text: "Do Tom and Mary believe in magic?" },
    ],
  },
  {
    word: "whisper",
    sentences: [
      { id: 8839522, text: "Tom lowered his voice to a whisper." },
      { id: 314224, text: "She spoke to me in a whisper." },
      { id: 3726256, text: "Let me whisper in your ear." },
    ],
  },
  {
    word: "menu",
    sentences: [
      { id: 31789, text: "There was a great variety of dishes on the menu." },
      { id: 277784, text: "Can I order from the breakfast menu?" },
      { id: 6915170, text: "Here is the lunch menu." },
    ],
  },
  {
    word: "moon",
    sentences: [
      { id: 9803721, text: "Who was the first person to walk on the moon?" },
      { id: 8074888, text: "Fifty years ago, the first humans landed on the moon." },
      { id: 328748, text: "How does the moon shine at night?" },
    ],
  },
  {
    word: "grandmother",
    sentences: [
      { id: 251368, text: "My grandmother goes for a walk in the evening." },
      { id: 1447110, text: "My grandmother can cook very well." },
      { id: 273894, text: "My grandmother lived to be ninety-five years old." },
    ],
  },
  {
    word: "coin",
    sentences: [
      { id: 3474596, text: "Tom pulled a coin out of his pocket." },
      { id: 3386121, text: "Tom found an ancient gold coin." },
      { id: 5830783, text: "The game begins with a coin toss." },
    ],
  },
  {
    word: "trick",
    sentences: [
      { id: 6020456, text: "Can you figure out how I did that magic trick?" },
      { id: 5817692, text: "Can you show me another magic trick?" },
      { id: 7543265, text: "Tom is teaching Mary a card trick." },
    ],
  },
  {
    word: "chocolate",
    sentences: [
      { id: 5667708, text: "Do you want some hot chocolate?" },
      { id: 11145341, text: "Tom ate a bar of dark chocolate." },
      { id: 1211470, text: "What chocolate do you like to eat?" },
    ],
  },
  {
    word: "belt",
    sentences: [
      { id: 12659052, text: "You must always wear a seat belt when driving." },
      { id: 3155588, text: "Put your seat belt on." },
    ],
  },
  {
    word: "potato",
    sentences: [
      { id: 6620542, text: "Tom ate a baked potato." },
      { id: 6590492, text: "Would you like some potato soup?" },
    ],
  },
  {
    word: "stair",
    sentences: [
      { id: 13336156, text: "Tom missed a stair and fell." },
      { id: 9733237, text: "He sat down on the last stair to wait for his friend." },
    ],
  },
  {
    word: "shine",
    sentences: [
      { id: 12770659, text: "Why do the stars shine so brightly for us?" },
      { id: 238829, text: "The moon does not shine as brightly as the sun." },
      { id: 7637279, text: "Did the stars shine bright last night?" },
    ],
  },
  {
    word: "stomach",
    sentences: [
      { id: 12960125, text: "My stomach hurts because I ate a lot." },
      { id: 4515066, text: "After eating the ice cream, my stomach began to hurt." },
      { id: 6412255, text: "Mary has an upset stomach because she ate too much." },
    ],
  },
  {
    word: "golden",
    sentences: [
      { id: 46453, text: "The girl has golden hair." },
      { id: 10803788, text: "Bake until golden brown." },
    ],
  },
  {
    word: "stamp",
    sentences: [
      { id: 3155851, text: "Tom put a stamp on the letter." },
      { id: 319644, text: "Stick another stamp on the envelope." },
      { id: 3871280, text: "Do you want to see my stamp collection?" },
    ],
  },
  {
    word: "envelope",
    sentences: [
      { id: 10538209, text: "I opened the envelope and pulled out the letter." },
      { id: 3156825, text: "Tom folded the letter and put it into the envelope." },
      { id: 7241285, text: "The secretary stuffed the letter into an envelope." },
    ],
  },
  {
    word: "bite",
    sentences: [
      { id: 2958311, text: "Tom took a bite out of the apple." },
      { id: 10546862, text: "Tie up the dog so he does not bite anyone.", changed: true },
    ],
  },
  {
    word: "adventure",
    sentences: [
      { id: 3118247, text: "I want to explore the world and go on an adventure." },
      { id: 11373246, text: "Every trip is an adventure." },
      { id: 13816663, text: "Every day is a new adventure." },
    ],
  },
  {
    word: "fence",
    sentences: [
      { id: 239180, text: "The dog jumped over the fence into the garden." },
      { id: 319303, text: "My father put a fence around the garden." },
      { id: 6263559, text: "Tom hit the ball over the fence." },
    ],
  },
  {
    word: "ocean",
    sentences: [
      { id: 9591592, text: "I love swimming in the ocean." },
      { id: 681608, text: "Tom sailed across the ocean in five days." },
      { id: 3663459, text: "There are islands in the ocean." },
    ],
  },
  {
    word: "castle",
    sentences: [
      { id: 974174, text: "The children on the beach are building a sand castle." },
      { id: 1117133, text: "A king lived in an old castle." },
      { id: 6133861, text: "The castle is surrounded by a beautiful garden." },
    ],
  },
  {
    word: "carpet",
    sentences: [
      { id: 4903267, text: "The dog is sitting on the carpet." },
      { id: 12799922, text: "I need to buy a new carpet for this room." },
      { id: 46268, text: "The floor is covered with a thick carpet." },
    ],
  },
  {
    word: "hurry",
    sentences: [
      { id: 7733081, text: "We have to hurry or we will be late.", changed: true },
      { id: 662668, text: "If you hurry, you can make it." },
      { id: 7735056, text: "We can still make it on time if we hurry." },
    ],
  },
  {
    word: "bell",
    sentences: [
      { id: 1097561, text: "When the bell rang, the teacher ended the class." },
      { id: 10291315, text: "The school bell rings and the day begins." },
      { id: 33883, text: "The bell rang and the train moved off." },
    ],
  },
  {
    word: "liquid",
    sentences: [
      { id: 270794, text: "Water is liquid. When it freezes, it becomes solid." },
      { id: 239898, text: "When a solid melts, it becomes liquid." },
      { id: 9799598, text: "There is a white liquid in the large bottle." },
    ],
  },
  {
    word: "uncle",
    sentences: [
      { id: 240614, text: "The man you see over there is my uncle." },
      { id: 12170559, text: "My uncle owns a farm in the village." },
      { id: 65069, text: "My uncle lives near the school." },
    ],
  },
  {
    word: "rice",
    sentences: [
      { id: 8014804, text: "Most of the farmers around here grow rice." },
      { id: 54340, text: "Which do you prefer, rice or bread?" },
      { id: 54337, text: "Do you know how to cook rice well?" },
    ],
  },
  {
    word: "silly",
    sentences: [
      { id: 38739, text: "How can you say such a silly thing?" },
      { id: 13408220, text: "Why are you acting so silly?" },
      { id: 12424757, text: "Tom gets confused and says silly things sometimes." },
    ],
  },
  {
    word: "harbour",
    sentences: [
      { id: 10744265, text: "We saw many ships in the harbour." },
      { id: 435250, text: "The lost fishing boat made a safe return to harbour." },
      { id: 9953259, text: "The fishing boats were leaving harbour." },
    ],
  },
  {
    word: "sheep",
    sentences: [
      { id: 1108091, text: "The sheep in the field are eating grass." },
      { id: 2801787, text: "Every day, I look after the sheep." },
      { id: 8783218, text: "We look after our sheep." },
    ],
  },
  {
    word: "rat",
    sentences: [
      { id: 7010682, text: "The cat is much larger than the rat." },
      { id: 4647243, text: "Tom saw a large rat run across the street." },
      { id: 12010564, text: "Dog chases cat, cat chases rat." },
    ],
  },
  {
    word: "tent",
    sentences: [
      { id: 2882254, text: "We slept in a very small tent." },
      { id: 273190, text: "We set up the tent next to the river." },
      { id: 12918835, text: "I looked out of the tent." },
    ],
  },
  {
    word: "leather",
    sentences: [
      { id: 3170608, text: "Tom keeps his important papers in a brown leather case." },
      { id: 12079108, text: "Black leather chairs surrounded the table." },
      { id: 8064039, text: "I want to buy a leather belt." },
    ],
  },
  {
    word: "stir",
    sentences: [
      { id: 12072255, text: "Add water and stir." },
      { id: 8919898, text: "Melt the chocolate, add the butter and stir well." },
      { id: 1503041, text: "If you do not stir the rice, it will burn.", changed: true },
    ],
  },
  {
    word: "slice",
    sentences: [
      { id: 13427521, text: "Can I have another slice of cake?" },
      { id: 11875117, text: "Can you slice the cake into small pieces?" },
      { id: 11095928, text: "Tom ate a slice of bread." },
    ],
  },
  {
    word: "gentle",
    sentences: [
      { id: 11888102, text: "Be gentle when you play with the dog." },
      { id: 11888848, text: "Please be gentle with your baby brother." },
      { id: 2253905, text: "There was a gentle knock on the door." },
    ],
  },
  {
    word: "tongue",
    sentences: [
      { id: 3318978, text: "Open your mouth and stick out your tongue." },
      { id: 5958322, text: "Tom bit his tongue while he was talking." },
    ],
  },
  {
    word: "wipe",
    sentences: [
      { id: 39630, text: "Will you please wipe the dust off the table?" },
      { id: 6732156, text: "Here, let me wipe down this table." },
      { id: 12091048, text: "Sit down and wipe your tears." },
    ],
  },
  {
    word: "cough",
    sentences: [
      { id: 434838, text: "Have you got a cough or a cold?" },
      { id: 11325040, text: "I have a cough because I caught a cold." },
      { id: 11892371, text: "Use your hands to cover your mouth when you cough." },
    ],
  },
  {
    word: "royal",
    sentences: [
      { id: 1573123, text: "Kate has become a full member of the royal family." },
      { id: 12775934, text: "The royal family gathered for the annual ball." },
    ],
  },
  {
    word: "curtain",
    sentences: [
      { id: 8893503, text: "I pulled back the curtain and looked outside." },
      { id: 1025218, text: "Tom hung a dark curtain over the window." },
      { id: 63830, text: "Who is hiding behind the curtain?" },
    ],
  },
  {
    word: "darkness",
    sentences: [
      { id: 323986, text: "Can you see in the darkness of the night?" },
      { id: 8946620, text: "A red light is shining in the darkness." },
      { id: 12918830, text: "I could not see anything in the darkness.", changed: true },
    ],
  },
  {
    word: "aunt",
    sentences: [
      { id: 4629244, text: "My aunt wrote me a letter last week." },
      { id: 8770133, text: "My aunt and uncle live in France." },
      { id: 13851308, text: "My aunt is a nurse in this hospital." },
    ],
  },
  {
    word: "autumn",
    sentences: [
      { id: 266344, text: "In autumn the leaves turn yellow." },
      { id: 12773581, text: "Why do trees shed their leaves in autumn?" },
      { id: 1215782, text: "The four seasons are: spring, summer, autumn and winter." },
    ],
  },
  {
    word: "cheek",
    sentences: [
      { id: 275997, text: "A big tear rolled down my cheek." },
      { id: 3774611, text: "She wiped a tear from her cheek." },
      { id: 8066766, text: "I can still see a bruise on your cheek." },
    ],
  },
  {
    word: "grin",
    sentences: [
      { id: 3315189, text: "Tom had a great big grin on his face." },
      { id: 12768577, text: "Tom opened the door with a grin." },
    ],
  },
  {
    word: "lazy",
    sentences: [
      { id: 9164207, text: "Today I am too lazy to do anything." },
      { id: 24271, text: "Stop being lazy and find something to do." },
      { id: 7518308, text: "I know that Tom is a very lazy boy." },
    ],
  },
]
