// SPDX-License-Identifier: CC-BY-2.0-FR
//
// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).
// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>
//
// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.
// "changed: true" means that we expanded a contraction, for example "don't" to "do not".
// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.

import type { TatoebaEntry } from '../bank'

export const TATOEBA_0004_BANK: readonly TatoebaEntry[] = [
  {
    word: "off",
    sentences: [
      { id: 2015126, text: "Do you want the lights on or off?" },
      { id: 5047265, text: "Turn it off, then turn it back on." },
      { id: 4014757, text: "Would you mind if I turned off the lights?" },
    ],
  },
  {
    word: "miss",
    sentences: [
      { id: 52065, text: "Leave now, or you will miss the train.", changed: true },
      { id: 3503993, text: "We will all miss you when you leave.", changed: true },
      { id: 18054, text: "We all miss you very much." },
    ],
  },
  {
    word: "buzz",
    sentences: [
      { id: 1103036, text: "Bees always buzz near the kitchen window." },
    ],
  },
  {
    word: "back",
    sentences: [
      { id: 30356, text: "Please put it back in its place." },
      { id: 30352, text: "Put it back where you found it." },
      { id: 70186, text: "When will you come back to school?" },
    ],
  },
  {
    word: "bank",
    sentences: [
      { id: 18446, text: "How much money do you have in the bank?" },
      { id: 53812, text: "Jane went to the bank to take out some money." },
      { id: 6662697, text: "I have a lot of money in the bank." },
    ],
  },
  {
    word: "sunk",
    sentences: [
      { id: 9139950, text: "The sun is already half sunk in the water." },
      { id: 518642, text: "The sun sunk below the clouds." },
      { id: 8246496, text: "The ship was sunk on purpose." },
    ],
  },
  {
    word: "rabbit",
    sentences: [
      { id: 2117, text: "A rabbit has long ears and a short tail." },
      { id: 12963056, text: "A rabbit is a small animal with long ears." },
      { id: 12104920, text: "The girl has a rabbit as a pet." },
    ],
  },
  {
    word: "carrot",
    sentences: [
      { id: 9257459, text: "Tom is eating a raw carrot." },
      { id: 11689779, text: "The carrot is good for soup." },
      { id: 4305667, text: "We are baking carrot cake." },
    ],
  },
  {
    word: "thunder",
    sentences: [
      { id: 12920507, text: "Yesterday there was thunder and lightning." },
      { id: 11149658, text: "First, I saw lightning, and then I heard thunder." },
      { id: 280666, text: "Suddenly I heard a loud clap of thunder." },
    ],
  },
  {
    word: "sunset",
    sentences: [
      { id: 11783950, text: "The sun disappeared behind the clouds just before sunset." },
      { id: 12382641, text: "The children played in the park until sunset." },
      { id: 12787135, text: "The sunset was beautiful this evening." },
    ],
  },
  {
    word: "fetch",
    sentences: [
      { id: 11892006, text: "Can you fetch the keys from the other room?" },
      { id: 263357, text: "Please fetch me a piece of paper." },
      { id: 4021960, text: "Would you fetch me a glass of water?" },
    ],
  },
  {
    word: "live",
    sentences: [
      { id: 1039514, text: "Which house do you live in?" },
      { id: 774901, text: "I want to live in a small town." },
      { id: 1027838, text: "Tom used to live near Mary." },
    ],
  },
  {
    word: "cats",
    sentences: [
      { id: 252384, text: "I like animals, for example, cats and dogs." },
      { id: 23018, text: "We can have dogs, cats, birds, and so on." },
      { id: 8455996, text: "We have both cats and dogs." },
    ],
  },
  {
    word: "dogs",
    sentences: [
      { id: 7544136, text: "Tom walks his dogs every day." },
      { id: 6021725, text: "We have a cat and several dogs." },
      { id: 8872071, text: "How long do cats and dogs live?" },
    ],
  },
  {
    word: "spends",
    sentences: [
      { id: 3486698, text: "Tom spends lots of money on clothes." },
      { id: 63737, text: "What money he earns he spends on books." },
      { id: 21363, text: "A student spends a lot of time studying." },
    ],
  },
  {
    word: "rocks",
    sentences: [
      { id: 1292958, text: "Fallen rocks blocked the road." },
      { id: 12621425, text: "The waves were crashing against the rocks." },
      { id: 20787, text: "A small stream ran down among the rocks." },
    ],
  },
  {
    word: "thanks",
    sentences: [
      { id: 453162, text: "A big thanks for your help." },
      { id: 10162917, text: "Many thanks for the quick answer!" },
      { id: 9466034, text: "Once again, thanks for all your help." },
    ],
  },
  {
    word: "catches",
    sentences: [
      { id: 5725266, text: "Not everyone who goes fishing catches fish." },
      { id: 250482, text: "Even if my house catches fire it would soon be put out." },
    ],
  },
  {
    word: "hunting",
    sentences: [
      { id: 4042257, text: "Tom and Mary went hunting for Easter eggs." },
      { id: 5280903, text: "Would you prefer to go fishing or hunting?" },
      { id: 2011967, text: "Tom wants to go job hunting." },
    ],
  },
  {
    word: "hunted",
    sentences: [
      { id: 293805, text: "He hunted for his missing cat all day." },
      { id: 12822587, text: "He hunted large animals." },
    ],
  },
  {
    word: "hunter",
    sentences: [
      { id: 13550119, text: "Every day, the hunter goes to the fields with his dog." },
      { id: 12345305, text: "The hunter has a horse and two dogs." },
      { id: 12286621, text: "Tom is a good hunter." },
    ],
  },
  {
    word: "buzzing",
    sentences: [
      { id: 9440170, text: "Have you ever heard a bee buzzing?" },
      { id: 1904264, text: "A bee is buzzing around." },
      { id: 11045190, text: "Bees were buzzing around the flowers." },
    ],
  },
  {
    word: "buzzed",
    sentences: [
      { id: 12768564, text: "The phone buzzed in his pocket." },
      { id: 237747, text: "The crowd buzzed with excitement." },
      { id: 2474224, text: "The audience buzzed with excitement." },
    ],
  },
  {
    word: "buzzer",
    sentences: [
      { id: 3472533, text: "Tom pressed the buzzer three times." },
      { id: 12163725, text: "Please press the buzzer." },
      { id: 2547594, text: "Tom heard the buzzer." },
    ],
  },
  {
    word: "jumping",
    sentences: [
      { id: 3730048, text: "Tom is jumping up and down with joy." },
      { id: 11017728, text: "The boys were jumping for joy." },
      { id: 5006847, text: "Stop jumping on the bed!" },
    ],
  },
  {
    word: "jumped",
    sentences: [
      { id: 4132535, text: "Tom jumped out of bed and ran to the window." },
      { id: 2117569, text: "I jumped for joy when I heard the news." },
      { id: 291156, text: "Hearing the news, he jumped out of his chair." },
    ],
  },
  {
    word: "jumper",
    sentences: [
      { id: 10555351, text: "Since I was cold, I put on a jumper." },
      { id: 11074083, text: "As it became warmer, I took off my jumper." },
      { id: 7897159, text: "Tom put on a warm jumper." },
    ],
  },
  {
    word: "fresher",
    sentences: [
      { id: 10121766, text: "Your bread is fresher than mine." },
      { id: 57512, text: "The eggs in this case are fresher than those in the other case." },
      { id: 663793, text: "I have a much fresher piece of bread than you." },
    ],
  },
  {
    word: "quicker",
    sentences: [
      { id: 12321874, text: "Which is quicker, a taxi or the tube?" },
      { id: 394690, text: "If you do it a bit slower, it goes quicker." },
      { id: 8815052, text: "The injury healed quicker than expected." },
    ],
  },
  {
    word: "quickest",
    sentences: [
      { id: 9493966, text: "Which is the quickest way to the bus station?" },
      { id: 243682, text: "The quickest means of travel is by plane." },
      { id: 317995, text: "Flying is the quickest method of travelling." },
    ],
  },
  {
    word: "stay",
    sentences: [
      { id: 18059, text: "You may stay here as long as you like." },
      { id: 247108, text: "I want you to stay here until I get back." },
      { id: 465961, text: "Does Tom have to stay home today?" },
    ],
  },
  {
    word: "enjoy",
    sentences: [
      { id: 2490723, text: "I think you will really enjoy reading this book.", changed: true },
      { id: 2390829, text: "I really enjoy spending time with you." },
      { id: 56271, text: "We hope you will enjoy the show." },
    ],
  },
  {
    word: "annoy",
    sentences: [
      { id: 9431953, text: "That noise is probably going to annoy Tom." },
      { id: 5385887, text: "She does nothing but annoy me all day long." },
      { id: 11636790, text: "Every little thing seems to annoy Tom." },
    ],
  },
  {
    word: "same",
    sentences: [
      { id: 2961443, text: "Does Tom go to the same school as Mary?" },
      { id: 2435053, text: "Tom lives in the same part of town as Mary." },
      { id: 1213439, text: "I eat and read at the same time." },
    ],
  },
  {
    word: "theme",
    sentences: [
      { id: 285210, text: "What is the theme of his latest novel?" },
      { id: 10793465, text: "The book is divided into four sections, each with a specific theme." },
      { id: 11886056, text: "Are you planning a theme party?" },
    ],
  },
  {
    word: "five",
    sentences: [
      { id: 1025671, text: "Tom goes to school five days a week." },
      { id: 6841959, text: "I will ask you five questions." },
      { id: 6784092, text: "Tom wants to learn five languages." },
    ],
  },
  {
    word: "side",
    sentences: [
      { id: 8593848, text: "We drive on the left side of the road." },
      { id: 6665396, text: "Tom walked to the other side of the room." },
      { id: 5535292, text: "On which side of the bed do you sleep?" },
    ],
  },
  {
    word: "woke",
    sentences: [
      { id: 255725, text: "I woke up at the sound of the alarm." },
      { id: 5547889, text: "When I woke up, it was still dark outside." },
      { id: 2640503, text: "Tom woke up the next morning feeling great." },
    ],
  },
  {
    word: "hope",
    sentences: [
      { id: 274000, text: "I hope you get well soon." },
      { id: 1324026, text: "I hope you have a great day!" },
      { id: 52109, text: "I hope to hear from you soon." },
    ],
  },
  {
    word: "hole",
    sentences: [
      { id: 8436789, text: "Tom dug a big hole in the garden." },
      { id: 7953952, text: "Tom cut a hole in the wall." },
      { id: 10738016, text: "My roof has a hole in it." },
    ],
  },
  {
    word: "rude",
    sentences: [
      { id: 8254579, text: "Did Tom say something rude to you?" },
      { id: 12120460, text: "What a rude thing to say!" },
      { id: 10775806, text: "Is it rude to ask a woman her age?" },
    ],
  },
  {
    word: "use",
    sentences: [
      { id: 6257666, text: "How often do you use a computer?" },
      { id: 886216, text: "People use computers for both games and work." },
      { id: 245465, text: "Please do not use the phone while working." },
    ],
  },
  {
    word: "tube",
    sentences: [
      { id: 10791635, text: "I go to school every day by tube." },
      { id: 11053729, text: "Does the tube stop at the next station?" },
      { id: 10568020, text: "You can get to the station either by bus or tube." },
    ],
  },
  {
    word: "tune",
    sentences: [
      { id: 8883891, text: "A man is playing a tune on the guitar." },
      { id: 9399439, text: "Tom began to play a tune on the piano." },
      { id: 9764167, text: "The band was playing a slow tune." },
    ],
  },
  {
    word: "start",
    sentences: [
      { id: 5144446, text: "What time does school start in the morning?" },
      { id: 3516208, text: "We must start at the beginning." },
      { id: 4013224, text: "What time does the first game start?" },
    ],
  },
  {
    word: "meet",
    sentences: [
      { id: 2543843, text: "I meet new people every day." },
      { id: 3524189, text: "When do I get to meet Tom?" },
      { id: 24585, text: "What time and where could we meet?" },
    ],
  },
  {
    word: "week",
    sentences: [
      { id: 27731, text: "How many days a week do you go to school?" },
      { id: 46724, text: "The class meets once a week." },
      { id: 2956786, text: "Tom goes shopping at least once a week." },
    ],
  },
  {
    word: "dream",
    sentences: [
      { id: 16198, text: "Do you ever dream about flying through the sky?" },
      { id: 27558, text: "You can make your dream come true by working hard." },
      { id: 11006276, text: "I dream of being happy one day." },
    ],
  },
  {
    word: "instead",
    sentences: [
      { id: 6238322, text: "Tom decided to walk instead of taking the bus." },
      { id: 294968, text: "By mistake, he turned left instead of right." },
      { id: 256636, text: "I stayed at home instead of going out." },
    ],
  },
  {
    word: "sound",
    sentences: [
      { id: 2303407, text: "I love the sound of rain falling." },
      { id: 10789800, text: "I could hear the sound of Tom breathing." },
      { id: 7240867, text: "How do we know light travels faster than sound?" },
    ],
  },
  {
    word: "better",
    sentences: [
      { id: 2265929, text: "Far from getting better, he gets worse every day." },
      { id: 70063, text: "Which do you like better, this or that?" },
      { id: 2348263, text: "Come on, you can do better than this!" },
    ],
  },
  {
    word: "under",
    sentences: [
      { id: 930399, text: "Come out from under the table!" },
      { id: 11418984, text: "May I sleep outside with you under the stars tonight?" },
    ],
  },
  {
    word: "first",
    sentences: [
      { id: 3162812, text: "As expected, he won first place." },
      { id: 5201587, text: "I want to get it right the first time." },
      { id: 3733752, text: "At first, I could not understand anything.", changed: true },
    ],
  },
  {
    word: "third",
    sentences: [
      { id: 5272862, text: "Tom lives on the third floor." },
      { id: 6269404, text: "Tom ended up in third place." },
      { id: 3819718, text: "Tom read the letter a third time." },
    ],
  },
  {
    word: "turn",
    sentences: [
      { id: 2827385, text: "You need to turn left at the second light." },
      { id: 1492176, text: "Please turn off the light before leaving the room." },
      { id: 1030726, text: "Could you turn the music down?" },
    ],
  },
  {
    word: "church",
    sentences: [
      { id: 10712735, text: "You can hear the church bells from there." },
      { id: 8977869, text: "Many people go to church on Easter Day." },
      { id: 9381160, text: "Tom and Mary usually walk to church together." },
    ],
  },
  {
    word: "zoo",
    sentences: [
      { id: 11881799, text: "What animals do you see at the zoo?" },
      { id: 9163961, text: "Tom took his daughter to the zoo." },
      { id: 7873644, text: "The animals at this zoo are well cared for." },
    ],
  },
  {
    word: "toe",
    sentences: [
      { id: 7894997, text: "I hurt my big toe." },
      { id: 243506, text: "Someone stepped on my toe in the crowded bus." },
      { id: 10939803, text: "I hit my foot against the door and hurt a toe." },
    ],
  },
  {
    word: "around",
    sentences: [
      { id: 1078035, text: "The family members sat around the table." },
      { id: 2540777, text: "Tom turned around and faced Mary." },
      { id: 69676, text: "Can you go around the world in a day?" },
    ],
  },
  {
    word: "down",
    sentences: [
      { id: 1130098, text: "What goes up must come down." },
      { id: 1841478, text: "Tom and Mary sat down to eat." },
      { id: 3223013, text: "Would you like to sit down?" },
    ],
  },
  {
    word: "own",
    sentences: [
      { id: 8442576, text: "How many houses do you own?" },
      { id: 11915824, text: "Does Tom still own this land?" },
      { id: 6515353, text: "Do Tom and Mary own any other property?" },
    ],
  },
  {
    word: "blow",
    sentences: [
      { id: 5336161, text: "A strong wind began to blow." },
      { id: 6142491, text: "Where does the wind blow from?" },
      { id: 12361285, text: "The wind used to blow all day." },
    ],
  },
  {
    word: "grow",
    sentences: [
      { id: 12545504, text: "Let the grass grow. Give some animals a home." },
      { id: 15915, text: "What do you want to be when you grow up?" },
      { id: 405341, text: "What will you do when you grow up?" },
    ],
  },
  {
    word: "show",
    sentences: [
      { id: 6126474, text: "Tom will show you how to do that." },
      { id: 2308172, text: "I could show you how this works." },
      { id: 1141002, text: "Tom wants to show you something." },
    ],
  },
  {
    word: "clue",
    sentences: [
      { id: 291771, text: "At last, he found a clue to the mystery." },
      { id: 4889516, text: "Do you have any clue to the mystery?" },
      { id: 11668654, text: "I have no clue how to solve this problem." },
    ],
  },
  {
    word: "true",
    sentences: [
      { id: 7131778, text: "Do you believe this to be true?" },
      { id: 10326022, text: "Do you think that dreams come true?" },
      { id: 2941649, text: "I knew it was too good to be true." },
    ],
  },
  {
    word: "rescue",
    sentences: [
      { id: 8101203, text: "Tom ran into the burning house to rescue Mary." },
      { id: 6048595, text: "I hope someone comes to rescue us." },
      { id: 29516, text: "The rescue party searched for the missing passengers." },
    ],
  },
  {
    word: "new",
    sentences: [
      { id: 2643568, text: "Tom loves to try new things." },
      { id: 3469172, text: "A few days later, Tom found a new job." },
      { id: 1824576, text: "I learn new things every day." },
    ],
  },
  {
    word: "few",
    sentences: [
      { id: 73014, text: "May I ask a few questions?" },
      { id: 280820, text: "Please walk back a few steps." },
      { id: 264251, text: "The next meeting will take place in a few days." },
    ],
  },
  {
    word: "grew",
    sentences: [
      { id: 253665, text: "I grew up in this small town." },
      { id: 46312, text: "The boy grew up to be a great man." },
      { id: 258302, text: "I remember the house where I grew up." },
    ],
  },
  {
    word: "flew",
    sentences: [
      { id: 12768425, text: "A bird flew past the window." },
      { id: 2123489, text: "The bird flew up into the blue sky." },
      { id: 10650497, text: "The planes flew over the island." },
    ],
  },
  {
    word: "drew",
    sentences: [
      { id: 681365, text: "Tom drew a straight line on the paper." },
      { id: 5293081, text: "Tom drew a circle in the sand with a stick." },
      { id: 7132257, text: "Can you tell me who drew this picture?" },
    ],
  },
  {
    word: "threw",
    sentences: [
      { id: 12292248, text: "The children threw stones into the water." },
      { id: 12766400, text: "I threw the old newspapers away." },
      { id: 5966544, text: "I threw the paper into the fire." },
    ],
  },
  {
    word: "lie",
    sentences: [
      { id: 16306, text: "You must not tell a lie." },
      { id: 3329452, text: "I would like to lie down for a few minutes.", changed: true },
      { id: 246436, text: "When have I told a lie?" },
    ],
  },
  {
    word: "pie",
    sentences: [
      { id: 3315051, text: "Would you like a nice big piece of apple pie?" },
      { id: 50028, text: "Did you really bake the pie by yourself?" },
      { id: 9520558, text: "Tom brought me a slice of pie." },
    ],
  },
  {
    word: "cried",
    sentences: [
      { id: 14021069, text: "When I read that book, I cried." },
      { id: 8473054, text: "I almost cried when Tom left." },
      { id: 5669161, text: "I laughed so hard I cried." },
    ],
  },
  {
    word: "tried",
    sentences: [
      { id: 3820397, text: "Tom tried to open the door, but he could not.", changed: true },
      { id: 2335898, text: "I tried to get up, but I fell down again." },
      { id: 3515056, text: "Have you tried doing this before?" },
    ],
  },
  {
    word: "dried",
    sentences: [
      { id: 6661660, text: "I got out of the bath and dried off." },
      { id: 45757, text: "The river has dried up." },
      { id: 12917076, text: "Which dried fruit do you like best?" },
    ],
  },
  {
    word: "field",
    sentences: [
      { id: 681330, text: "The team captain led the players onto the field." },
      { id: 9803728, text: "All the players walked off the field." },
      { id: 11887436, text: "Are you going on a school field trip?" },
    ],
  },
  {
    word: "thief",
    sentences: [
      { id: 19214, text: "A thief broke into the house to steal the money." },
      { id: 3902884, text: "When the thief heard the dog bark, he ran away." },
      { id: 5650517, text: "Unless caught stealing, one is not a thief." },
    ],
  },
  {
    word: "short",
    sentences: [
      { id: 6942438, text: "Do you prefer to have long hair or short hair?" },
      { id: 3844663, text: "Does Tom want it long, or short?" },
      { id: 6783906, text: "Tom will be here for just a short time." },
    ],
  },
  {
    word: "born",
    sentences: [
      { id: 8400348, text: "Tom was born and raised in a small town." },
      { id: 6659214, text: "Tom and Mary were born on the same day." },
      { id: 9774552, text: "How many babies have been born?" },
    ],
  },
  {
    word: "score",
    sentences: [
      { id: 13927785, text: "Our team needs to score one more goal to win the match." },
      { id: 9462371, text: "How many points did Tom score?" },
      { id: 243952, text: "The final score was two to nothing." },
    ],
  },
  {
    word: "wore",
    sentences: [
      { id: 244527, text: "I wore a hat yesterday because it was very cold." },
      { id: 7734297, text: "Mary wore a blue dress to the party." },
      { id: 6342472, text: "When was the last time you wore a uniform?" },
    ],
  },
  {
    word: "shore",
    sentences: [
      { id: 248647, text: "We walked along the shore of the lake." },
      { id: 12851212, text: "The waves crashed into the shore." },
      { id: 4988321, text: "The waves usually break when they reach the shore." },
    ],
  },
  {
    word: "saw",
    sentences: [
      { id: 239271, text: "When we looked down, we saw many buildings." },
      { id: 3066887, text: "Tom looked up and saw Mary standing there." },
      { id: 2952405, text: "I saw Tom come out of the house." },
    ],
  },
  {
    word: "yawn",
    sentences: [
      { id: 322713, text: "We yawn when sleepy or bored." },
      { id: 7546797, text: "I always yawn when I am sleepy.", changed: true },
      { id: 530021, text: "When you yawn, cover your mouth with your hand." },
    ],
  },
  {
    word: "crawl",
    sentences: [
      { id: 9803932, text: "Babies learn to crawl before they learn to walk." },
      { id: 45867, text: "The baby began to crawl." },
      { id: 2331770, text: "I had to crawl under the fence." },
    ],
  },
  {
    word: "dinosaur",
    sentences: [
      { id: 12027738, text: "What is the largest dinosaur that ever lived?", changed: true },
      { id: 1008898, text: "That scientist is looking for dinosaur bones in the valley." },
      { id: 4463189, text: "Scientists have discovered a new species of dinosaur." },
    ],
  },
  {
    word: "astronaut",
    sentences: [
      { id: 8672723, text: "The astronaut walked on the moon." },
      { id: 680270, text: "Would you like to be an astronaut?" },
      { id: 6234472, text: "One of my brothers wants to become an astronaut." },
    ],
  },
  {
    word: "fair",
    sentences: [
      { id: 2932199, text: "Would it be fair to the others?" },
      { id: 8851165, text: "You must have your fair share of the tasks." },
      { id: 7129636, text: "Do you think that the fine was fair?" },
    ],
  },
  {
    word: "pair",
    sentences: [
      { id: 6253301, text: "I need to buy a new pair of shoes." },
      { id: 11746181, text: "I only have one pair of glasses." },
      { id: 4133455, text: "I bought myself a new pair of boots." },
    ],
  },
  {
    word: "dear",
    sentences: [
      { id: 773144, text: "Hi, how are you, my dear friend?" },
      { id: 2277612, text: "I love you, dear sister." },
      { id: 8221086, text: "Wishing you success forever, my dear friend." },
    ],
  },
  {
    word: "hear",
    sentences: [
      { id: 325962, text: "I can hear someone talking in the next room." },
      { id: 2301246, text: "I can hear Tom talking in the other room." },
      { id: 2308128, text: "I could hear Tom and Mary talking." },
    ],
  },
  {
    word: "beard",
    sentences: [
      { id: 2450926, text: "The old man had a long grey beard." },
      { id: 4921453, text: "Tom grew a long beard." },
      { id: 12268476, text: "You look younger without a beard." },
    ],
  },
  {
    word: "near",
    sentences: [
      { id: 9637473, text: "We live very near the school." },
      { id: 9958170, text: "I live near the train station." },
      { id: 21569, text: "Living near the school, I usually walk there." },
    ],
  },
  {
    word: "year",
    sentences: [
      { id: 17630, text: "How old will you be next year?" },
      { id: 2169048, text: "I studied there a year ago." },
      { id: 5250542, text: "I hope to see you next year." },
    ],
  },
  {
    word: "pear",
    sentences: [
      { id: 11128993, text: "The apple and the pear are fruit." },
      { id: 13632226, text: "Do you want a pear, an apple, or both?" },
      { id: 9702585, text: "This is a pear tree." },
    ],
  },
  {
    word: "bare",
    sentences: [
      { id: 6684837, text: "The floor was cold under his bare feet." },
      { id: 12463490, text: "Can you catch a fish with your bare hands?" },
      { id: 12268065, text: "Tom caught the fish with his bare hands." },
    ],
  },
  {
    word: "dare",
    sentences: [
      { id: 9823028, text: "Only those who dare to dream change the world." },
      { id: 5442682, text: "Few people dare to say the truth." },
    ],
  },
  {
    word: "care",
    sentences: [
      { id: 1092645, text: "Tom took very good care of Mary." },
      { id: 1094538, text: "Tom does not care what other people think.", changed: true },
      { id: 2538447, text: "We have families we have to take care of." },
    ],
  },
  {
    word: "share",
    sentences: [
      { id: 10598465, text: "Tom does not share his food with anyone.", changed: true },
      { id: 274140, text: "May I share this table with you?" },
      { id: 2019161, text: "I want to share my thoughts with you." },
    ],
  },
  {
    word: "scared",
    sentences: [
      { id: 3819889, text: "I was so scared that I could hardly think." },
      { id: 6002320, text: "Tom was too scared to walk home by himself." },
      { id: 2239643, text: "Do not be scared to meet new people.", changed: true },
    ],
  },
  {
    word: "dolphin",
    sentences: [
      { id: 7274063, text: "The dolphin jumped out of the water." },
      { id: 11664441, text: "The dolphin is a beautiful animal." },
      { id: 11952170, text: "The dolphin is not a fish." },
    ],
  },
  {
    word: "alphabet",
    sentences: [
      { id: 2761494, text: "Have you learned all the letters in the alphabet?" },
      { id: 12130188, text: "What is the first letter of the alphabet?" },
      { id: 967742, text: "How many letters are there in the English alphabet?" },
    ],
  },
  {
    word: "elephant",
    sentences: [
      { id: 268257, text: "An elephant is a very large animal." },
      { id: 268259, text: "The elephant is the largest land animal." },
      { id: 6862508, text: "Everybody knows that the ears of an elephant are large." },
    ],
  },
  {
    word: "sketch",
    sentences: [
      { id: 3436650, text: "Tom is drawing a sketch of the house." },
      { id: 17290, text: "Make a sketch of your house." },
      { id: 3022623, text: "Draw me a sketch of the first floor." },
    ],
  },
  {
    word: "kit",
    sentences: [
      { id: 2541119, text: "I have a first aid kit in my car." },
      { id: 10754281, text: "What should be in a first aid kit?" },
      { id: 10741453, text: "Tom is wearing his football kit." },
    ],
  },
  {
    word: "unhappy",
    sentences: [
      { id: 10936336, text: "An unhappy mother does not raise a happy child." },
      { id: 2957073, text: "Tom is clearly unhappy to be here." },
      { id: 7732127, text: "Tom seemed really unhappy about that." },
    ],
  },
  {
    word: "undo",
    sentences: [
      { id: 12078665, text: "Just undo the button." },
      { id: 545272, text: "You cannot undo what has already been done." },
      { id: 320950, text: "Please undo the package." },
    ],
  },
  {
    word: "unload",
    sentences: [
      { id: 6273178, text: "Tom helped Mary unload the car." },
      { id: 6349338, text: "I helped Tom unload his van." },
      { id: 11911604, text: "Let us unload the car later.", changed: true },
    ],
  },
  {
    word: "unfair",
    sentences: [
      { id: 11412069, text: "Life can be unfair at times." },
      { id: 5635821, text: "You are being very unfair to me." },
      { id: 9631532, text: "What exactly do you think is unfair?" },
    ],
  },
  {
    word: "unlock",
    sentences: [
      { id: 13124871, text: "I need those keys to unlock the door." },
      { id: 11886604, text: "Where is the key to unlock the door?" },
      { id: 11882302, text: "Can you unlock your phone?" },
    ],
  },
  {
    word: "playground",
    sentences: [
      { id: 13178390, text: "She likes to play with her friends at the playground." },
      { id: 10843829, text: "There are a lot of kids on the playground." },
      { id: 11895241, text: "When the bell rang, the pupils went out into the playground to play." },
    ],
  },
]
