// SPDX-License-Identifier: CC-BY-2.0-FR
//
// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).
// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>
//
// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.
// "changed: true" means that we expanded a contraction, for example "don't" to "do not".
// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.

import type { TatoebaEntry } from '../bank'

export const TATOEBA_0009_BANK: readonly TatoebaEntry[] = [
  {
    word: "manners",
    sentences: [
      { id: 10651204, text: "Good manners are important for living well together." },
      { id: 276380, text: "Who taught them table manners?" },
      { id: 11698360, text: "Mind your table manners." },
    ],
  },
  {
    word: "dishes",
    sentences: [
      { id: 1830414, text: "Tom finished eating then washed the dishes." },
      { id: 462664, text: "The cook prepares different dishes every day." },
      { id: 7768481, text: "What dishes do you like to eat?" },
    ],
  },
  {
    word: "habit",
    sentences: [
      { id: 9188752, text: "Make a habit of going to sleep early." },
      { id: 259175, text: "I have to form the habit of getting up early." },
      { id: 9387663, text: "What are some good ways to break a bad habit?" },
    ],
  },
  {
    word: "modern",
    sentences: [
      { id: 1517082, text: "More modern buildings are safer than older ones." },
      { id: 1756432, text: "I like classical music more than modern music." },
      { id: 239634, text: "What do you think of modern art?" },
    ],
  },
  {
    word: "event",
    sentences: [
      { id: 11884554, text: "Anyone can attend this free event." },
      { id: 680854, text: "The wedding is going to be quite an event." },
      { id: 61325, text: "Would you take part in this event?" },
    ],
  },
  {
    word: "fond",
    sentences: [
      { id: 413337, text: "Ann is exceedingly fond of chocolate." },
      { id: 69709, text: "Are you fond of listening to the radio?" },
      { id: 2728491, text: "I am not fond of pets." },
    ],
  },
  {
    word: "stack",
    sentences: [
      { id: 3419987, text: "Tom came in carrying a stack of books." },
      { id: 11172780, text: "There was a stack of dirty dishes in the sink." },
      { id: 10740879, text: "There is a stack of letters on the table." },
    ],
  },
  {
    word: "snack",
    sentences: [
      { id: 13625961, text: "Crackers and cheese make a good snack." },
      { id: 10771298, text: "What do you want for an afternoon snack?" },
      { id: 7736330, text: "Tom is eating a snack." },
    ],
  },
  {
    word: "spine",
    sentences: [
      { id: 10190035, text: "The spine is made up of twenty-four bones." },
      { id: 553681, text: "The book was split along its spine." },
      { id: 11879780, text: "He repaired the damaged spine of a book." },
    ],
  },
  {
    word: "contents",
    sentences: [
      { id: 7738659, text: "The contents of the box are indicated on the label." },
      { id: 6251987, text: "Tom emptied the box of its contents." },
      { id: 2267563, text: "May I see the contents of the package?" },
    ],
  },
  {
    word: "tricky",
    sentences: [
      { id: 13642205, text: "Longer sentences are often tricky to translate." },
      { id: 10352566, text: "That was a really tricky question." },
      { id: 10791428, text: "Tom is in a tricky situation." },
    ],
  },
  {
    word: "ribs",
    sentences: [
      { id: 5669154, text: "I laughed so hard, my ribs hurt." },
      { id: 9225917, text: "Can you see my ribs?" },
    ],
  },
  {
    word: "neighbours",
    sentences: [
      { id: 13864305, text: "We greet our neighbours every morning." },
      { id: 10540274, text: "Our neighbours have got a dog." },
      { id: 71557, text: "You should do all you can to help your neighbours." },
    ],
  },
  {
    word: "astonishment",
    sentences: [
      { id: 5729016, text: "Tom looked at Mary in astonishment." },
      { id: 45224, text: "The news filled me with astonishment." },
      { id: 6981753, text: "I stared at him in astonishment." },
    ],
  },
  {
    word: "roads",
    sentences: [
      { id: 44816, text: "All the roads leading into the city are full of cars." },
      { id: 798692, text: "Both roads lead to the station." },
      { id: 5073494, text: "The roads are blocked due to the bad weather." },
    ],
  },
  {
    word: "shift",
    sentences: [
      { id: 9831124, text: "Tom now works the night shift." },
      { id: 8948730, text: "I work the morning shift." },
      { id: 7541692, text: "Tom is working the night shift this week." },
    ],
  },
  {
    word: "squashed",
    sentences: [
      { id: 1725123, text: "Have you ever squashed a fly with your hand?" },
      { id: 297993, text: "He squashed my hat flat." },
    ],
  },
  {
    word: "miracle",
    sentences: [
      { id: 10782455, text: "Only a miracle can help us now." },
      { id: 9125317, text: "By some miracle, the bus came on time." },
      { id: 11256913, text: "Because she was a fairy she could do a miracle." },
    ],
  },
  {
    word: "source",
    sentences: [
      { id: 2242813, text: "The sun is our most important source of energy." },
      { id: 4744158, text: "Are eggs a good source of protein?" },
      { id: 11094096, text: "Wind is a cheap and environmentally friendly source of energy." },
    ],
  },
  {
    word: "presents",
    sentences: [
      { id: 12934091, text: "How many Christmas presents did you get?" },
      { id: 6237300, text: "I hope I get a lot of presents for Christmas." },
      { id: 5679077, text: "Tom and Mary gave each other presents on Christmas morning." },
    ],
  },
  {
    word: "behaviour",
    sentences: [
      { id: 12137622, text: "I hope you will be on your best behaviour.", changed: true },
      { id: 11560301, text: "The teacher laid down some rules of good behaviour." },
      { id: 12965023, text: "I want you to keep up the good behaviour." },
    ],
  },
  {
    word: "meals",
    sentences: [
      { id: 11759958, text: "Most people I know eat three meals a day." },
      { id: 11760167, text: "I eat most of my meals at home." },
      { id: 13201498, text: "I want to learn how to cook healthy meals for myself." },
    ],
  },
  {
    word: "satisfaction",
    sentences: [
      { id: 254373, text: "I had the satisfaction of finishing the work." },
      { id: 2329564, text: "I get a lot of satisfaction out of my work." },
      { id: 314694, text: "She expressed satisfaction with her life." },
    ],
  },
  {
    word: "facts",
    sentences: [
      { id: 6606342, text: "The facts of the case are simple." },
      { id: 2751005, text: "Wait until all the facts in the case are known." },
      { id: 3642985, text: "There is always a right way to tell the facts." },
    ],
  },
  {
    word: "curls",
    sentences: [
      { id: 316179, text: "She keeps her hair in curls." },
      { id: 251580, text: "My hair curls easily." },
      { id: 13558211, text: "She wrapped one of her curls around her finger as she thought." },
    ],
  },
  {
    word: "grumpy",
    sentences: [
      { id: 3444657, text: "Tom is always grumpy in the morning." },
      { id: 1023742, text: "Why does Tom look so grumpy today?" },
      { id: 3144307, text: "Tom tends to be a bit grumpy." },
    ],
  },
  {
    word: "jagged",
    sentences: [
      { id: 1896045, text: "The jagged mountains were capped with snow." },
      { id: 11239842, text: "The creature had sharp and jagged teeth." },
      { id: 5273777, text: "They climbed up the jagged rocks." },
    ],
  },
  {
    word: "messy",
    sentences: [
      { id: 11812633, text: "My kitchen is always messy." },
      { id: 2660342, text: "I just cleaned my room today. Why is it so messy?" },
      { id: 9805850, text: "Are you a clean or messy person?" },
    ],
  },
  {
    word: "condition",
    sentences: [
      { id: 10195128, text: "All the engines are in good condition." },
      { id: 1826, text: "I accept, but only under one condition." },
    ],
  },
  {
    word: "steering",
    sentences: [
      { id: 3155633, text: "Put both hands on the steering wheel." },
      { id: 4876406, text: "Turning the steering wheel makes the car turn." },
      { id: 265465, text: "A car has one steering wheel." },
    ],
  },
  {
    word: "season",
    sentences: [
      { id: 8353628, text: "Which season do you like better, spring or summer?" },
      { id: 9533971, text: "The football season begins in late summer." },
      { id: 282492, text: "When will the rainy season be over?" },
    ],
  },
  {
    word: "senses",
    sentences: [
      { id: 1617284, text: "Humans have five senses: sight, hearing, touch, taste and smell." },
      { id: 13329377, text: "Dogs have senses we do not have.", changed: true },
    ],
  },
  {
    word: "version",
    sentences: [
      { id: 8808807, text: "The original version of the song sounds much better." },
      { id: 13087338, text: "I updated the software to the latest version." },
      { id: 3820669, text: "Have you heard the original version of this song?" },
    ],
  },
  {
    word: "protection",
    sentences: [
      { id: 7302735, text: "Make sure you wear eye protection." },
      { id: 12038858, text: "Do not worry, your children will be under our protection." },
    ],
  },
  {
    word: "lean",
    sentences: [
      { id: 5139596, text: "Can you lean forward a bit?" },
      { id: 2550040, text: "Do not lean out the window.", changed: true },
      { id: 11070864, text: "Do not lean against the wall. It is fresh paint.", changed: true },
    ],
  },
  {
    word: "powder",
    sentences: [
      { id: 3490704, text: "I mixed milk and chocolate powder together and then added water." },
      { id: 2774088, text: "Mix this powder with a cup of water." },
      { id: 11607543, text: "The powder is light enough to float on water." },
    ],
  },
  {
    word: "supplies",
    sentences: [
      { id: 3150751, text: "I need to buy some school supplies." },
      { id: 10569292, text: "Our food supplies are running low." },
      { id: 48138, text: "The lake supplies water to the village." },
    ],
  },
  {
    word: "soap",
    sentences: [
      { id: 11892531, text: "You should wash your hands with soap and water regularly." },
      { id: 1121203, text: "I always wash my face with soap and water." },
      { id: 3676540, text: "We wash with soap." },
    ],
  },
  {
    word: "angle",
    sentences: [
      { id: 2483428, text: "Look at things from every angle." },
      { id: 11536527, text: "Try looking at it from this angle." },
    ],
  },
  {
    word: "applause",
    sentences: [
      { id: 23204, text: "We gave the performer a round of applause." },
      { id: 4664614, text: "The audience burst into applause." },
      { id: 9662684, text: "Thank you for your kind applause." },
    ],
  },
  {
    word: "property",
    sentences: [
      { id: 9665036, text: "Tom has three apple trees on his property." },
      { id: 687760, text: "Who is the owner of this property?", changed: true },
      { id: 47799, text: "All the property will go to his daughter." },
    ],
  },
  {
    word: "beam",
    sentences: [
      { id: 2464755, text: "I was wakened by a beam of light shining through my window." },
      { id: 324021, text: "We found a beam of light in the night sky." },
      { id: 9499171, text: "The wood beam supports the roof so it does not fall in.", changed: true },
    ],
  },
  {
    word: "unknown",
    sentences: [
      { id: 11882959, text: "The cause of the crash is unknown." },
      { id: 11850835, text: "Much remains unknown about these creatures." },
      { id: 12769359, text: "I follow the stars to unknown lands." },
    ],
  },
  {
    word: "newspapers",
    sentences: [
      { id: 9951322, text: "Which newspapers do you read?" },
      { id: 43297, text: "The story was in all daily newspapers." },
      { id: 1549848, text: "Usually newspapers and magazines have many opinions." },
    ],
  },
  {
    word: "account",
    sentences: [
      { id: 6276631, text: "May I ask, can I open a bank account?" },
      { id: 12155123, text: "I have a savings account at this bank." },
      { id: 26750, text: "The game was called off on account of the rain." },
    ],
  },
  {
    word: "presence",
    sentences: [
      { id: 276940, text: "Gentlemen remove their hats in the presence of a lady." },
      { id: 272427, text: "The red flag indicated the presence of danger." },
      { id: 12109209, text: "I sense a comforting presence in the house." },
    ],
  },
  {
    word: "background",
    sentences: [
      { id: 9763451, text: "I like to read with music playing in the background." },
      { id: 12180926, text: "In the background of the picture is a castle." },
      { id: 271994, text: "Paint the trees against the background of the blue sky." },
    ],
  },
  {
    word: "blade",
    sentences: [
      { id: 2267967, text: "The blade was very sharp." },
      { id: 3872667, text: "How long is this blade?" },
    ],
  },
  {
    word: "stroke",
    sentences: [
      { id: 1439042, text: "Do not stroke the cat the wrong way.", changed: true },
      { id: 6297632, text: "Tom reached behind his neck to stroke the cat." },
      { id: 36086, text: "What a stroke of luck!" },
    ],
  },
  {
    word: "amused",
    sentences: [
      { id: 3439695, text: "Tom was amused by the joke." },
      { id: 246047, text: "The children amused themselves by playing games." },
      { id: 22752, text: "We were all greatly amused by his jokes." },
    ],
  },
  {
    word: "friendship",
    sentences: [
      { id: 6849417, text: "Tom and Mary have a close friendship." },
      { id: 8604231, text: "My friendship with you is very important to me." },
      { id: 8379294, text: "Do you know how much I value our friendship?" },
    ],
  },
  {
    word: "creepy",
    sentences: [
      { id: 11961428, text: "At night, the factory looked creepy." },
      { id: 12033655, text: "It got pretty creepy out there at night." },
      { id: 11655732, text: "The park was very woodsy and kind of creepy." },
    ],
  },
  {
    word: "items",
    sentences: [
      { id: 282506, text: "Did you check all the items on the shopping list?" },
      { id: 44892, text: "The store has numerous items to sell." },
      { id: 12486056, text: "How many items are on your list?" },
    ],
  },
  {
    word: "shorts",
    sentences: [
      { id: 11318244, text: "I like to wear shorts in summer." },
      { id: 11170545, text: "All of the boys were wearing shorts." },
      { id: 11881866, text: "Put on your gym shorts." },
    ],
  },
  {
    word: "supply",
    sentences: [
      { id: 24422, text: "Prices depend on supply and demand." },
      { id: 11724575, text: "Water and food are in short supply." },
      { id: 23310, text: "We have a plentiful supply of water." },
    ],
  },
  {
    word: "coats",
    sentences: [
      { id: 10077614, text: "We put on our coats and hats." },
      { id: 398654, text: "Black coats are in fashion this winter." },
      { id: 2835532, text: "Tom and Mary were both wearing heavy winter coats." },
    ],
  },
  {
    word: "worries",
    sentences: [
      { id: 2734377, text: "Tom always worries about his daughter." },
      { id: 4761317, text: "Is there anything that worries you right now?" },
      { id: 12128109, text: "Try to let go of worries." },
    ],
  },
  {
    word: "process",
    sentences: [
      { id: 10794817, text: "The whole process takes several months." },
      { id: 1948729, text: "I consider making mistakes an important part of the learning process." },
      { id: 3861905, text: "The entire process of manufacturing this small car takes only six hours." },
    ],
  },
  {
    word: "successful",
    sentences: [
      { id: 680842, text: "To be successful, you have to establish a good plan." },
      { id: 48524, text: "The plan has been successful so far." },
      { id: 12774027, text: "All in all, it was a successful day." },
    ],
  },
  {
    word: "sleeves",
    sentences: [
      { id: 8860255, text: "I had a shirt with short sleeves." },
      { id: 1092303, text: "Tom wears long sleeves when working in the garden." },
      { id: 6731346, text: "Tom rolled up his sleeves and started working." },
    ],
  },
  {
    word: "loop",
    sentences: [
      { id: 8616235, text: "The music is being played in an endless loop." },
      { id: 10206221, text: "The music played in a loop." },
    ],
  },
  {
    word: "greedy",
    sentences: [
      { id: 3144238, text: "Do not get greedy and eat too much.", changed: true },
      { id: 3824320, text: "Why are people so greedy?" },
      { id: 13065368, text: "A greedy person is not happy poor or rich.", changed: true },
    ],
  },
  {
    word: "pound",
    sentences: [
      { id: 33066, text: "A pound is a unit of weight." },
      { id: 253690, text: "I bought a pound of meat the other day." },
      { id: 61941, text: "Fish is sold by the pound here." },
    ],
  },
  {
    word: "cushion",
    sentences: [
      { id: 7027409, text: "Tom placed a cushion on the floor and sat on it." },
      { id: 10996446, text: "The cushion was soft and inviting." },
      { id: 11523176, text: "The benches are hard, so I always bring a cushion." },
    ],
  },
  {
    word: "wishes",
    sentences: [
      { id: 13216223, text: "Our family sends our best wishes to you and yours." },
      { id: 942476, text: "Send my best wishes to your family." },
      { id: 3776362, text: "Thank you all for the good wishes!" },
    ],
  },
  {
    word: "tape",
    sentences: [
      { id: 3573808, text: "Do you have a tape measure I could borrow?" },
      { id: 11394515, text: "Please tape the boxes closed before sending them this way." },
      { id: 11692577, text: "I need to buy a roll of double-sided tape." },
    ],
  },
  {
    word: "wobbly",
    sentences: [
      { id: 9665092, text: "I tried sitting on that chair, but it was wobbly." },
      { id: 1021951, text: "Why is the table so wobbly?" },
      { id: 267761, text: "All I did was run a little and now my knees are wobbly." },
    ],
  },
  {
    word: "delicate",
    sentences: [
      { id: 48813, text: "The machine is so delicate that it easily breaks." },
      { id: 9693231, text: "Dogs have a delicate sense of smell." },
      { id: 4134203, text: "Can I ask you a delicate question?" },
    ],
  },
  {
    word: "depths",
    sentences: [
      { id: 2725830, text: "The submarine hid in the depths of the ocean." },
      { id: 12774926, text: "They explored the ocean depths." },
      { id: 10540371, text: "In the depths of winter, a hot-water bottle is essential." },
    ],
  },
  {
    word: "blink",
    sentences: [
      { id: 12772613, text: "Everything changed in the blink of an eye." },
      { id: 950918, text: "How many times a minute does the average person blink?" },
      { id: 318080, text: "The plane went out of sight in a blink." },
    ],
  },
  {
    word: "bedtime",
    sentences: [
      { id: 2542215, text: "Tom read Mary a bedtime story." },
      { id: 3202592, text: "Tom told his children a bedtime story." },
      { id: 9859433, text: "Do not eat right before bedtime.", changed: true },
    ],
  },
  {
    word: "tour",
    sentences: [
      { id: 12887774, text: "We went on a world tour." },
      { id: 7542518, text: "Tom gave us a quick tour of his house." },
      { id: 14015421, text: "The guided tour through the capital was wonderful!" },
    ],
  },
  {
    word: "photos",
    sentences: [
      { id: 954704, text: "Would you like to see some photos of my trip?" },
      { id: 11363184, text: "I like to take photos with my new camera." },
      { id: 1230769, text: "My younger brother really likes to take photos of mountains." },
    ],
  },
  {
    word: "breaths",
    sentences: [
      { id: 9371595, text: "I took a few deep breaths." },
      { id: 11889829, text: "Take deep breaths and focus on your breathing." },
      { id: 10144421, text: "We held our breaths and waited." },
    ],
  },
  {
    word: "mixture",
    sentences: [
      { id: 18239, text: "Air is a mixture of various gases." },
      { id: 11620620, text: "Add a small amount of cream to the mixture." },
      { id: 9867958, text: "A mixture of snow and rain was falling from the sky." },
    ],
  },
  {
    word: "skill",
    sentences: [
      { id: 12784750, text: "What is a skill you would like to learn?", changed: true },
      { id: 10372243, text: "Good writing is a skill that most people do not have." },
      { id: 11892784, text: "Cleaning up your room is a valuable life skill you should develop." },
    ],
  },
  {
    word: "tidy",
    sentences: [
      { id: 57294, text: "I want you to have this room clean and tidy." },
      { id: 264783, text: "I always keep my room as tidy as I can." },
      { id: 11886166, text: "Please make sure you tidy up your room before you go out to play." },
    ],
  },
  {
    word: "bald",
    sentences: [
      { id: 8507135, text: "Tom still has hair, but his brother is completely bald." },
      { id: 280134, text: "I have a round bald spot on my head." },
      { id: 1177623, text: "Tom has a bald spot." },
    ],
  },
  {
    word: "moustache",
    sentences: [
      { id: 11940073, text: "Why do you want to grow a moustache?" },
      { id: 6997099, text: "Tom has a large moustache." },
      { id: 11894931, text: "Tom has grown a moustache." },
    ],
  },
  {
    word: "talks",
    sentences: [
      { id: 11306521, text: "When he talks to people, they keep quiet and listen." },
      { id: 8091431, text: "Tom talks to Mary every night on the phone." },
      { id: 237966, text: "The management has agreed to have talks with the workers." },
    ],
  },
  {
    word: "shimmering",
    sentences: [
      { id: 12723659, text: "Stars were shimmering like gems in the night sky." },
    ],
  },
  {
    word: "crumbs",
    sentences: [
      { id: 8902833, text: "The birds ate the bread crumbs." },
      { id: 10098113, text: "There were only crumbs left in the box." },
      { id: 11891624, text: "Be careful not to leave crumbs on the table." },
    ],
  },
  {
    word: "trace",
    sentences: [
      { id: 4945644, text: "The ship disappeared without a trace." },
      { id: 11513856, text: "How far back can you trace your family tree?" },
      { id: 11317181, text: "I saw no trace of a smile." },
    ],
  },
  {
    word: "gust",
    sentences: [
      { id: 11699954, text: "A strong gust of wind tipped my boat over." },
      { id: 12106445, text: "A gust of wind swept through the air." },
      { id: 280665, text: "The gust of wind rose suddenly." },
    ],
  },
  {
    word: "rustling",
    sentences: [
      { id: 13247219, text: "I listened to the rustling of the leaves." },
      { id: 10113367, text: "The leaves on the tree are rustling in the wind." },
      { id: 8855711, text: "The autumn wind is rustling the trees." },
    ],
  },
  {
    word: "sons",
    sentences: [
      { id: 6254264, text: "Tom had three sons and one daughter." },
      { id: 919038, text: "We have got two daughters and two sons." },
      { id: 2243, text: "Generally, who visits their parents more, sons or daughters?" },
    ],
  },
  {
    word: "grasp",
    sentences: [
      { id: 12845107, text: "Tom has a very good grasp of English grammar." },
      { id: 23195, text: "We fail to grasp the meaning of the word." },
      { id: 2954706, text: "You seem to have a really good grasp on this." },
    ],
  },
  {
    word: "victory",
    sentences: [
      { id: 1292996, text: "Our team returned home after a huge victory." },
      { id: 247404, text: "Our team gained a great victory." },
      { id: 291847, text: "He won a narrow victory in the race." },
    ],
  },
  {
    word: "towers",
    sentences: [
      { id: 8549836, text: "Giraffes live in groups called towers." },
      { id: 289752, text: "He towers above the rest of the class." },
    ],
  },
  {
    word: "female",
    sentences: [
      { id: 13699810, text: "I have a male and a female cat." },
      { id: 8212278, text: "A school has male and female students." },
      { id: 68424, text: "Is that dog male or female?" },
    ],
  },
  {
    word: "capable",
    sentences: [
      { id: 270197, text: "Only human beings are capable of speech." },
      { id: 1093448, text: "Tom is perfectly capable of taking care of himself." },
      { id: 1441377, text: "Babies are not capable of looking after themselves." },
    ],
  },
  {
    word: "imaginary",
    sentences: [
      { id: 9732805, text: "I had an imaginary friend when I was a kid." },
      { id: 13714172, text: "The child was talking to his imaginary friend." },
      { id: 2633368, text: "Tom lives in an imaginary world." },
    ],
  },
  {
    word: "accent",
    sentences: [
      { id: 2575664, text: "Tom speaks English with a French accent." },
      { id: 10251004, text: "Do you speak with an accent?" },
      { id: 2971716, text: "Tom speaks beautiful French, without any accent." },
    ],
  },
  {
    word: "glare",
    sentences: [
      { id: 396092, text: "The sudden glare hurt his eyes." },
      { id: 3723114, text: "Tom gave Mary an icy glare." },
    ],
  },
  {
    word: "activity",
    sentences: [
      { id: 11746344, text: "Fishing can be a fun family activity." },
      { id: 11591081, text: "Physical activity is necessary for good health." },
      { id: 12984964, text: "I often choose reading as a leisure activity." },
    ],
  },
  {
    word: "thread",
    sentences: [
      { id: 9688861, text: "Tie the pieces with a thread." },
      { id: 7996469, text: "The thread is thin and breaks easily." },
      { id: 13406283, text: "She holds the end of the thread while I cut." },
    ],
  },
  {
    word: "reality",
    sentences: [
      { id: 10326018, text: "How can we change this dream into reality?" },
      { id: 10267548, text: "One day, my dreams will become a reality." },
      { id: 11610041, text: "Our dream has finally become a reality." },
    ],
  },
  {
    word: "cotton",
    sentences: [
      { id: 3258511, text: "I like cotton clothing in the summer." },
      { id: 10758782, text: "The shirt is made of cotton." },
      { id: 13798052, text: "This bath towel made of cotton is very soft." },
    ],
  },
  {
    word: "shriek",
    sentences: [
      { id: 13828501, text: "The shriek of the pig is so loud." },
      { id: 13616422, text: "I heard a sudden shriek." },
      { id: 3660199, text: "The woman let out such a loud shriek that the house shook." },
    ],
  },
  {
    word: "miniature",
    sentences: [
      { id: 9755746, text: "Have you ever played miniature golf?" },
      { id: 1008894, text: "He stared at that detailed miniature model of a dinosaur." },
      { id: 5708278, text: "I really enjoy playing miniature golf." },
    ],
  },
  {
    word: "deserted",
    sentences: [
      { id: 3222726, text: "The island was completely deserted." },
      { id: 11241374, text: "The top of the hill was completely deserted." },
      { id: 12911703, text: "I ran down the deserted road." },
    ],
  },
  {
    word: "smelly",
    sentences: [
      { id: 8549673, text: "All the towels are wet and smelly." },
      { id: 8529737, text: "This towel is smelly." },
      { id: 10822868, text: "Cats are not smelly animals.", changed: true },
    ],
  },
  {
    word: "frantic",
    sentences: [
      { id: 2629808, text: "My cat became frantic as soon as the car began to move." },
      { id: 1024498, text: "Tom made a frantic attempt to finish painting the fence before dark." },
      { id: 7113617, text: "Why are you so frantic?" },
    ],
  },
  {
    word: "central",
    sentences: [
      { id: 747555, text: "Is the central heating warm enough in the winter?" },
      { id: 8824389, text: "There is no central heating in this house." },
      { id: 277524, text: "The central location gives easy access to stores and offices." },
    ],
  },
  {
    word: "bundle",
    sentences: [
      { id: 12651240, text: "I carried a bundle of wood on my back." },
      { id: 1078852, text: "He tied the small branches into a bundle." },
      { id: 322067, text: "The books were tied up in a bundle." },
    ],
  },
  {
    word: "role",
    sentences: [
      { id: 12337029, text: "The older sister played the role of the mother." },
      { id: 51624, text: "Sports play an important role in social life." },
      { id: 9409745, text: "We all have a role to play." },
    ],
  },
  {
    word: "spirits",
    sentences: [
      { id: 46571, text: "Our team was in high spirits because of the victory." },
      { id: 273560, text: "The players were in high spirits after the game." },
      { id: 5742524, text: "Tom seemed in good spirits." },
    ],
  },
  {
    word: "possibility",
    sentences: [
      { id: 2640444, text: "Tom considered the possibility of not going." },
      { id: 7221880, text: "Is there any possibility Tom will be early?" },
      { id: 2841096, text: "There is the possibility of what he said being true." },
    ],
  },
  {
    word: "pets",
    sentences: [
      { id: 680202, text: "Which animals make the best pets for children?" },
      { id: 24117, text: "Before you leave home, make sure your pets have enough food." },
      { id: 12917111, text: "My pets just sleep every day." },
    ],
  },
  {
    word: "floors",
    sentences: [
      { id: 60601, text: "How many floors does this building have?" },
      { id: 1390300, text: "The house has three floors." },
      { id: 682475, text: "All the floors in her house are made of wood." },
    ],
  },
  {
    word: "worms",
    sentences: [
      { id: 10721042, text: "The bird is looking for worms." },
      { id: 320946, text: "The mother bird brought worms for her young ones." },
      { id: 1885883, text: "How many worms did you find?" },
    ],
  },
  {
    word: "ease",
    sentences: [
      { id: 41177, text: "People feel most at ease when they are at home." },
      { id: 3467803, text: "I feel at ease around Tom." },
      { id: 52499, text: "I can never feel at ease among strangers." },
    ],
  },
  {
    word: "heroes",
    sentences: [
      { id: 9805702, text: "Who are your heroes?" },
      { id: 5261248, text: "Tom is one of my heroes." },
      { id: 2713515, text: "You guys are my heroes." },
    ],
  },
  {
    word: "blankets",
    sentences: [
      { id: 4447561, text: "In the winter, I sleep under two blankets." },
      { id: 2266864, text: "How many blankets are there on the bed?" },
      { id: 11880025, text: "I wrapped myself in the warm blankets on the bed." },
    ],
  },
  {
    word: "bells",
    sentences: [
      { id: 2672656, text: "The bells started to ring." },
      { id: 13636291, text: "Did you hear the bells ring?" },
      { id: 10726070, text: "I hear the bells ringing." },
    ],
  },
  {
    word: "candles",
    sentences: [
      { id: 11879383, text: "Can you light the candles on the cake?" },
      { id: 10541515, text: "How many candles are we lighting tonight?" },
      { id: 11390353, text: "I lit the candles in my bedroom." },
    ],
  },
  {
    word: "sandy",
    sentences: [
      { id: 11296772, text: "The white sandy beach is very beautiful." },
      { id: 789928, text: "Several children are playing on the sandy beach." },
      { id: 11893040, text: "Do you prefer sandy or rocky beaches?" },
    ],
  },
  {
    word: "fires",
    sentences: [
      { id: 13895345, text: "We use matches to light fires." },
      { id: 279641, text: "We often have fires in winter." },
      { id: 5609034, text: "The local population helps fight forest fires." },
    ],
  },
  {
    word: "trunks",
    sentences: [
      { id: 2722375, text: "Elephants have long trunks." },
      { id: 11066198, text: "Is that a new pair of swimming trunks?" },
      { id: 11232132, text: "The tree trunks started to rock back and forth." },
    ],
  },
  {
    word: "ribbon",
    sentences: [
      { id: 46633, text: "The girl wore a yellow ribbon in her hair." },
      { id: 9220218, text: "Tom wrapped the package and tied it with a ribbon." },
      { id: 44557, text: "The cat had a ribbon around its neck." },
    ],
  },
  {
    word: "sixth",
    sentences: [
      { id: 4195453, text: "We live on the sixth floor." },
      { id: 12022820, text: "What day of the week is the sixth?" },
      { id: 3949362, text: "Do you believe that women have a sixth sense?" },
    ],
  },
  {
    word: "credit",
    sentences: [
      { id: 2238, text: "Can I pay by credit card?" },
      { id: 434376, text: "Can I pay with a credit card?" },
      { id: 502363, text: "Most of the credit for our success goes to you." },
    ],
  },
  {
    word: "remarkable",
    sentences: [
      { id: 12867876, text: "Dogs have a remarkable sense of smell." },
      { id: 3573356, text: "What a remarkable achievement!" },
      { id: 10085504, text: "Mary is a remarkable young lady." },
    ],
  },
  {
    word: "drivers",
    sentences: [
      { id: 7736240, text: "How much money do taxi drivers make?" },
      { id: 1177063, text: "All drivers should obey the rules of the road." },
      { id: 8438410, text: "Bus drivers are responsible for cleaning the buses they drive." },
    ],
  },
  {
    word: "landscape",
    sentences: [
      { id: 12607132, text: "The landscape was white with snow." },
      { id: 13775040, text: "The painter painted an amazing landscape." },
      { id: 259182, text: "I gazed out of the window at the landscape." },
    ],
  },
  {
    word: "dozens",
    sentences: [
      { id: 4179693, text: "There are dozens of trees in the garden." },
      { id: 256435, text: "I went there dozens of times." },
      { id: 8819553, text: "There are dozens of letters waiting for you." },
    ],
  },
  {
    word: "pigs",
    sentences: [
      { id: 9669011, text: "I fed the pigs and the chickens." },
      { id: 11998073, text: "Are pigs smarter than dogs?" },
      { id: 12062956, text: "All the apples that fell were eaten by the pigs." },
    ],
  },
  {
    word: "secure",
    sentences: [
      { id: 11886368, text: "You need to keep the keys in a secure place." },
      { id: 681362, text: "Children need limits in order to feel secure." },
      { id: 11889643, text: "Keep your personal belongings secure." },
    ],
  },
  {
    word: "cheers",
    sentences: [
      { id: 49477, text: "The speech was greeted by loud cheers." },
      { id: 237770, text: "The crowds broke into loud cheers." },
      { id: 12106102, text: "Chocolate always cheers me up." },
    ],
  },
  {
    word: "thrilled",
    sentences: [
      { id: 1877585, text: "Tom will be thrilled to see you." },
      { id: 11165283, text: "I was really thrilled to have met you." },
      { id: 8155014, text: "We are thrilled to have you on the team.", changed: true },
    ],
  },
  {
    word: "velvet",
    sentences: [
      { id: 6029627, text: "If you pick up the velvet, you can feel how soft it is." },
      { id: 6029166, text: "The dress was covered with blue velvet." },
      { id: 7927288, text: "I got the wedding rings in a velvet box." },
    ],
  },
  {
    word: "banana",
    sentences: [
      { id: 13667810, text: "The monkey drank water after eating a banana." },
      { id: 9505438, text: "All Tom had for breakfast was a banana and some milk." },
      { id: 2154638, text: "Is his aunt eating an apple or a banana?" },
    ],
  },
  {
    word: "limbs",
    sentences: [
      { id: 302936, text: "He rested his tired limbs." },
      { id: 323582, text: "Branches are to trees what limbs are to us." },
      { id: 2841370, text: "He ran as fast as his limbs could carry him." },
    ],
  },
  {
    word: "sensitive",
    sentences: [
      { id: 2348952, text: "My eyes are very sensitive to light." },
      { id: 323762, text: "The eye is sensitive to light." },
      { id: 326047, text: "My teeth are sensitive to cold foods." },
    ],
  },
  {
    word: "gulp",
    sentences: [
      { id: 10684216, text: "Tom took a gulp of water." },
      { id: 2051744, text: "The girl drank down the milk in one gulp." },
      { id: 3315192, text: "Tom took a big gulp of his drink." },
    ],
  },
  {
    word: "quarters",
    sentences: [
      { id: 47676, text: "Three-quarters of the work was finished." },
      { id: 11964732, text: "The glass is about three quarters full." },
      { id: 305101, text: "Three quarters of them agreed." },
    ],
  },
  {
    word: "shirts",
    sentences: [
      { id: 1495751, text: "Why do you always wear white shirts?" },
      { id: 3258410, text: "In the summer, I wear cotton shirts." },
      { id: 11676427, text: "The students put their school shirts on." },
    ],
  },
  {
    word: "colourful",
    sentences: [
      { id: 2494340, text: "The flowers were bright and colourful." },
      { id: 11159570, text: "The girls wear colourful dresses." },
      { id: 14029220, text: "There are colourful leaves on that tree." },
    ],
  },
  {
    word: "underwater",
    sentences: [
      { id: 1095247, text: "Tom closes his eyes when he swims underwater." },
      { id: 9733116, text: "How far can you swim underwater?" },
      { id: 11578408, text: "Do you have an underwater camera?" },
    ],
  },
  {
    word: "lifetime",
    sentences: [
      { id: 8515211, text: "Things like this only happen once in a lifetime." },
      { id: 6040114, text: "Tom wrote over thirty books in his lifetime." },
      { id: 3756524, text: "I got the chance of a lifetime, and I took it." },
    ],
  },
  {
    word: "messages",
    sentences: [
      { id: 8085641, text: "You can send private messages to other members." },
      { id: 12199706, text: "Have you checked your text messages?" },
      { id: 6234135, text: "Tom and I send each other text messages quite often." },
    ],
  },
  {
    word: "palms",
    sentences: [
      { id: 11716975, text: "Tom looked at the palms of his hands." },
      { id: 10901627, text: "Let me see the palms of your hands." },
      { id: 2097, text: "I can place the palms of my hands on the floor without bending my knees." },
    ],
  },
  {
    word: "wires",
    sentences: [
      { id: 45273, text: "The man connected two wires." },
      { id: 10076663, text: "Be careful not to trip over the wires." },
      { id: 9967099, text: "The wires are attached to the light switch." },
    ],
  },
  {
    word: "outline",
    sentences: [
      { id: 12395998, text: "The artist carefully sketched the outline of the portrait." },
      { id: 3171488, text: "Tom gave Mary a brief outline of his plan." },
      { id: 5742042, text: "Here is a general outline." },
    ],
  },
  {
    word: "bites",
    sentences: [
      { id: 6392437, text: "Be careful! My dog bites!" },
      { id: 2889431, text: "We have four rabbits, and one of them bites." },
      { id: 12675471, text: "He ate a few bites and stood up." },
    ],
  },
]
