// SPDX-License-Identifier: CC-BY-2.0-FR
//
// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).
// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>
//
// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.
// "changed: true" means that we expanded a contraction, for example "don't" to "do not".
// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.

import type { TatoebaEntry } from '../bank'

export const TATOEBA_0006_BANK: readonly TatoebaEntry[] = [
  {
    word: "grown",
    sentences: [
      { id: 10950963, text: "Our little girl has grown up." },
      { id: 2711657, text: "Your son is quite grown up now." },
      { id: 10527208, text: "Tom only eats locally-grown vegetables." },
    ],
  },
  {
    word: "heel",
    sentences: [
      { id: 6844437, text: "The heel of her shoe broke." },
      { id: 11864528, text: "The heel is missing on my left shoe." },
      { id: 413835, text: "My black shoes need heel repairs." },
    ],
  },
  {
    word: "heal",
    sentences: [
      { id: 682492, text: "In older people, wounds take a long time to heal." },
      { id: 12770968, text: "With time, all wounds heal." },
      { id: 11487628, text: "All wounds are said to heal with time." },
    ],
  },
  {
    word: "knot",
    sentences: [
      { id: 9149293, text: "Do you know how to tie a knot?" },
      { id: 10472009, text: "Could you teach me how to tie a square knot?" },
      { id: 7364434, text: "Tom loosened the knot on his tie." },
    ],
  },
  {
    word: "mail",
    sentences: [
      { id: 992953, text: "I got a book in the mail today." },
      { id: 323172, text: "Remember to mail this letter tomorrow morning." },
      { id: 13125037, text: "I received a thoughtful letter in the mail." },
    ],
  },
  {
    word: "male",
    sentences: [
      { id: 270109, text: "A person is either male or female." },
      { id: 68424, text: "Is that dog male or female?" },
      { id: 2771505, text: "Is that bird male or female?" },
    ],
  },
  {
    word: "main",
    sentences: [
      { id: 706871, text: "There are two main characters in this story." },
      { id: 1114845, text: "What is the main attraction of the museum?" },
      { id: 13595256, text: "The main thing is not to be late." },
    ],
  },
  {
    word: "mane",
    sentences: [
      { id: 6122981, text: "Horses have a mane and a thick, long tail." },
      { id: 12629336, text: "The man bought a horse with a very nice mane." },
    ],
  },
  {
    word: "medal",
    sentences: [
      { id: 3058823, text: "Who do you think will win the gold medal?" },
      { id: 7924064, text: "I won my first gold medal." },
      { id: 13992111, text: "Runners-up receive a silver medal." },
    ],
  },
  {
    word: "meddle",
    sentences: [
      { id: 285025, text: "Do not meddle in his affairs.", changed: true },
      { id: 11668471, text: "I did not meddle with their family affairs.", changed: true },
      { id: 11727418, text: "Who gives you the right to meddle in the lives of others?" },
    ],
  },
  {
    word: "missed",
    sentences: [
      { id: 259434, text: "I arrived too late and missed the train." },
      { id: 13520870, text: "We arrived a minute late because we missed the bus." },
      { id: 33035, text: "I missed the train by only one minute." },
    ],
  },
  {
    word: "mist",
    sentences: [
      { id: 11565752, text: "The mountains are now covered in mist." },
      { id: 322862, text: "A boat suddenly appeared out of the mist." },
      { id: 13483370, text: "There was mist over the river." },
    ],
  },
  {
    word: "peace",
    sentences: [
      { id: 13998347, text: "When will this world be able to live in peace?" },
      { id: 6069126, text: "Tom says he just wants some peace and quiet." },
      { id: 241699, text: "I feel at peace with myself now." },
    ],
  },
  {
    word: "piece",
    sentences: [
      { id: 385439, text: "Can I offer you another piece of cake?" },
      { id: 511477, text: "Please give me a piece of paper to write on." },
      { id: 6265242, text: "Do you want a piece of cake?" },
    ],
  },
  {
    word: "seen",
    sentences: [
      { id: 1835173, text: "Have you already seen the film?" },
      { id: 2641044, text: "Have you ever seen a bear in this area?" },
      { id: 2792974, text: "Have you seen the new film?" },
    ],
  },
  {
    word: "whether",
    sentences: [
      { id: 247755, text: "We must go there whether we like it or not." },
      { id: 241088, text: "The question whether we should go or stay comes next." },
      { id: 3630515, text: "I have no idea whether or not Tom will come." },
    ],
  },
  {
    word: "whose",
    sentences: [
      { id: 9949440, text: "I have a friend whose father is a doctor." },
      { id: 6529302, text: "I met a man whose brother knows you." },
      { id: 8353846, text: "I know three boys whose fathers are doctors." },
    ],
  },
  {
    word: "precious",
    sentences: [
      { id: 13558201, text: "Freedom is more precious than silver or gold." },
      { id: 477701, text: "Our health is our most precious possession." },
      { id: 263981, text: "Time is the most precious thing of all." },
    ],
  },
  {
    word: "delicious",
    sentences: [
      { id: 1716451, text: "Thank you for baking this delicious cake." },
      { id: 10100049, text: "The ice cream that I ate yesterday was delicious." },
      { id: 13857757, text: "Thank you for this delicious meal!" },
    ],
  },
  {
    word: "suspicious",
    sentences: [
      { id: 6700109, text: "Have you noticed anything suspicious recently?" },
      { id: 318639, text: "If you see a suspicious person, please inform the police." },
      { id: 13565291, text: "If you see anything suspicious, please contact us." },
    ],
  },
  {
    word: "ambitious",
    sentences: [
      { id: 5610161, text: "Tom is an ambitious young man." },
      { id: 4985285, text: "I think your plan is too ambitious." },
      { id: 687327, text: "I am very positive and ambitious for my goals." },
    ],
  },
  {
    word: "cautious",
    sentences: [
      { id: 11886895, text: "Be cautious when walking on the slippery rocks." },
      { id: 11886741, text: "Be cautious around the fire, it can cause accidents." },
      { id: 11891640, text: "Be cautious when crossing the river, it can be slippery." },
    ],
  },
  {
    word: "fictitious",
    sentences: [
      { id: 60788, text: "All the characters in this drama are fictitious." },
      { id: 8940507, text: "The events described in this story are purely fictitious." },
      { id: 12589618, text: "I provided him with a fictitious name." },
    ],
  },
  {
    word: "infectious",
    sentences: [
      { id: 4187588, text: "You have an infectious disease." },
      { id: 13087501, text: "Her illness is infectious." },
      { id: 13102993, text: "His laughter is infectious." },
    ],
  },
  {
    word: "nutritious",
    sentences: [
      { id: 9358161, text: "Milk is not only tasty, but also nutritious." },
      { id: 26427, text: "You have to eat nutritious foods." },
      { id: 1300109, text: "I ate a nutritious breakfast." },
    ],
  },
  {
    word: "official",
    sentences: [
      { id: 11887274, text: "What is the official language of your country?" },
      { id: 10729274, text: "The official language of the country is French." },
      { id: 11020235, text: "An official statement was released yesterday." },
    ],
  },
  {
    word: "artificial",
    sentences: [
      { id: 13336916, text: "After the accident, he learned to walk again with an artificial leg." },
      { id: 6533486, text: "How does artificial intelligence work?" },
      { id: 5780398, text: "Will artificial intelligence be able to replace people?" },
    ],
  },
  {
    word: "partial",
    sentences: [
      { id: 46884, text: "The play was only a partial success." },
      { id: 11592669, text: "This is a partial list of the things we need." },
      { id: 2796750, text: "I can only afford to make a partial payment." },
    ],
  },
  {
    word: "confidential",
    sentences: [
      { id: 13572495, text: "Please keep this information confidential." },
      { id: 13550045, text: "This is a confidential document. Please do not share it with anyone." },
      { id: 4497234, text: "The details are confidential." },
    ],
  },
  {
    word: "essential",
    sentences: [
      { id: 11150784, text: "Water is essential to our life." },
      { id: 11591083, text: "Exercise is essential for maintaining good health." },
      { id: 279474, text: "Hard work is an essential element of success." },
    ],
  },
  {
    word: "observant",
    sentences: [
      { id: 9479762, text: "Tom is an observant person." },
      { id: 3325420, text: "Tom is usually quite observant." },
      { id: 6228033, text: "I know that Tom is observant." },
    ],
  },
  {
    word: "observation",
    sentences: [
      { id: 277656, text: "A careful observation will show you the difference." },
      { id: 11737914, text: "Science requires careful observation and analysis." },
      { id: 11726780, text: "May I make a personal observation?" },
    ],
  },
  {
    word: "expectation",
    sentences: [
      { id: 11468104, text: "He had no expectation of winning." },
      { id: 238613, text: "The result fell short of his expectation." },
      { id: 20511, text: "We were filled with joyful expectation." },
    ],
  },
  {
    word: "hesitant",
    sentences: [
      { id: 2952749, text: "I am a little hesitant to go there by myself.", changed: true },
    ],
  },
  {
    word: "tolerant",
    sentences: [
      { id: 12283281, text: "Always try to be tolerant and patient." },
      { id: 6261068, text: "Tom told Mary that she should be more tolerant." },
      { id: 3728523, text: "We really have to be more tolerant." },
    ],
  },
  {
    word: "tolerance",
    sentences: [
      { id: 11390965, text: "True tolerance is when we agree to disagree." },
      { id: 5236077, text: "Peace cannot exist without tolerance and respect for diversity." },
      { id: 12231202, text: "To some people, tolerance is another word for weakness." },
    ],
  },
  {
    word: "substance",
    sentences: [
      { id: 5325785, text: "Air is a physical substance which has weight." },
      { id: 11979944, text: "The result of the experiment was a blue substance." },
    ],
  },
  {
    word: "substantial",
    sentences: [
      { id: 12236171, text: "There is a substantial difference!" },
      { id: 5726226, text: "The differences were substantial." },
      { id: 4496196, text: "Many buildings sustained substantial damage." },
    ],
  },
  {
    word: "innocent",
    sentences: [
      { id: 5702017, text: "Tom knew that Mary was innocent." },
      { id: 9542784, text: "No one believes that she is innocent." },
      { id: 8414478, text: "There might be a perfectly innocent explanation." },
    ],
  },
  {
    word: "innocence",
    sentences: [
      { id: 7274348, text: "How can I prove my innocence?" },
      { id: 248349, text: "We are all convinced of his innocence." },
      { id: 28939, text: "I have a firm belief in his innocence." },
    ],
  },
  {
    word: "decent",
    sentences: [
      { id: 11685098, text: "When was the last time you ate a decent meal?" },
      { id: 70005, text: "You had better go there in decent clothes." },
      { id: 1553355, text: "Tom seems like a decent kid." },
    ],
  },
  {
    word: "decency",
    sentences: [
      { id: 9200053, text: "At least he had the decency to apologise." },
      { id: 10678836, text: "Tom had the decency to admit that it was his fault." },
      { id: 6730670, text: "Have you no decency?" },
    ],
  },
  {
    word: "frequent",
    sentences: [
      { id: 12194683, text: "Traffic accidents are very frequent here." },
      { id: 1597396, text: "His visits became less frequent as time passed." },
      { id: 3295317, text: "Tom is a frequent guest on the show." },
    ],
  },
  {
    word: "frequency",
    sentences: [
      { id: 35254, text: "Bus service must be increased in frequency." },
    ],
  },
  {
    word: "confident",
    sentences: [
      { id: 11698741, text: "You should be more confident in yourself." },
      { id: 7136863, text: "We feel pretty confident that we can win." },
      { id: 12419545, text: "We were confident that we would win the game." },
    ],
  },
  {
    word: "confidence",
    sentences: [
      { id: 252882, text: "I have confidence in your ability to win." },
      { id: 1962004, text: "I have a lot of confidence in you." },
      { id: 3726945, text: "I have full confidence in your abilities." },
    ],
  },
  {
    word: "assistant",
    sentences: [
      { id: 8417280, text: "My sister is working as a shop assistant now." },
      { id: 2276353, text: "Tom is a teaching assistant." },
      { id: 249315, text: "We employed her as an assistant." },
    ],
  },
  {
    word: "assistance",
    sentences: [
      { id: 70557, text: "Can I be of any assistance to you?" },
      { id: 11698877, text: "Do you need any assistance with that?" },
      { id: 2644137, text: "Do you need our assistance?" },
    ],
  },
  {
    word: "obedient",
    sentences: [
      { id: 13033279, text: "You have to be obedient to your parents." },
      { id: 12583960, text: "Children should always be obedient." },
      { id: 12349064, text: "I was an obedient child." },
    ],
  },
  {
    word: "obedience",
    sentences: [
      { id: 23266, text: "We should always act in obedience to the law." },
    ],
  },
  {
    word: "independent",
    sentences: [
      { id: 2992382, text: "Mary is a strong, independent woman." },
      { id: 52635, text: "John wanted to be completely independent of his family." },
      { id: 10856290, text: "Do you want to become financially independent?" },
    ],
  },
  {
    word: "independence",
    sentences: [
      { id: 1355900, text: "The people of the United States fought for their independence." },
      { id: 681545, text: "The nation recently declared its independence." },
      { id: 12170112, text: "How can I achieve true financial independence?" },
    ],
  },
  {
    word: "applicable",
    sentences: [
      { id: 57142, text: "This law is applicable to all cases." },
      { id: 10794710, text: "This rule is not always applicable." },
      { id: 48786, text: "Is that rule applicable to us foreigners?" },
    ],
  },
  {
    word: "application",
    sentences: [
      { id: 58338, text: "Please fill in this application form." },
      { id: 680812, text: "To be employed, you must fill out an application." },
      { id: 13195765, text: "What application do you use for drawing?" },
    ],
  },
  {
    word: "considerable",
    sentences: [
      { id: 10345141, text: "A considerable sum of money was spent on the new bridge." },
      { id: 13699384, text: "The storm did considerable damage to the field crops." },
      { id: 2623373, text: "The city has changed a considerable amount in the last two years." },
    ],
  },
  {
    word: "considerably",
    sentences: [
      { id: 1580295, text: "Your English has improved considerably." },
      { id: 9128396, text: "The weather improved considerably during the course of the day." },
      { id: 9189980, text: "Traffic has gone down considerably." },
    ],
  },
  {
    word: "consideration",
    sentences: [
      { id: 11554973, text: "We need to take that fact into consideration." },
      { id: 2485840, text: "You should take into consideration the advice of your mother." },
      { id: 247973, text: "We have to take this problem into consideration." },
    ],
  },
  {
    word: "changeable",
    sentences: [
      { id: 61926, text: "The weather is changeable here." },
      { id: 245089, text: "The weather is more changeable in mountain regions than in any other district." },
      { id: 8735121, text: "The weather is very changeable here." },
    ],
  },
  {
    word: "noticeable",
    sentences: [
      { id: 325629, text: "There are noticeable differences between the two." },
      { id: 13379251, text: "The difference is very noticeable." },
      { id: 10018064, text: "Is there a noticeable difference?" },
    ],
  },
  {
    word: "legible",
    sentences: [
      { id: 12871062, text: "Your letter was barely legible." },
    ],
  },
  {
    word: "dependable",
    sentences: [
      { id: 5937026, text: "Tom is very dependable and reliable." },
      { id: 7515885, text: "I know that Tom is a dependable person." },
      { id: 6343678, text: "Do you think Tom is still dependable?" },
    ],
  },
  {
    word: "comfortable",
    sentences: [
      { id: 2138636, text: "Sit down and make yourself comfortable!" },
      { id: 13664318, text: "How comfortable is it to sit in?" },
      { id: 2326023, text: "I feel very comfortable with you." },
    ],
  },
  {
    word: "understandable",
    sentences: [
      { id: 1528903, text: "Can you phrase your answer in an understandable manner?" },
      { id: 13794489, text: "The longer the sentences, the less understandable they are." },
      { id: 8269297, text: "I hope what I wrote was understandable." },
    ],
  },
  {
    word: "reasonable",
    sentences: [
      { id: 8861820, text: "I think that the price is reasonable." },
      { id: 832079, text: "I sold my books at a reasonable price." },
      { id: 11886786, text: "Keep the volume at a reasonable level, please." },
    ],
  },
  {
    word: "enjoyable",
    sentences: [
      { id: 12434883, text: "Did you have an enjoyable evening?" },
      { id: 794672, text: "Learning a foreign language is truly interesting and enjoyable." },
      { id: 11516501, text: "We wish you a very enjoyable weekend!" },
    ],
  },
  {
    word: "reliable",
    sentences: [
      { id: 13960522, text: "A reliable source provides accurate information." },
      { id: 471251, text: "As far as I know, he is a reliable friend." },
      { id: 5849669, text: "How reliable is this information?" },
    ],
  },
  {
    word: "possibly",
    sentences: [
      { id: 528251, text: "Read as many books as you possibly can." },
      { id: 4013578, text: "What could possibly be the reason?" },
      { id: 4016980, text: "How hard could it possibly be?" },
    ],
  },
  {
    word: "horrible",
    sentences: [
      { id: 6533573, text: "I had such a horrible dream last night." },
      { id: 6210007, text: "How can you say such a horrible thing?" },
      { id: 264533, text: "The scene of the traffic accident was a horrible sight." },
    ],
  },
  {
    word: "horribly",
    sentences: [
      { id: 3303684, text: "Everything went horribly wrong for Tom." },
      { id: 5725611, text: "The boys look horribly disappointed." },
      { id: 9935628, text: "My father is horribly choosy about food." },
    ],
  },
  {
    word: "terribly",
    sentences: [
      { id: 1024842, text: "Tom is terribly busy at this time." },
      { id: 6685170, text: "Let us stay inside. Outside it is terribly cold.", changed: true },
      { id: 3302821, text: "I am terribly sorry for being late.", changed: true },
    ],
  },
  {
    word: "visible",
    sentences: [
      { id: 9951482, text: "In summer, many stars are visible in the night sky." },
      { id: 18314, text: "Numerous stars were visible in the sky." },
      { id: 11223264, text: "The trail was barely visible." },
    ],
  },
  {
    word: "visibly",
    sentences: [
      { id: 11178962, text: "The young man was visibly embarrassed." },
      { id: 10652713, text: "He was visibly upset." },
      { id: 12893452, text: "He has aged visibly." },
    ],
  },
  {
    word: "incredible",
    sentences: [
      { id: 3622675, text: "Tom told me an incredible story." },
      { id: 24896, text: "What an incredible amount of work he has done!" },
      { id: 275139, text: "The sun sends out an incredible amount of heat and light." },
    ],
  },
  {
    word: "incredibly",
    sentences: [
      { id: 11787871, text: "English is an incredibly difficult language." },
      { id: 6657762, text: "Tom is an incredibly smart man." },
      { id: 11625165, text: "In the summer, the beach is incredibly busy." },
    ],
  },
  {
    word: "sensible",
    sentences: [
      { id: 320012, text: "A sensible person is one who uses good sense." },
      { id: 11513683, text: "John is a very responsible, brave and sensible boy." },
      { id: 6237552, text: "Doing that would be the sensible thing to do." },
    ],
  },
  {
    word: "sensibly",
    sentences: [
      { id: 11685094, text: "People do not always behave sensibly.", changed: true },
    ],
  },
  {
    word: "referring",
    sentences: [
      { id: 12252054, text: "Which paragraph are you referring to?" },
      { id: 11249947, text: "What is the newspaper referring to?" },
      { id: 11247716, text: "Yes, I am referring to you." },
    ],
  },
  {
    word: "referred",
    sentences: [
      { id: 290095, text: "He is often referred to as a national hero." },
      { id: 46968, text: "The period is referred to as the Stone Age." },
      { id: 241163, text: "The speaker referred to his notes every few minutes." },
    ],
  },
  {
    word: "transferring",
    sentences: [
      { id: 12889307, text: "They are transferring to another school.", changed: true },
      { id: 12903136, text: "He will be transferring schools next week.", changed: true },
      { id: 11920084, text: "Are you transferring to another department?" },
    ],
  },
  {
    word: "transferred",
    sentences: [
      { id: 11498161, text: "A new girl has been transferred to our class." },
      { id: 10751412, text: "Tom got transferred to another department." },
      { id: 12769985, text: "Tom transferred some money to Mary." },
    ],
  },
  {
    word: "reference",
    sentences: [
      { id: 264902, text: "A dictionary is an excellent reference book." },
      { id: 10287627, text: "I want to look at my reference books." },
      { id: 12915802, text: "He made reference to that book." },
    ],
  },
  {
    word: "referee",
    sentences: [
      { id: 9435557, text: "The referee placed the ball on the spot." },
      { id: 9182491, text: "The referee has called a penalty!" },
      { id: 11818447, text: "The referee has awarded a corner kick." },
    ],
  },
  {
    word: "preference",
    sentences: [
      { id: 12646547, text: "What is your preference? Sweet or salty.", changed: true },
      { id: 9838211, text: "What is your personal preference?", changed: true },
      { id: 2645101, text: "Do you have a preference?" },
    ],
  },
  {
    word: "deceive",
    sentences: [
      { id: 5482408, text: "Do you think it is easy to deceive children?" },
      { id: 12438913, text: "Tom tried to deceive us." },
      { id: 914074, text: "I never meant to deceive you." },
    ],
  },
  {
    word: "conceive",
    sentences: [
      { id: 3833203, text: "What the mind can conceive, it can achieve." },
      { id: 24648, text: "I cannot conceive why she has done such a thing." },
      { id: 264550, text: "I cannot conceive how I could have made such a mistake.", changed: true },
    ],
  },
  {
    word: "receive",
    sentences: [
      { id: 10933191, text: "Each child will receive a gift." },
      { id: 5679121, text: "What gift would you like to receive for Christmas?" },
      { id: 2725709, text: "We are very happy to receive a message from you." },
    ],
  },
  {
    word: "perceive",
    sentences: [
      { id: 9370503, text: "Change the way you perceive the world." },
      { id: 13020530, text: "You worry about how others perceive you." },
      { id: 11510590, text: "How do you perceive me?" },
    ],
  },
  {
    word: "ceiling",
    sentences: [
      { id: 11573281, text: "You should paint the ceiling before you paint the floor." },
      { id: 278782, text: "There is a fly on the ceiling." },
      { id: 6258958, text: "Tom hung a light from the ceiling." },
    ],
  },
  {
    word: "ought",
    sentences: [
      { id: 3150745, text: "I really ought to buy a new car." },
      { id: 4015151, text: "Do you think we ought to go in?" },
      { id: 3534186, text: "Maybe you ought to talk to Tom." },
    ],
  },
  {
    word: "bought",
    sentences: [
      { id: 2167929, text: "I bought a watch in that shop." },
      { id: 259048, text: "I bought a new computer last month." },
      { id: 276243, text: "Who bought a book at the shop?" },
    ],
  },
  {
    word: "nought",
    sentences: [
      { id: 987311, text: "I teach kids from nought to five years old." },
    ],
  },
  {
    word: "brought",
    sentences: [
      { id: 11639556, text: "What have you brought with you?" },
      { id: 11952899, text: "Have you brought something with you?" },
      { id: 5472752, text: "Why have you brought the child here?" },
    ],
  },
  {
    word: "fought",
    sentences: [
      { id: 10817944, text: "The two boys fought over who got to use the computer." },
      { id: 267402, text: "We fought hard for victory." },
      { id: 6634527, text: "The girls fought over a boy." },
    ],
  },
  {
    word: "tough",
    sentences: [
      { id: 4626702, text: "Times are tough. Try to be strong!" },
      { id: 13017079, text: "How do you manage when things get tough?" },
      { id: 6222370, text: "Tom will be tough to beat." },
    ],
  },
  {
    word: "dough",
    sentences: [
      { id: 4468469, text: "The baker forgot to put salt in the dough." },
      { id: 270856, text: "Add water and mix to a firm dough." },
      { id: 5357070, text: "Form the dough into a ball." },
    ],
  },
  {
    word: "plough",
    sentences: [
      { id: 12442648, text: "The Great Bear looks like a plough." },
    ],
  },
  {
    word: "bough",
    sentences: [
      { id: 9941264, text: "The bough did not support his weight and broke off.", changed: true },
    ],
  },
  {
    word: "doubt",
    sentences: [
      { id: 42936, text: "There seems no doubt about it." },
      { id: 6245216, text: "I doubt Tom will ever do that again." },
      { id: 3350631, text: "When in doubt, just take the next small step." },
    ],
  },
  {
    word: "lamb",
    sentences: [
      { id: 12573013, text: "A lamb is a young sheep." },
      { id: 12810346, text: "Tom was holding a lamb in his arms." },
      { id: 11169282, text: "A lamb should drink all the milk it wants." },
    ],
  },
  {
    word: "solemn",
    sentences: [
      { id: 12407863, text: "It is the wedding tomorrow. Everything must look very solemn.", changed: true },
    ],
  },
  {
    word: "advice",
    sentences: [
      { id: 3152742, text: "Can I give you a word of advice?" },
      { id: 1027850, text: "Tom turned to Mary for advice." },
      { id: 2360315, text: "I have some advice for you, Tom." },
    ],
  },
  {
    word: "advise",
    sentences: [
      { id: 5201623, text: "Can you advise me on what I should do?" },
      { id: 2406806, text: "I strongly advise you not to do that." },
      { id: 264254, text: "Please advise me of the date for the next meeting." },
    ],
  },
  {
    word: "device",
    sentences: [
      { id: 7323426, text: "How does this device work?" },
      { id: 12608445, text: "To turn the device on, press this button." },
      { id: 410485, text: "The telephone is just a wonderful device." },
    ],
  },
  {
    word: "devise",
    sentences: [
      { id: 12417932, text: "We need to devise a plan." },
      { id: 11662053, text: "Let us devise a new strategy.", changed: true },
      { id: 25054, text: "We must devise some means of escape." },
    ],
  },
  {
    word: "licence",
    sentences: [
      { id: 12046223, text: "Have you still got a driving licence?" },
      { id: 12442676, text: "You are not old enough to get a driving licence.", changed: true },
      { id: 10977120, text: "Did you get your driving licence?" },
    ],
  },
  {
    word: "practice",
    sentences: [
      { id: 6549839, text: "I have band practice after school." },
      { id: 6248906, text: "Tom never missed a game or a practice." },
      { id: 3483055, text: "Tom showed up early for practice today." },
    ],
  },
  {
    word: "practise",
    sentences: [
      { id: 8203317, text: "You should practise your English more." },
      { id: 10121750, text: "You have to practise your reading." },
      { id: 10741456, text: "How many times a week does the football team practise?" },
    ],
  },
  {
    word: "prophecy",
    sentences: [
      { id: 16870, text: "Your prophecy has come true." },
      { id: 4420301, text: "Do you believe in prophecy?" },
      { id: 1792466, text: "The prophecy came true." },
    ],
  },
  {
    word: "farther",
    sentences: [
      { id: 275122, text: "The sun is farther from the earth than the moon." },
      { id: 7555476, text: "The school is farther away than the station." },
      { id: 12119239, text: "How much farther do you have to go?" },
    ],
  },
  {
    word: "further",
    sentences: [
      { id: 2912121, text: "How much further do we have to go?" },
      { id: 2253473, text: "Do you want to study it further?" },
      { id: 3329762, text: "Can we be of any further assistance?" },
    ],
  },
  {
    word: "guessed",
    sentences: [
      { id: 8629559, text: "I guessed you would come." },
      { id: 13400729, text: "I guessed that Tom had done it." },
      { id: 3469376, text: "No one would have guessed it!" },
    ],
  },
  {
    word: "herd",
    sentences: [
      { id: 12857361, text: "A herd of sheep walks across the field." },
      { id: 12489403, text: "A herd of cows stood in the field." },
      { id: 11850623, text: "There is enough grass here to feed the whole herd." },
    ],
  },
  {
    word: "led",
    sentences: [
      { id: 2960796, text: "Tom led the way and I followed." },
      { id: 9023318, text: "The guide led the group through the museum." },
      { id: 258452, text: "I led him by the hand." },
    ],
  },
  {
    word: "lead",
    sentences: [
      { id: 11830242, text: "Where does that road lead to?" },
      { id: 10172820, text: "Where does this path lead to?" },
      { id: 10589311, text: "Where does that door lead to?" },
    ],
  },
  {
    word: "mourning",
    sentences: [
      { id: 2600754, text: "The man is mourning after the sad news." },
      { id: 12404122, text: "The whole country is in mourning." },
      { id: 2897114, text: "Today is a day of mourning for the whole nation." },
    ],
  },
  {
    word: "passed",
    sentences: [
      { id: 2731250, text: "We passed one test, but failed the other." },
      { id: 13645744, text: "Time passed, and she calmed down." },
      { id: 9949270, text: "A lot of time has passed since then." },
    ],
  },
  {
    word: "past",
    sentences: [
      { id: 2416213, text: "Leave the past behind and take care of the present." },
      { id: 3086249, text: "Forget the past, live the future." },
      { id: 12948732, text: "By changing the past, he changed the present." },
    ],
  },
  {
    word: "proceed",
    sentences: [
      { id: 12772621, text: "Shall we proceed as planned?" },
      { id: 10733043, text: "Are you sure you want to proceed with this?" },
      { id: 3127952, text: "How do you suggest we proceed?" },
    ],
  },
  {
    word: "principal",
    sentences: [
      { id: 3447045, text: "Tom is the principal of a high school." },
      { id: 12207008, text: "Is this the principal of your school?" },
      { id: 1768736, text: "The principal presented the new teacher." },
    ],
  },
  {
    word: "principle",
    sentences: [
      { id: 13041456, text: "Respect must be our leading principle." },
      { id: 274969, text: "Majority rule is a basic principle of democracy." },
      { id: 251711, text: "My father made it a principle to keep early hours." },
    ],
  },
  {
    word: "profit",
    sentences: [
      { id: 258293, text: "I made a good profit by selling my car." },
      { id: 7126780, text: "How much profit do you expect?" },
      { id: 2293500, text: "I barely make any profit now." },
    ],
  },
  {
    word: "prophet",
    sentences: [
      { id: 6285331, text: "The prophet had a vision." },
      { id: 8249164, text: "He started studying the life of our prophet." },
      { id: 6815372, text: "The best prophet of the future is the past." },
    ],
  },
  {
    word: "stationery",
    sentences: [
      { id: 294817, text: "He bought some stationery at the school store." },
      { id: 9456980, text: "The department store also has a stationery department." },
      { id: 727807, text: "All of this stationery is his." },
    ],
  },
  {
    word: "steal",
    sentences: [
      { id: 19214, text: "A thief broke into the house to steal the money." },
      { id: 8510306, text: "Somebody is trying to steal your car." },
      { id: 10154611, text: "If you leave that there, someone might steal it." },
    ],
  },
  {
    word: "steel",
    sentences: [
      { id: 11049387, text: "The lift car is made of steel." },
      { id: 6050387, text: "Most kitchen sinks are made of stainless steel." },
      { id: 7305693, text: "Lead is soft and heavy. Iron is hard and steel harder." },
    ],
  },
  {
    word: "wary",
    sentences: [
      { id: 7996986, text: "My parents always told me to be wary of strangers." },
      { id: 4374030, text: "Mary is wary of strangers." },
      { id: 11231658, text: "Always be wary of your surroundings." },
    ],
  },
  {
    word: "weary",
    sentences: [
      { id: 12104890, text: "Tom closed his weary eyes." },
      { id: 261371, text: "I became weary of waiting for her." },
      { id: 12104889, text: "Rest your weary eyes." },
    ],
  },
]
