// SPDX-License-Identifier: CC-BY-2.0-FR
//
// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).
// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>
//
// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.
// "changed: true" means that we expanded a contraction, for example "don't" to "do not".
// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.

import type { TatoebaEntry } from '../bank'

export const TATOEBA_0001_BANK: readonly TatoebaEntry[] = [
  {
    word: "day",
    sentences: [
      { id: 706352, text: "The shop stays open all day." },
      { id: 1824576, text: "I learn new things every day." },
      { id: 1412436, text: "Do you go running every day?" },
    ],
  },
  {
    word: "child",
    sentences: [
      { id: 13137589, text: "Step by step, the child learns to walk." },
      { id: 12232185, text: "A child first learns to speak before they can write." },
      { id: 13971608, text: "The teacher gave the child a book." },
      { id: 9939349, text: "Take the child outside to play in the garden." },
    ],
  },
  {
    word: "man",
    sentences: [
      { id: 3389029, text: "The door opened and a man walked in." },
      { id: 43387, text: "The old man lives by himself." },
      { id: 11121150, text: "The man and the woman have a child." },
    ],
  },
  {
    word: "write",
    sentences: [
      { id: 3041972, text: "Do you know how to read and write?" },
      { id: 267130, text: "I have to write a letter." },
      { id: 3751689, text: "I started to write a book." },
    ],
  },
  {
    word: "school",
    sentences: [
      { id: 249353, text: "We go to school because we want to learn." },
      { id: 842632, text: "Do the children go to school?" },
      { id: 1572993, text: "The students do not have to go to school today.", changed: true },
    ],
  },
  {
    word: "play",
    sentences: [
      { id: 3121911, text: "Do you have any toys Tom can play with?" },
      { id: 2954144, text: "What kind of games do you like to play?" },
      { id: 4501459, text: "The children want to play outside." },
    ],
  },
  {
    word: "home",
    sentences: [
      { id: 268728, text: "Do you eat at home or eat out?" },
      { id: 1495776, text: "Do you have a computer at home?" },
      { id: 717037, text: "After work, I go right home." },
    ],
  },
  {
    word: "house",
    sentences: [
      { id: 325942, text: "Who lives in the house next door?" },
      { id: 269274, text: "We moved into a new house." },
      { id: 3138820, text: "A family lives in a big house." },
    ],
  },
  {
    word: "woman",
    sentences: [
      { id: 2839853, text: "I see a man and a woman." },
      { id: 387558, text: "I see a woman wearing black." },
      { id: 13645242, text: "I asked the woman at the door." },
    ],
  },
  {
    word: "book",
    sentences: [
      { id: 27300, text: "I read the whole book in one evening." },
      { id: 322090, text: "Have you ever written a book?" },
      { id: 257337, text: "I have been reading a book all morning." },
    ],
  },
  {
    word: "family",
    sentences: [
      { id: 1078035, text: "The family members sat around the table." },
      { id: 2308002, text: "I come from a big family." },
      { id: 3737332, text: "You should be with friends and family." },
    ],
  },
  {
    word: "hand",
    sentences: [
      { id: 681828, text: "The man raised his hand to ask a question." },
      { id: 265026, text: "If you have a question, please raise your right hand." },
      { id: 10165421, text: "Tom held the phone in his left hand." },
    ],
  },
  {
    word: "money",
    sentences: [
      { id: 253755, text: "I have enough money to buy this book." },
      { id: 1546292, text: "I do not have the money to buy a car.", changed: true },
      { id: 67737, text: "Do not spend too much money.", changed: true },
    ],
  },
  {
    word: "read",
    sentences: [
      { id: 245698, text: "Do you have any good books for children to read?" },
      { id: 22787, text: "We learn to read and write." },
      { id: 70266, text: "How many books do you read a month?" },
    ],
  },
  {
    word: "friend",
    sentences: [
      { id: 1260122, text: "Do you have a best friend?" },
      { id: 8625033, text: "Tom asked his friend if she wanted to come over." },
      { id: 7522188, text: "Everyone needs at least one close friend." },
    ],
  },
  {
    word: "open",
    sentences: [
      { id: 881438, text: "Will you please open the door?" },
      { id: 8344078, text: "What time do the shops open?" },
      { id: 6924212, text: "Leave the door open when you leave." },
    ],
  },
  {
    word: "buy",
    sentences: [
      { id: 258409, text: "I have enough money to buy a car." },
      { id: 2387496, text: "I need money to buy Tom a present." },
      { id: 680459, text: "The family wants to buy a house." },
    ],
  },
  {
    word: "room",
    sentences: [
      { id: 319592, text: "Close the door after you when you leave the room." },
      { id: 2301246, text: "I can hear Tom talking in the other room." },
      { id: 436461, text: "I bought a table for the living room." },
    ],
  },
  {
    word: "head",
    sentences: [
      { id: 48280, text: "The dog turned its head this way and that." },
    ],
  },
  {
    word: "car",
    sentences: [
      { id: 388285, text: "You must be careful when you drive a car." },
      { id: 69081, text: "Do you go by train or by car?" },
      { id: 21397, text: "Some of the students come to school by car." },
    ],
  },
  {
    word: "city",
    sentences: [
      { id: 8386782, text: "Do you live in the big city?" },
      { id: 9711650, text: "What city would you like to live in?" },
      { id: 5666286, text: "I grew up in this city." },
    ],
  },
  {
    word: "night",
    sentences: [
      { id: 255895, text: "I often sit up late at night to read." },
      { id: 1093304, text: "Tom left the lights on all night." },
      { id: 2734262, text: "Tom worked until late at night." },
    ],
  },
  {
    word: "train",
    sentences: [
      { id: 326143, text: "You must not get off the train before it stops." },
      { id: 9180762, text: "I come to school by train." },
      { id: 8466369, text: "What time does the train leave from here?" },
    ],
  },
  {
    word: "party",
    sentences: [
      { id: 262828, text: "We played a lot of games at the party." },
      { id: 4663248, text: "I asked Tom what I should bring to the party." },
      { id: 6340477, text: "Even Tom stayed until the end of the party." },
    ],
  },
  {
    word: "water",
    sentences: [
      { id: 6243709, text: "How many times a day do you drink water?" },
      { id: 3328115, text: "Can I get you some water?" },
      { id: 6238048, text: "I often help Tom carry water from the well." },
    ],
  },
  {
    word: "mother",
    sentences: [
      { id: 1259385, text: "My mother always gets up earlier in the morning." },
      { id: 3820393, text: "Tom helped his mother set the table." },
      { id: 2951778, text: "Do you think Tom looks like his mother?" },
    ],
  },
  {
    word: "walk",
    sentences: [
      { id: 687842, text: "Would you like to go for a walk?" },
      { id: 3051837, text: "Do you walk to school every day?" },
      { id: 1619639, text: "We must learn to walk before we can run." },
    ],
  },
  {
    word: "light",
    sentences: [
      { id: 319602, text: "Please turn out the light before leaving the room." },
      { id: 9001523, text: "May I turn the light on?" },
      { id: 2640430, text: "Tom opened the door and turned on the light." },
    ],
  },
  {
    word: "sit",
    sentences: [
      { id: 1532558, text: "Can I sit next to you?" },
      { id: 5849750, text: "Come back to the table and sit down." },
      { id: 984510, text: "Please, come in and sit down." },
    ],
  },
  {
    word: "letter",
    sentences: [
      { id: 5621269, text: "I wrote a long letter to Tom." },
      { id: 1028158, text: "Tom received a letter from Mary this morning." },
      { id: 3983894, text: "Maybe I should write a letter to Tom." },
    ],
  },
  {
    word: "class",
    sentences: [
      { id: 62893, text: "All the class waited for the new teacher." },
      { id: 10008658, text: "I will ask the teacher about it after class.", changed: true },
      { id: 6253958, text: "Have you ever been late for class?" },
    ],
  },
  {
    word: "town",
    sentences: [
      { id: 253665, text: "I grew up in this small town." },
      { id: 6961008, text: "How many people live in this town?" },
      { id: 5161988, text: "I live in the town centre." },
    ],
  },
  {
    word: "food",
    sentences: [
      { id: 1830495, text: "What kind of food do you like to eat?" },
      { id: 262711, text: "We eat many kinds of food." },
      { id: 2869058, text: "I always try to eat healthy food." },
    ],
  },
  {
    word: "colour",
    sentences: [
      { id: 12797545, text: "If you mix blue and yellow, what colour do you get?" },
      { id: 10351683, text: "My favourite colour is dark blue." },
      { id: 12321872, text: "What colour are the walls in your room?" },
    ],
  },
  {
    word: "drive",
    sentences: [
      { id: 2266019, text: "Have you learned to drive a car?" },
      { id: 2645063, text: "I will drive you to school.", changed: true },
      { id: 265594, text: "You must take care when you drive a car." },
    ],
  },
  {
    word: "eye",
    sentences: [
      { id: 13115144, text: "The eye sees and the ear hears." },
    ],
  },
  {
    word: "music",
    sentences: [
      { id: 1030726, text: "Could you turn the music down?" },
      { id: 2050680, text: "Tom and Mary played music together all evening." },
      { id: 5814038, text: "Tom really likes music a lot." },
    ],
  },
  {
    word: "game",
    sentences: [
      { id: 6702139, text: "Do you know how to play this game?" },
      { id: 37970, text: "Which team will win the game?" },
      { id: 9189246, text: "Do you know the rules of the game?" },
    ],
  },
  {
    word: "body",
    sentences: [
      { id: 13815107, text: "What is the longest bone in the human body?", changed: true },
      { id: 6205925, text: "When we sleep, our body temperature falls by several degrees." },
      { id: 12089949, text: "My whole body hurt too much to move." },
    ],
  },
  {
    word: "team",
    sentences: [
      { id: 9637072, text: "We play well together as a team." },
      { id: 6264100, text: "Tom and I play on the same team." },
      { id: 5726386, text: "I only want to help the team win." },
    ],
  },
  {
    word: "black",
    sentences: [
      { id: 257441, text: "I have a black and white dog." },
      { id: 12780609, text: "Why do you always wear black?" },
      { id: 3361840, text: "What happens to light in a black hole?" },
    ],
  },
  {
    word: "paper",
    sentences: [
      { id: 12190546, text: "Tom wrote something down on a piece of paper." },
      { id: 690934, text: "Please write the answer on this piece of paper." },
      { id: 8861329, text: "I looked for a piece of paper and a pen." },
    ],
  },
  {
    word: "computer",
    sentences: [
      { id: 2793915, text: "Do you like playing computer games?" },
      { id: 7357384, text: "Tom sits at a computer all day." },
      { id: 9811225, text: "Tom spends too much time in front of a computer." },
    ],
  },
  {
    word: "film",
    sentences: [
      { id: 11535074, text: "In the evening, we watched a film." },
      { id: 12694739, text: "I like to watch a film before I sleep." },
      { id: 12489363, text: "What film do you want to watch next?" },
    ],
  },
  {
    word: "morning",
    sentences: [
      { id: 1025686, text: "Tom gets up early in the morning." },
      { id: 1495742, text: "What time do you get up in the morning?" },
      { id: 2543200, text: "I took a shower this morning." },
    ],
  },
  {
    word: "shop",
    sentences: [
      { id: 253251, text: "I live next door to the toy shop." },
      { id: 2490419, text: "I work in a flower shop." },
      { id: 10804171, text: "I bought this book in the shop opposite the station." },
    ],
  },
  {
    word: "carry",
    sentences: [
      { id: 3763807, text: "Why do children have to carry such a heavy bag?" },
      { id: 9062909, text: "Could you carry this box into the living room?" },
      { id: 11888948, text: "You must carry the keys with you at all times." },
    ],
  },
  {
    word: "father",
    sentences: [
      { id: 1867824, text: "Tom turned out to be just like his father." },
      { id: 12760356, text: "People often say I look a lot like my father." },
      { id: 453815, text: "I would like to meet his father." },
    ],
  },
  {
    word: "table",
    sentences: [
      { id: 8208523, text: "We all sat down at the table and started talking." },
      { id: 6255886, text: "Tom put the book down on the table." },
      { id: 395063, text: "Can we sit at the table over there?" },
    ],
  },
  {
    word: "cut",
    sentences: [
      { id: 6245510, text: "How often does Tom get his hair cut?" },
      { id: 61680, text: "Are you going to cut down all the trees here?" },
    ],
  },
  {
    word: "girl",
    sentences: [
      { id: 1091967, text: "Have you seen a little girl with short black hair?" },
      { id: 252181, text: "I took the little girl by the hand." },
      { id: 274178, text: "Do you know the girl standing by the window?" },
    ],
  },
  {
    word: "eat",
    sentences: [
      { id: 27479, text: "You must not eat too much food at one time." },
      { id: 25071, text: "Can I have something to eat?" },
      { id: 1830495, text: "What kind of food do you like to eat?" },
    ],
  },
  {
    word: "phone",
    sentences: [
      { id: 4483281, text: "I talk to Tom on the phone every day." },
      { id: 8886338, text: "I called Tom, but a girl answered the phone." },
      { id: 279333, text: "I have to make a phone call." },
    ],
  },
  {
    word: "draw",
    sentences: [
      { id: 10643714, text: "Let me draw a map for you." },
      { id: 278454, text: "A ruler helps one to draw a straight line." },
    ],
  },
  {
    word: "white",
    sentences: [
      { id: 6108930, text: "I have a white dog and a black dog." },
      { id: 9638570, text: "The black phone is more expensive than the white one." },
    ],
  },
  {
    word: "door",
    sentences: [
      { id: 1868005, text: "Tom opened the door and walked in." },
      { id: 3080210, text: "Tom left the front door open when he left." },
      { id: 319592, text: "Close the door after you when you leave the room." },
    ],
  },
  {
    word: "teacher",
    sentences: [
      { id: 272892, text: "The teacher handed out the tests." },
      { id: 2163199, text: "We ask the teacher questions every day." },
      { id: 273026, text: "The teacher called each student by name." },
    ],
  },
  {
    word: "picture",
    sentences: [
      { id: 11687939, text: "Can you draw a picture of it?" },
      { id: 6423837, text: "Mary showed Tom a picture she drew." },
      { id: 10280587, text: "Do you know the man in this picture?" },
    ],
  },
  {
    word: "boy",
    sentences: [
      { id: 46312, text: "The boy grew up to be a great man." },
      { id: 1934884, text: "The young boy helped the old woman." },
      { id: 254828, text: "I gave it to the little boy." },
    ],
  },
  {
    word: "happy",
    sentences: [
      { id: 2044794, text: "What can I do to make you happy?" },
      { id: 2044663, text: "I like to make people happy." },
      { id: 2044683, text: "Tom seemed happy to see you." },
    ],
  },
  {
    word: "road",
    sentences: [
      { id: 36964, text: "Drivers must look out for children crossing the road." },
      { id: 280497, text: "Look out for cars when you cross the road." },
      { id: 12319759, text: "Please park on the left side of the road." },
    ],
  },
  {
    word: "wear",
    sentences: [
      { id: 6877395, text: "What kind of clothes do you wear to school?" },
      { id: 5936594, text: "I almost always wear a hat when I go outside." },
      { id: 7470199, text: "Why do you always wear blue?" },
    ],
  },
  {
    word: "kid",
    sentences: [
      { id: 8285494, text: "I used to play here when I was a kid." },
      { id: 9474062, text: "Tom cried like a little kid." },
    ],
  },
  {
    word: "space",
    sentences: [
      { id: 5647181, text: "Have you ever been to outer space?" },
      { id: 2707463, text: "What does the earth look like from space?" },
      { id: 4770627, text: "The bed takes up a lot of space." },
    ],
  },
  {
    word: "foot",
    sentences: [
      { id: 69525, text: "Do you go to school on foot or by bicycle?" },
      { id: 68951, text: "Will you go on foot or by bus?" },
    ],
  },
  {
    word: "animal",
    sentences: [
      { id: 6604256, text: "If you touch an animal or plant, touch it gently." },
      { id: 239220, text: "A dog is a faithful animal." },
      { id: 1717610, text: "Have you ever drawn an animal?" },
    ],
  },
  {
    word: "street",
    sentences: [
      { id: 7541680, text: "Tom lives in the house across the street." },
      { id: 24529, text: "I can see some people walking across the street." },
      { id: 13214838, text: "All the houses on this street look the same." },
    ],
  },
  {
    word: "sport",
    sentences: [
      { id: 13163536, text: "Tennis is a very popular sport." },
      { id: 2361640, text: "I like to play tennis. What sport do you like to play?" },
      { id: 585759, text: "Football is the best known sport in the world." },
    ],
  },
  {
    word: "fire",
    sentences: [
      { id: 23809, text: "A fire broke out on the first floor." },
      { id: 10119973, text: "What should I do in case of fire?" },
      { id: 57937, text: "A forest fire broke out in this area." },
    ],
  },
  {
    word: "laugh",
    sentences: [
      { id: 464358, text: "We began to laugh when he told the joke." },
      { id: 5248415, text: "I love to make people laugh." },
      { id: 9805777, text: "What makes you laugh the most?" },
    ],
  },
  {
    word: "arm",
    sentences: [
      { id: 8959996, text: "Have you ever broken an arm?" },
      { id: 12057172, text: "I could not lift my right arm.", changed: true },
    ],
  },
  {
    word: "fast",
    sentences: [
      { id: 8230201, text: "Can you run as fast as Tom?" },
      { id: 56482, text: "How fast does this train run?" },
      { id: 6519789, text: "Tom and Mary ran as fast as they could." },
    ],
  },
  {
    word: "summer",
    sentences: [
      { id: 13835641, text: "In the summer, it gets very hot here." },
      { id: 13654735, text: "Do you go to the sea every summer?" },
      { id: 5288223, text: "I read a lot of books last summer." },
    ],
  },
  {
    word: "drink",
    sentences: [
      { id: 2064806, text: "Can I have something to drink?" },
      { id: 3154873, text: "Do you want something to eat or drink?" },
      { id: 240661, text: "You can eat and drink as much as you want." },
    ],
  },
  {
    word: "park",
    sentences: [
      { id: 248677, text: "We took a walk in the park." },
      { id: 11516283, text: "Children play in the park every day." },
      { id: 9751006, text: "Tom watched the children playing in the park." },
    ],
  },
  {
    word: "key",
    sentences: [
      { id: 9416512, text: "Do you have a key to this door?" },
      { id: 4013481, text: "Do you have the key to this room?" },
      { id: 6256030, text: "Tom looked for the key to the door." },
    ],
  },
  {
    word: "plant",
    sentences: [
      { id: 10669833, text: "Where are you going to plant that tree?" },
      { id: 6680105, text: "Would you help me plant these seeds?" },
      { id: 12272304, text: "Did you plant all these flowers yourself?" },
    ],
  },
  {
    word: "paint",
    sentences: [
      { id: 6842950, text: "Should I paint the wall white or green?" },
      { id: 4135134, text: "Tom would like to paint his room blue." },
      { id: 2259307, text: "The door needs another coat of paint." },
    ],
  },
  {
    word: "evening",
    sentences: [
      { id: 2542024, text: "I watch the news every evening." },
      { id: 243407, text: "How about eating out this evening?" },
      { id: 2483366, text: "We have friends coming over this evening." },
    ],
  },
  {
    word: "catch",
    sentences: [
      { id: 9044162, text: "You have to leave early to catch the train." },
      { id: 3597751, text: "I left early to catch the first bus." },
      { id: 6340967, text: "Do you always catch the same bus every morning?" },
    ],
  },
  {
    word: "son",
    sentences: [
      { id: 12211664, text: "Do you have a son or a daughter?" },
      { id: 9182186, text: "The father called out for his son." },
      { id: 6659496, text: "I have a son named Tom." },
    ],
  },
  {
    word: "bed",
    sentences: [
      { id: 320922, text: "The mother put the children to bed." },
      { id: 33484, text: "I go to bed very early." },
      { id: 268919, text: "Put out the light before you go to bed." },
    ],
  },
  {
    word: "station",
    sentences: [
      { id: 432779, text: "How can I get to the train station?" },
      { id: 1885295, text: "The train left the station a few minutes ago." },
      { id: 43433, text: "The train stops at every station." },
    ],
  },
  {
    word: "player",
    sentences: [
      { id: 69886, text: "I hear that you are a good tennis player." },
      { id: 13333233, text: "I want to be a football player." },
      { id: 3619182, text: "Tom is better than any other player on the team." },
    ],
  },
  {
    word: "wall",
    sentences: [
      { id: 680111, text: "Put the desk against the wall." },
      { id: 11184941, text: "I will hang the picture on the wall.", changed: true },
      { id: 6253313, text: "I looked at the clock on the wall." },
    ],
  },
  {
    word: "window",
    sentences: [
      { id: 471878, text: "We all looked out the window." },
      { id: 2958446, text: "Tom walked across the room and opened the window." },
      { id: 265519, text: "Could you open the car window?" },
    ],
  },
  {
    word: "tree",
    sentences: [
      { id: 323609, text: "Almost all the leaves fell off the tree." },
      { id: 1722855, text: "Have you ever planted a tree?" },
      { id: 43807, text: "I cut a branch from the tree." },
    ],
  },
  {
    word: "holiday",
    sentences: [
      { id: 12163692, text: "We went on holiday together last summer." },
      { id: 12307499, text: "Where are you planning to go on holiday next summer?" },
      { id: 48726, text: "All the schools are closed on that holiday." },
    ],
  },
  {
    word: "machine",
    sentences: [
      { id: 1028023, text: "Tom showed Mary how to use the washing machine." },
    ],
  },
  {
    word: "floor",
    sentences: [
      { id: 10361119, text: "A piece of paper fell on to the floor." },
      { id: 11023286, text: "How many rooms are there on the first floor?" },
      { id: 8912281, text: "I slept on the hard floor." },
    ],
  },
  {
    word: "wide",
    sentences: [
      { id: 3071662, text: "Is the road wide enough for two-way traffic?" },
      { id: 682303, text: "The valley was twenty miles wide." },
    ],
  },
  {
    word: "club",
    sentences: [
      { id: 70243, text: "Do you intend to join that tennis club?" },
      { id: 8946675, text: "Are you a member of a sports club?" },
    ],
  },
  {
    word: "doctor",
    sentences: [
      { id: 4016355, text: "Do you need to see a doctor?" },
      { id: 36486, text: "Why do you want to be a doctor?" },
      { id: 4803262, text: "Tom wants to be a doctor when he grows up." },
    ],
  },
  {
    word: "card",
    sentences: [
      { id: 12482734, text: "How do you get a library card?" },
    ],
  },
  {
    word: "beautiful",
    sentences: [
      { id: 69803, text: "What a beautiful garden you have!" },
      { id: 5623619, text: "What a beautiful dress you have on!" },
      { id: 7927622, text: "What a beautiful day to be out and about." },
    ],
  },
  {
    word: "television",
    sentences: [
      { id: 245734, text: "Instead of watching television, the children played outside." },
      { id: 12580570, text: "I prefer reading to watching television." },
      { id: 682374, text: "Do you like to watch sports on television?" },
    ],
  },
  {
    word: "red",
    sentences: [
      { id: 12522786, text: "When the light turns red, you stop." },
      { id: 13760779, text: "Some leaves turn red, others yellow." },
      { id: 11304835, text: "Put the red apples here and the green ones there." },
    ],
  },
  {
    word: "bus",
    sentences: [
      { id: 5548671, text: "Tom walked to the bus stop." },
      { id: 6239407, text: "Tom and I take the same bus home from school." },
      { id: 322404, text: "Where do you get on the bus every day?" },
    ],
  },
  {
    word: "village",
    sentences: [
      { id: 8655306, text: "Tom grew up in a small village." },
      { id: 10095826, text: "Not many people live in this village." },
      { id: 11763298, text: "We live at the other end of the village." },
    ],
  },
  {
    word: "brother",
    sentences: [
      { id: 10004365, text: "Does he have a brother or a sister?" },
      { id: 4016836, text: "Tom shares a room with his older brother." },
      { id: 5510725, text: "Tom looks a lot like his older brother." },
    ],
  },
  {
    word: "trip",
    sentences: [
      { id: 12925691, text: "Every year, I go on a trip with my family." },
      { id: 8821425, text: "A family took a trip to the mountains." },
      { id: 6310263, text: "Have you ever been on a camping trip?" },
    ],
  },
  {
    word: "sleep",
    sentences: [
      { id: 1821304, text: "How many hours do you sleep at night?" },
      { id: 1126701, text: "You should turn off the light before going to sleep." },
      { id: 2308275, text: "I could not sleep at all last night.", changed: true },
    ],
  },
  {
    word: "fish",
    sentences: [
      { id: 11746462, text: "You can catch fish for food while fishing." },
      { id: 3154697, text: "Tom wanted to catch some fish to eat." },
      { id: 1717364, text: "Have you ever caught a fish?" },
    ],
  },
  {
    word: "touch",
    sentences: [
      { id: 2285825, text: "Do not touch anything without asking.", changed: true },
    ],
  },
  {
    word: "clean",
    sentences: [
      { id: 5514041, text: "You should always keep the room clean." },
      { id: 881831, text: "Why do you clean the house each week?" },
      { id: 5799078, text: "Do you always help Tom clean his room?" },
    ],
  },
  {
    word: "fill",
    sentences: [
      { id: 10221468, text: "Can you fill in the missing words in this sentence?" },
    ],
  },
  {
    word: "star",
    sentences: [
      { id: 3474658, text: "No star was seen that night." },
      { id: 2732458, text: "Did you know that the star nearest to Earth is the Sun?" },
    ],
  },
  {
    word: "throw",
    sentences: [
      { id: 239144, text: "Do not throw a stone at the dog.", changed: true },
      { id: 2796736, text: "Please do not throw the bottle out the window.", changed: true },
      { id: 280383, text: "Do not throw away cans on the street.", changed: true },
    ],
  },
  {
    word: "blue",
    sentences: [
      { id: 13541064, text: "Do you know why the sky looks so blue?" },
      { id: 68853, text: "Can you tell green from blue?" },
      { id: 4529141, text: "We have decided to paint the walls light blue.", changed: true },
    ],
  },
  {
    word: "box",
    sentences: [
      { id: 8106838, text: "Tom put the box on the table and opened it." },
      { id: 6658405, text: "Tom carried in a box full of books." },
      { id: 1884468, text: "Tom picked up the box and tried to open it." },
    ],
  },
  {
    word: "huge",
    sentences: [
      { id: 8340985, text: "There was a huge crowd of people there." },
      { id: 9199796, text: "The storm caused a huge amount of damage." },
    ],
  },
  {
    word: "cold",
    sentences: [
      { id: 6245962, text: "The last few days have been very cold." },
      { id: 6864882, text: "Tom fell into the cold water." },
      { id: 7490836, text: "I do not like cold days.", changed: true },
    ],
  },
  {
    word: "push",
    sentences: [
      { id: 39024, text: "Can you push the door open?" },
    ],
  },
  {
    word: "baby",
    sentences: [
      { id: 9843777, text: "I think I hear a baby crying." },
      { id: 1992379, text: "Could you please put the baby to bed?" },
      { id: 33980, text: "Look at a baby sleeping in the bed." },
    ],
  },
  {
    word: "sing",
    sentences: [
      { id: 5794343, text: "You can sing much better than Tom." },
      { id: 4828091, text: "I like it when you sing." },
    ],
  },
  {
    word: "fly",
    sentences: [
      { id: 7431223, text: "How fast does that bird fly?" },
      { id: 5303448, text: "If humans were meant to fly, they would have wings." },
      { id: 11436755, text: "Where did you learn to fly a plane?" },
    ],
  },
  {
    word: "hot",
    sentences: [
      { id: 8353840, text: "How hot does it get here in the summer?" },
      { id: 282090, text: "During hot weather, be sure to drink lots of water." },
      { id: 2543336, text: "Tom turned on the hot water." },
    ],
  },
  {
    word: "dog",
    sentences: [
      { id: 1697017, text: "What time do you walk the dog?" },
      { id: 6597980, text: "Could you please take the dog out for a walk?" },
      { id: 239160, text: "The dog ran around and around." },
    ],
  },
  {
    word: "dress",
    sentences: [
      { id: 13395650, text: "Which dress do you want to wear?" },
      { id: 3426210, text: "Mary changed into a very nice dress." },
      { id: 1030054, text: "Mary looks good in a black dress." },
    ],
  },
  {
    word: "author",
    sentences: [
      { id: 8924821, text: "Who is the author of that book?", changed: true },
      { id: 277706, text: "The author illustrated his book with a lot of pictures." },
      { id: 2680423, text: "What was the author thinking while she was writing this book?" },
    ],
  },
  {
    word: "hair",
    sentences: [
      { id: 8388651, text: "I have brown hair and blue eyes." },
      { id: 278062, text: "I saw a girl with long hair." },
      { id: 8418349, text: "How often do you get your hair cut?" },
    ],
  },
  {
    word: "dark",
    sentences: [
      { id: 255975, text: "I must get home before it gets dark." },
      { id: 13836944, text: "Tom walks carefully, trying to see in the dark." },
      { id: 13581808, text: "Do not sit in the dark; turn the light on.", changed: true },
    ],
  },
  {
    word: "daughter",
    sentences: [
      { id: 11545382, text: "My youngest daughter will soon be starting school." },
      { id: 2539343, text: "Tom took his daughter Mary to school." },
      { id: 12914730, text: "I have one daughter and one son." },
    ],
  },
  {
    word: "newspaper",
    sentences: [
      { id: 251734, text: "My father reads the newspaper every morning." },
      { id: 13045125, text: "I only read the sports section of the newspaper." },
      { id: 3424468, text: "Tom wrote an article about it in the school newspaper." },
    ],
  },
  {
    word: "clock",
    sentences: [
      { id: 3956159, text: "Do you have an alarm clock in your room?" },
      { id: 12377810, text: "When the clock strikes four, I leave." },
      { id: 11124126, text: "Tom woke up before the alarm clock went off." },
    ],
  },
  {
    word: "weekend",
    sentences: [
      { id: 321383, text: "We go out together every weekend." },
      { id: 7731990, text: "Tom stays at home almost every weekend." },
      { id: 9371877, text: "We have gone out of town for the weekend." },
    ],
  },
  {
    word: "green",
    sentences: [
      { id: 12506978, text: "Cross the road only when the light is green." },
      { id: 272443, text: "The light changed from red to green." },
      { id: 8938339, text: "The leaves are a striking green and white." },
    ],
  },
  {
    word: "song",
    sentences: [
      { id: 3596762, text: "I would like to sing you a song.", changed: true },
      { id: 6340060, text: "You should sing that new song you wrote last week." },
      { id: 9607153, text: "Do you know what song Tom wants to sing?" },
    ],
  },
  {
    word: "afternoon",
    sentences: [
      { id: 1025681, text: "Tom goes for a walk every afternoon." },
      { id: 2540785, text: "Tom stayed at home all afternoon." },
      { id: 242524, text: "May I come see you this afternoon?" },
    ],
  },
  {
    word: "clothes",
    sentences: [
      { id: 6776579, text: "What kinds of clothes do you like to wear?" },
      { id: 2033890, text: "You might want to change into some clean clothes." },
      { id: 10631964, text: "Do you like shopping for new clothes?" },
    ],
  },
  {
    word: "dance",
    sentences: [
      { id: 2016648, text: "I want to learn to dance like you." },
      { id: 5291061, text: "Tom can dance better than Mary." },
    ],
  },
  {
    word: "sister",
    sentences: [
      { id: 10287713, text: "I have a little brother and a big sister." },
      { id: 6078530, text: "I have a sister who plays tennis." },
      { id: 10023014, text: "I only have one younger sister." },
    ],
  },
  {
    word: "rock",
    sentences: [
      { id: 5799516, text: "The bread is as hard as a rock." },
      { id: 5725827, text: "Do you want to learn rock climbing?" },
    ],
  },
  {
    word: "garden",
    sentences: [
      { id: 8910373, text: "Have you already watered the flowers in the garden?" },
      { id: 14032987, text: "The plants in this garden grow quickly." },
      { id: 1744940, text: "I have to plant trees in the garden." },
    ],
  },
  {
    word: "fix",
    sentences: [
      { id: 3171336, text: "Tom helped Mary fix the broken table." },
    ],
  },
  {
    word: "magazine",
    sentences: [
      { id: 6412811, text: "Mary read a magazine while she waited for the bus." },
      { id: 3223174, text: "Tom sat in the waiting room reading a magazine." },
      { id: 12215145, text: "What kind of magazine are you reading?" },
    ],
  },
  {
    word: "sea",
    sentences: [
      { id: 2951283, text: "Some fish live in rivers, others in the sea." },
      { id: 7054427, text: "Fish live in the river and the sea." },
      { id: 1176293, text: "You must pay attention when swimming in the sea." },
    ],
  },
  {
    word: "smile",
    sentences: [
      { id: 9757353, text: "Tom left with a smile on his face." },
      { id: 63564, text: "Will you smile at the camera, please?" },
      { id: 5496405, text: "Tom liked to make people smile." },
    ],
  },
  {
    word: "wind",
    sentences: [
      { id: 10738329, text: "I can hear the wind blowing." },
      { id: 668550, text: "The leaves blew away in the wind." },
      { id: 13003965, text: "By the sea, the wind blows hard." },
    ],
  },
  {
    word: "warm",
    sentences: [
      { id: 5915233, text: "Come over here and warm yourself by the fire." },
      { id: 276795, text: "Ice turns to water when it gets warm." },
      { id: 4442395, text: "Put on warm clothes, the night air is very cold." },
    ],
  },
  {
    word: "writer",
    sentences: [
      { id: 886174, text: "The writer is working on his new book." },
      { id: 10459720, text: "You become a writer by writing." },
      { id: 58495, text: "Who do you think is the writer of this novel?" },
    ],
  },
  {
    word: "safe",
    sentences: [
      { id: 516031, text: "Keep money in a safe place." },
      { id: 9182986, text: "Please be careful and stay safe." },
      { id: 5036425, text: "I just want to get home safe and sound." },
    ],
  },
  {
    word: "telephone",
    sentences: [
      { id: 12185206, text: "The telephone rang and Tom answered." },
      { id: 1307568, text: "As soon as I got home, the telephone rang." },
      { id: 30708, text: "If the telephone rings, can you answer it?" },
    ],
  },
]
