// SPDX-License-Identifier: CC-BY-2.0-FR
//
// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).
// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>
//
// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.
// "changed: true" means that we expanded a contraction, for example "don't" to "do not".
// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.

import type { TatoebaEntry } from '../bank'

export const TATOEBA_0008_BANK: readonly TatoebaEntry[] = [
  {
    word: "corners",
    sentences: [
      { id: 6210044, text: "A square has four corners and four sides." },
      { id: 2992925, text: "Why does a football field have four corners?" },
      { id: 12170477, text: "The corners need to be rounded." },
    ],
  },
  {
    word: "amazed",
    sentences: [
      { id: 261233, text: "I was amazed by her quick response." },
      { id: 254312, text: "I was amazed at the results." },
      { id: 13079835, text: "I was amazed to learn about such a way of life." },
    ],
  },
  {
    word: "firm",
    sentences: [
      { id: 4502936, text: "Tom works for a large firm." },
      { id: 49082, text: "The firm is known for its high-quality products." },
      { id: 28939, text: "I have a firm belief in his innocence." },
    ],
  },
  {
    word: "complicated",
    sentences: [
      { id: 12386813, text: "Why make things complicated, when we can make everything simple?" },
      { id: 5839834, text: "How can something so simple become so complicated?" },
      { id: 9780406, text: "Things are a lot more complicated than they look." },
    ],
  },
  {
    word: "agreement",
    sentences: [
      { id: 3598147, text: "We came to an agreement on a price." },
      { id: 3209666, text: "We reached an agreement at the end of the meeting." },
      { id: 286113, text: "I am in agreement with most of what he says." },
    ],
  },
  {
    word: "respect",
    sentences: [
      { id: 10137228, text: "You should treat everyone with respect." },
      { id: 12613421, text: "Treat everyone with kindness and respect." },
      { id: 5500338, text: "I have a lot of respect for Tom." },
    ],
  },
  {
    word: "satisfied",
    sentences: [
      { id: 4618453, text: "Some people are never satisfied with what they have." },
      { id: 6064306, text: "Are you satisfied with the service here?" },
      { id: 41216, text: "On the whole I am satisfied with the result." },
    ],
  },
  {
    word: "progress",
    sentences: [
      { id: 21331, text: "The students are making good progress in English." },
      { id: 1039466, text: "We made a lot of progress today." },
      { id: 2503320, text: "Science has made a great deal of progress." },
    ],
  },
  {
    word: "fifth",
    sentences: [
      { id: 13694070, text: "The fifth month of the year is May." },
      { id: 1183660, text: "I live on the fifth floor." },
      { id: 13081274, text: "Earth is the fifth largest planet in our solar system." },
    ],
  },
  {
    word: "tricks",
    sentences: [
      { id: 8946738, text: "The magician performs a few card tricks." },
      { id: 12233697, text: "Tom will perform a few magic tricks for us." },
      { id: 7131856, text: "Can old dogs learn new tricks?" },
    ],
  },
  {
    word: "keen",
    sentences: [
      { id: 3022410, text: "The dog has a very keen sense of smell." },
      { id: 47543, text: "The kid has a keen sense of hearing." },
      { id: 21345, text: "I was keen on classical music in my school days." },
    ],
  },
  {
    word: "glimpse",
    sentences: [
      { id: 258880, text: "I caught a glimpse of him in the crowd." },
      { id: 326179, text: "We caught a glimpse of the castle from the window of our train." },
      { id: 268304, text: "We had a glimpse of the lake as we flew over it." },
    ],
  },
  {
    word: "relaxed",
    sentences: [
      { id: 1938845, text: "I thought Tom would be nervous, but he was very relaxed." },
      { id: 6662387, text: "Tom is always very calm and relaxed." },
      { id: 257673, text: "I was nervous at first, but gradually got more relaxed." },
    ],
  },
  {
    word: "details",
    sentences: [
      { id: 12054881, text: "You should ask Tom for details." },
      { id: 8957494, text: "Please see below for more details." },
      { id: 4133581, text: "I will tell you all the details later.", changed: true },
    ],
  },
  {
    word: "expensive",
    sentences: [
      { id: 49798, text: "Few people can buy such an expensive car." },
      { id: 1026978, text: "Tom bought a very expensive camera." },
      { id: 27250, text: "How much is the most expensive car?" },
    ],
  },
  {
    word: "damage",
    sentences: [
      { id: 275456, text: "The storm did a lot of damage to the crops." },
      { id: 11471254, text: "The fire caused significant damage to my house." },
      { id: 11560034, text: "The storm caused great damage to the city." },
    ],
  },
  {
    word: "tails",
    sentences: [
      { id: 5325921, text: "Foxes have long tails and pointed ears." },
      { id: 1396365, text: "Rabbits have long ears and short tails." },
      { id: 13591452, text: "There are cats without tails." },
    ],
  },
  {
    word: "fuss",
    sentences: [
      { id: 24975, text: "Stop making a fuss over nothing." },
      { id: 4017437, text: "What was all the fuss about?" },
      { id: 13823964, text: "He likes making a huge fuss over it." },
    ],
  },
  {
    word: "surprising",
    sentences: [
      { id: 276993, text: "The news was very surprising to her." },
      { id: 3795249, text: "The researchers made a surprising discovery." },
      { id: 10314497, text: "There was a surprising amount of interest." },
    ],
  },
  {
    word: "expert",
    sentences: [
      { id: 680893, text: "A doctor is an expert in medicine." },
      { id: 3680801, text: "The boy seems to be an expert on plants." },
      { id: 6002346, text: "Tom is an expert at solving mysteries." },
    ],
  },
  {
    word: "noisy",
    sentences: [
      { id: 12805524, text: "The room was so noisy that Tom covered his ears." },
      { id: 10114105, text: "I closed the window because it was too noisy outside." },
      { id: 320736, text: "My mother told me not to be noisy." },
    ],
  },
  {
    word: "gasp",
    sentences: [
      { id: 6627443, text: "His appearance made me gasp." },
      { id: 5736012, text: "Tom came up for a gasp of air." },
      { id: 3915521, text: "I heard her gasp." },
    ],
  },
  {
    word: "tangled",
    sentences: [
      { id: 2570933, text: "Her hair was tangled." },
      { id: 13891049, text: "My brother borrowed my net and now it is all tangled.", changed: true },
      { id: 8750549, text: "A bird with tangled wings cannot fly." },
    ],
  },
  {
    word: "muffled",
    sentences: [
      { id: 9372089, text: "The carpet muffled the sound of my feet." },
      { id: 9946763, text: "Mary could hear the sounds of muffled laughter through the wall." },
    ],
  },
  {
    word: "noses",
    sentences: [
      { id: 22686, text: "We smell with our noses." },
      { id: 11884716, text: "Cats have small little noses." },
      { id: 11887625, text: "We should use tissues to clean our noses, not our fingers." },
    ],
  },
  {
    word: "elbow",
    sentences: [
      { id: 6238148, text: "Tom hurt his elbow when he slipped on the ice." },
      { id: 11394449, text: "I hurt my elbow while playing tennis." },
      { id: 2693924, text: "The joint in my left elbow hurts." },
    ],
  },
  {
    word: "peaceful",
    sentences: [
      { id: 5073956, text: "The people here live a peaceful life." },
      { id: 12764628, text: "Mary found a peaceful spot to relax by the sea." },
      { id: 12114304, text: "I enjoyed a peaceful walk in nature." },
    ],
  },
  {
    word: "personal",
    sentences: [
      { id: 10878604, text: "I know this from personal experience." },
      { id: 10066662, text: "Can I ask you a few personal questions?" },
      { id: 11882318, text: "You should never share personal information online." },
    ],
  },
  {
    word: "load",
    sentences: [
      { id: 48666, text: "The bridge will give way under such a heavy load." },
      { id: 6342035, text: "What else do you need to load into the car?" },
      { id: 13314618, text: "What a load of potatoes I gave them!" },
    ],
  },
  {
    word: "brand",
    sentences: [
      { id: 10251023, text: "The brand new pen is easy to use." },
      { id: 10637159, text: "A brand name does not guarantee quality." },
      { id: 10894804, text: "Have you bought a brand-new car?" },
    ],
  },
  {
    word: "dizzy",
    sentences: [
      { id: 267732, text: "Feeling a little dizzy, I sat down for a while." },
      { id: 2329567, text: "I get dizzy when I stand up." },
      { id: 2147931, text: "I feel dizzy every time I get up." },
    ],
  },
  {
    word: "reasons",
    sentences: [
      { id: 670252, text: "There are many good reasons not to do it." },
      { id: 10137463, text: "There are good reasons to believe what he says." },
      { id: 3724723, text: "We have many reasons to be hopeful." },
    ],
  },
  {
    word: "wink",
    sentences: [
      { id: 8593156, text: "Did Tom wink at you?" },
      { id: 3822520, text: "Did you just wink at me?" },
    ],
  },
  {
    word: "contact",
    sentences: [
      { id: 5289514, text: "Please contact me if you have any questions." },
      { id: 326313, text: "When you contact me, please do so by phone." },
      { id: 7731727, text: "Tom tried not to make eye contact with Mary." },
    ],
  },
  {
    word: "bump",
    sentences: [
      { id: 10986808, text: "Be careful not to bump into anything." },
      { id: 13708932, text: "Turn aside before you bump into the tree." },
      { id: 12167742, text: "Did you bump your head again?" },
    ],
  },
  {
    word: "shops",
    sentences: [
      { id: 11314648, text: "There are many expensive shops along the street." },
      { id: 1392479, text: "I went to many shops to look for the book." },
      { id: 9960670, text: "In town, the shops were closed." },
    ],
  },
  {
    word: "bolt",
    sentences: [
      { id: 11591707, text: "I tightened the bolt with my fingers." },
      { id: 239945, text: "Do not forget to bolt the door.", changed: true },
      { id: 11021396, text: "I saw a lightning bolt." },
    ],
  },
  {
    word: "original",
    sentences: [
      { id: 9952749, text: "Is this the original or a copy?" },
      { id: 11802679, text: "The original song sounds much better." },
      { id: 243958, text: "The final plan differs greatly from the original one." },
    ],
  },
  {
    word: "muddy",
    sentences: [
      { id: 3168561, text: "The road was muddy and slippery." },
      { id: 9668888, text: "The muddy road ruined my new shoes." },
      { id: 3360953, text: "Please take off your muddy boots." },
    ],
  },
  {
    word: "slight",
    sentences: [
      { id: 3022287, text: "Tom has a slight cold." },
      { id: 326586, text: "I have a slight pain in my side." },
      { id: 23489, text: "We had a slight difference of opinion." },
    ],
  },
  {
    word: "twist",
    sentences: [
      { id: 13756291, text: "The road has a sharp twist." },
      { id: 11889025, text: "Remember to twist the handle and stop the water flow." },
      { id: 6833264, text: "Do not twist or bend!" },
    ],
  },
  {
    word: "rings",
    sentences: [
      { id: 13452651, text: "The mother has two gold rings on her finger." },
      { id: 30708, text: "If the telephone rings, can you answer it?" },
      { id: 881464, text: "I will leave as soon as the bell rings." },
    ],
  },
  {
    word: "responsible",
    sentences: [
      { id: 11886951, text: "You need to be responsible for your actions." },
      { id: 3890548, text: "The parents are responsible for the education of the children." },
      { id: 276357, text: "Who is responsible for leaving the window open?" },
    ],
  },
  {
    word: "curved",
    sentences: [
      { id: 12244786, text: "A straight road is shorter than a curved one." },
      { id: 12244788, text: "Is this line straight or curved?" },
      { id: 6820214, text: "This phone has a curved screen." },
    ],
  },
  {
    word: "mouthful",
    sentences: [
      { id: 9086262, text: "He drank a mouthful of water." },
    ],
  },
  {
    word: "clapping",
    sentences: [
      { id: 10156438, text: "Tom started clapping, and everyone else quickly joined in." },
      { id: 11972310, text: "The baby was clapping." },
      { id: 7782453, text: "You can turn on the lights by clapping." },
    ],
  },
  {
    word: "inches",
    sentences: [
      { id: 11587231, text: "There were four inches of snow on the ground." },
      { id: 3071736, text: "I need a piece of wood about three inches thick." },
      { id: 682124, text: "I am five feet, two inches tall." },
    ],
  },
  {
    word: "splash",
    sentences: [
      { id: 12882957, text: "It fell into the water with a splash." },
      { id: 7376787, text: "Mary heard a loud splash behind her." },
      { id: 12307346, text: "Did you hear a splash?" },
    ],
  },
  {
    word: "pattern",
    sentences: [
      { id: 2820737, text: "Where did you get the pattern for your new dress?" },
      { id: 11972349, text: "No two giraffes have the same coat pattern." },
      { id: 11892815, text: "Do you own a belt with a unique pattern?" },
    ],
  },
  {
    word: "style",
    sentences: [
      { id: 2270139, text: "What style of furniture would you like?" },
      { id: 257043, text: "I want the same style of jacket as yours." },
      { id: 13976589, text: "I really liked the writing style of the author." },
    ],
  },
  {
    word: "unexpected",
    sentences: [
      { id: 3723385, text: "Receiving a gift from you was an unexpected surprise." },
      { id: 47345, text: "I jumped at the unexpected news." },
      { id: 12961389, text: "Life often takes unexpected turns." },
    ],
  },
  {
    word: "fork",
    sentences: [
      { id: 3154724, text: "Tom picked up his fork and began to eat." },
      { id: 7954677, text: "Soup cannot be eaten with a fork." },
      { id: 8292495, text: "Beat the egg with a fork." },
    ],
  },
  {
    word: "fluffy",
    sentences: [
      { id: 4853303, text: "The snow was soft and fluffy." },
      { id: 1164640, text: "This towel is so soft and fluffy. It feels good!" },
      { id: 327243, text: "The bread was baked light and fluffy." },
    ],
  },
  {
    word: "price",
    sentences: [
      { id: 253723, text: "I bought this dress at a low price." },
      { id: 3147912, text: "Today you can get two for the price of one." },
      { id: 10512827, text: "The price of oil continues to rise." },
    ],
  },
  {
    word: "cups",
    sentences: [
      { id: 6341936, text: "How many cups of tea do you drink every day?" },
      { id: 3722473, text: "Tom placed some cups of tea on the table." },
      { id: 8304419, text: "I had two cups of tea." },
    ],
  },
  {
    word: "curly",
    sentences: [
      { id: 9130477, text: "My mother has straight hair and I have curly hair." },
      { id: 3560904, text: "Mary has short, curly brown hair." },
      { id: 8296020, text: "Is your hair naturally curly?" },
    ],
  },
  {
    word: "stern",
    sentences: [
      { id: 23371, text: "Our teacher is stern to us." },
      { id: 1482812, text: "Mary gave Tom a stern look." },
      { id: 11994503, text: "The teacher gave her pupils a stern telling-off." },
    ],
  },
  {
    word: "nostrils",
    sentences: [
      { id: 10750486, text: "Why do humans have two nostrils?" },
      { id: 8546716, text: "Giraffes can close their nostrils." },
    ],
  },
  {
    word: "pavement",
    sentences: [
      { id: 12137588, text: "There were a lot of children playing on the pavement." },
      { id: 320521, text: "One should not ride a bicycle on the pavement.", changed: true },
      { id: 6172571, text: "A layer of leaves lies on the pavement." },
    ],
  },
  {
    word: "brief",
    sentences: [
      { id: 326537, text: "There was a brief break in the discussion." },
      { id: 2820747, text: "There was a brief pause and then the music began." },
      { id: 2583302, text: "After a brief break, he continued his work." },
    ],
  },
  {
    word: "sore",
    sentences: [
      { id: 253314, text: "I have a sore throat from a cold." },
      { id: 12076658, text: "My legs are sore from walking all day." },
      { id: 7733465, text: "My arm is still very sore." },
    ],
  },
  {
    word: "sheets",
    sentences: [
      { id: 320679, text: "My mother put clean sheets on the bed." },
      { id: 5166395, text: "Please give me a pen and some sheets of paper." },
      { id: 324856, text: "Hand in the three sheets of paper together." },
    ],
  },
  {
    word: "pairs",
    sentences: [
      { id: 8419265, text: "How many pairs of shoes do you need?" },
      { id: 6351743, text: "I bought three pairs of shoes." },
      { id: 10632062, text: "How many pairs of boots do you have?" },
    ],
  },
  {
    word: "nuts",
    sentences: [
      { id: 3773319, text: "I love chocolates, especially those with nuts." },
      { id: 5906234, text: "The guests ate all the nuts." },
      { id: 13008678, text: "Do you want nuts or cheese?" },
    ],
  },
  {
    word: "lungs",
    sentences: [
      { id: 1746336, text: "Inside the chest, there are the heart and the lungs." },
      { id: 10457285, text: "The icy air burned her lungs." },
    ],
  },
  {
    word: "mass",
    sentences: [
      { id: 18326, text: "There is a mass of dark clouds in the sky." },
      { id: 64914, text: "People were gathering in a huge mass." },
    ],
  },
  {
    word: "pity",
    sentences: [
      { id: 4752665, text: "I took pity on her and lent her the money." },
      { id: 7913630, text: "My heart was filled with pity for him." },
      { id: 71622, text: "What a pity it is that you cannot come!", changed: true },
    ],
  },
  {
    word: "ankles",
    sentences: [
      { id: 10992861, text: "Tom and Mary have both twisted their ankles." },
      { id: 670477, text: "The long black coat reached almost to his ankles." },
      { id: 10360551, text: "I was wearing a red dress that went down to my ankles." },
    ],
  },
  {
    word: "hips",
    sentences: [
      { id: 7221581, text: "Mary stood with her hands on her hips." },
      { id: 10761353, text: "Put your hands on your hips." },
      { id: 3382695, text: "Tom has wide shoulders and narrow hips." },
    ],
  },
  {
    word: "proof",
    sentences: [
      { id: 6033301, text: "Do you have proof of that?" },
    ],
  },
  {
    word: "skinny",
    sentences: [
      { id: 2510145, text: "The dog is brown, small, and skinny." },
      { id: 8418741, text: "Tom is tall and skinny." },
      { id: 9999450, text: "Tom is a skinny kid." },
    ],
  },
  {
    word: "duty",
    sentences: [
      { id: 254063, text: "I felt it my duty to do so." },
      { id: 2308015, text: "I consider it my duty to help my parents." },
      { id: 7765382, text: "We have a duty not to forget history." },
    ],
  },
  {
    word: "dive",
    sentences: [
      { id: 8341470, text: "Tom watched Mary dive into the pool." },
      { id: 269502, text: "As we dive deeper, the water becomes colder." },
      { id: 11757937, text: "The submarine can dive at high speed." },
    ],
  },
  {
    word: "alert",
    sentences: [
      { id: 265523, text: "Be alert when you cross a busy street!" },
      { id: 20088, text: "You should be alert to the possible dangers." },
      { id: 266079, text: "The hunter was alert to every sound and movement." },
    ],
  },
  {
    word: "daylight",
    sentences: [
      { id: 3088530, text: "Tom got home just before daylight." },
      { id: 247106, text: "It was broad daylight when I woke up." },
    ],
  },
  {
    word: "cute",
    sentences: [
      { id: 7316824, text: "What a cute baby. How old is he?" },
      { id: 33003, text: "What a cute baby! May I hold her?" },
      { id: 12212611, text: "What a cute couple you make!" },
    ],
  },
  {
    word: "cheerful",
    sentences: [
      { id: 3825774, text: "Tom seems very happy and cheerful." },
      { id: 12129454, text: "Tom used to be cheerful, now he seems to be unhappy." },
      { id: 319182, text: "Father told me always to be brave and cheerful." },
    ],
  },
  {
    word: "groups",
    sentences: [
      { id: 1241169, text: "The students divided themselves into three groups." },
      { id: 272963, text: "Our teacher separated us into two groups." },
      { id: 12787094, text: "The teacher divided the class into smaller groups for the activity." },
    ],
  },
  {
    word: "events",
    sentences: [
      { id: 12772222, text: "How often do you attend sporting events?" },
      { id: 13957407, text: "The town council organises several cultural events throughout the year." },
      { id: 776203, text: "What kind of public events do you enjoy attending?" },
    ],
  },
  {
    word: "detail",
    sentences: [
      { id: 5659251, text: "Tom described what happened in great detail." },
      { id: 10116334, text: "Can you explain the steps in more detail?" },
      { id: 11357394, text: "Everything is planned down to the smallest detail!" },
    ],
  },
  {
    word: "pleasant",
    sentences: [
      { id: 853805, text: "What a pleasant surprise to see you here!" },
      { id: 248255, text: "We went to the party and had a pleasant time." },
      { id: 36096, text: "What a pleasant journey we had!" },
    ],
  },
  {
    word: "growl",
    sentences: [
      { id: 8340248, text: "Tom heard the dog growl." },
      { id: 7126583, text: "My stomach began to growl." },
      { id: 11826147, text: "The bear let out an even louder growl." },
    ],
  },
  {
    word: "sunny",
    sentences: [
      { id: 12371546, text: "The weather today is warm and sunny." },
      { id: 8543506, text: "Tom likes to sit on the grass on sunny days." },
      { id: 13825590, text: "I like the rain, but I prefer sunny days." },
    ],
  },
  {
    word: "jokes",
    sentences: [
      { id: 3049967, text: "Tom is good at telling jokes." },
      { id: 6258436, text: "Tom often laughs at his own jokes." },
      { id: 4570972, text: "Tom told a few jokes to warm up the audience." },
    ],
  },
  {
    word: "sandwiches",
    sentences: [
      { id: 9250905, text: "My mother made us cheese sandwiches for lunch." },
      { id: 2046912, text: "Tom is busy making sandwiches in the kitchen." },
      { id: 10569981, text: "I really like eating egg sandwiches." },
    ],
  },
  {
    word: "thoughtful",
    sentences: [
      { id: 3411005, text: "Tom is a very thoughtful person." },
      { id: 11641892, text: "Thank you for being so thoughtful." },
      { id: 3071458, text: "Tom is always thoughtful of his parents." },
    ],
  },
  {
    word: "opinion",
    sentences: [
      { id: 6098709, text: "Do you have an opinion on this issue?" },
      { id: 9751317, text: "Hear both sides of the story before forming any opinion." },
      { id: 2731642, text: "I have a high opinion of Tom." },
    ],
  },
  {
    word: "chat",
    sentences: [
      { id: 11616317, text: "We had a friendly short chat." },
      { id: 22521, text: "I had a little chat with John after the meeting." },
      { id: 11878398, text: "I would like to have a chat with you." },
    ],
  },
  {
    word: "valuable",
    sentences: [
      { id: 263955, text: "Which is more valuable, time or money?" },
      { id: 1312197, text: "A true friendship is more valuable than money." },
      { id: 13057116, text: "What is the most valuable thing that you own?" },
    ],
  },
  {
    word: "suits",
    sentences: [
      { id: 3099238, text: "Your new dress suits you very much." },
      { id: 3170755, text: "All the men were wearing dark suits and white shirts." },
      { id: 11632789, text: "I think this one suits you better than that one." },
    ],
  },
  {
    word: "false",
    sentences: [
      { id: 44044, text: "The report turned out to be false." },
      { id: 2121227, text: "Animals cannot distinguish between true and false.", changed: true },
      { id: 1989557, text: "The following sentence is true. The preceding sentence is false." },
    ],
  },
  {
    word: "piles",
    sentences: [
      { id: 13008461, text: "There were random piles of books." },
      { id: 2958112, text: "Tom separated the items into three piles." },
      { id: 9199656, text: "He has piles of books." },
    ],
  },
  {
    word: "crowds",
    sentences: [
      { id: 11661022, text: "The crowds began to gather." },
      { id: 3283846, text: "I made my way through the crowds of people." },
      { id: 3122563, text: "We walked to the next beach to get away from the crowds." },
    ],
  },
  {
    word: "exit",
    sentences: [
      { id: 12107283, text: "The exit door is on the right." },
      { id: 8269500, text: "Leave the building by the nearest exit, closing doors behind you." },
      { id: 12774673, text: "Which exit should I take?" },
    ],
  },
  {
    word: "reflection",
    sentences: [
      { id: 6858743, text: "Tom gazed at his reflection in the mirror." },
      { id: 2959499, text: "After much reflection, I decided not to accept the offer." },
    ],
  },
  {
    word: "patient",
    sentences: [
      { id: 11617167, text: "Please be a little more patient." },
      { id: 7156667, text: "Teachers should be very patient with students." },
      { id: 43416, text: "The old doctor gave individual attention to each patient." },
    ],
  },
  {
    word: "holidays",
    sentences: [
      { id: 21540, text: "School has closed for the Christmas holidays." },
      { id: 9128742, text: "School will soon break up for the summer holidays." },
      { id: 3122124, text: "We want to spend the holidays in a quiet place." },
    ],
  },
  {
    word: "eyebrow",
    sentences: [
      { id: 12768588, text: "He raised an eyebrow in surprise." },
    ],
  },
  {
    word: "gloves",
    sentences: [
      { id: 319195, text: "Father bought me a pair of gloves." },
      { id: 11498187, text: "I wish I had a pair of warm gloves." },
      { id: 2958341, text: "Tom took off his gardening gloves." },
    ],
  },
  {
    word: "giggle",
    sentences: [
      { id: 9162073, text: "What Tom said made Mary giggle." },
      { id: 7367744, text: "Tom started to giggle." },
      { id: 8495376, text: "This video made me giggle." },
    ],
  },
  {
    word: "unlikely",
    sentences: [
      { id: 6083864, text: "I think it is unlikely that will ever happen.", changed: true },
      { id: 8178002, text: "I still think it is unlikely Tom will win.", changed: true },
      { id: 8180384, text: "I think that it is unlikely Tom would ever move.", changed: true },
    ],
  },
  {
    word: "advantage",
    sentences: [
      { id: 11719183, text: "The player who goes first has an advantage." },
      { id: 737454, text: "The home team always have an advantage over their opponents." },
      { id: 295696, text: "The experience gave him an advantage over the others." },
    ],
  },
  {
    word: "range",
    sentences: [
      { id: 10849079, text: "Tom has a broad range of interests." },
      { id: 11638482, text: "We discussed a wide range of issues." },
      { id: 2959215, text: "Prices range from one to five dollars." },
    ],
  },
  {
    word: "feast",
    sentences: [
      { id: 6926564, text: "All the family gathered for a feast." },
      { id: 8120725, text: "The king held a feast in the great hall." },
      { id: 6213469, text: "All the villagers were invited to the feast." },
    ],
  },
  {
    word: "homes",
    sentences: [
      { id: 13397277, text: "People have to heat their homes in winter." },
      { id: 243864, text: "Many women work outside their homes these days." },
      { id: 2717934, text: "The settlers built their homes along the river." },
    ],
  },
  {
    word: "approach",
    sentences: [
      { id: 21914, text: "I will show you a new approach to foreign language learning." },
      { id: 4891491, text: "I suggest that we take a new approach." },
      { id: 12768158, text: "What if we take a different approach?" },
    ],
  },
  {
    word: "nails",
    sentences: [
      { id: 1747573, text: "When was the last time you cut your nails?" },
      { id: 8626727, text: "Why do women paint their nails?" },
      { id: 1210447, text: "I have a bad habit of biting my nails." },
    ],
  },
  {
    word: "spray",
    sentences: [
      { id: 12849496, text: "He waters the flowers with a spray bottle." },
      { id: 12667671, text: "We must spray them with cold water." },
    ],
  },
  {
    word: "covers",
    sentences: [
      { id: 279656, text: "Ice covers the lake during the winter." },
      { id: 24292, text: "The summer grass covers the ground." },
      { id: 240860, text: "A vast forest covers the mountains." },
    ],
  },
  {
    word: "response",
    sentences: [
      { id: 13252218, text: "There was no response to my request." },
      { id: 2888444, text: "Thank you for the quick response to my message." },
      { id: 11383678, text: "I called out to Tom, but I got no response." },
    ],
  },
  {
    word: "polished",
    sentences: [
      { id: 319249, text: "My father polished his car till it shone." },
      { id: 10287485, text: "I polished the floor and the furniture." },
      { id: 12079687, text: "His black shoes were well-polished." },
    ],
  },
  {
    word: "vegetables",
    sentences: [
      { id: 13503431, text: "You need to eat more fruits and vegetables." },
      { id: 8984945, text: "I bought fruit and vegetables at the market yesterday." },
      { id: 10903709, text: "I eat vegetables and fruit every morning." },
    ],
  },
  {
    word: "painful",
    sentences: [
      { id: 11929908, text: "Looking into the sun is really painful for the eyes." },
      { id: 9853906, text: "Is it painful to move like this?" },
      { id: 10031139, text: "At times it can get extremely painful." },
    ],
  },
  {
    word: "hills",
    sentences: [
      { id: 239991, text: "The lake is surrounded by green hills." },
      { id: 6330632, text: "The town is surrounded by hills." },
      { id: 48727, text: "The hills were covered with snow." },
    ],
  },
  {
    word: "sleepy",
    sentences: [
      { id: 9828485, text: "I get sleepy after eating a big meal." },
      { id: 8378514, text: "Do you often feel sleepy in the early afternoon?" },
      { id: 6257780, text: "Do you ever get sleepy in class?" },
    ],
  },
  {
    word: "hint",
    sentences: [
      { id: 3151339, text: "Let me give you a hint." },
      { id: 3153789, text: "Could you at least give me a hint?" },
      { id: 11576109, text: "A hint of a smile lit up his face." },
    ],
  },
  {
    word: "sizes",
    sentences: [
      { id: 60784, text: "This dress comes in three sizes." },
      { id: 10505991, text: "There were bags in various sizes." },
      { id: 6990481, text: "Heroes come in all shapes and sizes." },
    ],
  },
  {
    word: "patience",
    sentences: [
      { id: 12773889, text: "Few have the patience to wait so long." },
      { id: 10960063, text: "Have patience. You will find out very soon.", changed: true },
      { id: 6175252, text: "Now, above all, Tom must exercise patience." },
    ],
  },
  {
    word: "cracks",
    sentences: [
      { id: 3316617, text: "There are some cracks in the basement wall." },
      { id: 3872966, text: "Large cracks started to develop in the concrete." },
      { id: 12010567, text: "The fields dry up, and the soil cracks." },
    ],
  },
  {
    word: "argument",
    sentences: [
      { id: 4429425, text: "Did you and Tom have an argument today?" },
      { id: 2948350, text: "We had an argument about it last night." },
      { id: 11629132, text: "A heated argument developed between the four friends." },
    ],
  },
  {
    word: "handy",
    sentences: [
      { id: 265564, text: "A car is a handy thing to own." },
      { id: 10778653, text: "This tool will certainly come in handy." },
      { id: 953321, text: "Here. Take this with you. It might come in handy." },
    ],
  },
  {
    word: "fashion",
    sentences: [
      { id: 11537769, text: "When did hats go out of fashion?" },
      { id: 3424269, text: "Tom hopes to become a fashion designer." },
      { id: 56237, text: "Is this dress the latest fashion?" },
    ],
  },
  {
    word: "slippery",
    sentences: [
      { id: 6959324, text: "The floor is wet and slippery. Be careful!" },
      { id: 7023576, text: "Why do roads become slippery when it rains?" },
      { id: 9189290, text: "The wet floor is very slippery." },
    ],
  },
  {
    word: "upper",
    sentences: [
      { id: 30211, text: "The upper part of the mountain is covered with snow." },
      { id: 2610088, text: "The lower lip is bigger than the upper lip." },
      { id: 11239649, text: "Letters have two cases: upper case and lower case." },
    ],
  },
  {
    word: "drinks",
    sentences: [
      { id: 2795467, text: "I only like to drink cold drinks." },
      { id: 10625413, text: "Tom bought his daughters some cold drinks." },
      { id: 10087577, text: "Do not drink too many sugary drinks.", changed: true },
    ],
  },
  {
    word: "temper",
    sentences: [
      { id: 1028332, text: "Tom lost his temper and shouted at Mary." },
      { id: 2741473, text: "Tom tried to control his temper." },
      { id: 3478340, text: "Tom loses his temper quite easily." },
    ],
  },
  {
    word: "strangers",
    sentences: [
      { id: 11886171, text: "Do not talk to strangers and stay close to your group.", changed: true },
      { id: 10543317, text: "Do not tell strangers your name.", changed: true },
      { id: 1236432, text: "I am thankful for the kindness of strangers." },
    ],
  },
  {
    word: "pots",
    sentences: [
      { id: 10792158, text: "The flower pots were all filled with soil." },
      { id: 5012002, text: "Small pots have long handles." },
      { id: 11886210, text: "You need to use a pot holder when handling hot pots." },
    ],
  },
  {
    word: "arrival",
    sentences: [
      { id: 11262361, text: "With the arrival of spring, the plant world returns to life." },
      { id: 10263479, text: "With the arrival of winter, leaves fall from the trees." },
      { id: 287363, text: "Do you know the time of arrival of his plane?" },
    ],
  },
  {
    word: "remote",
    sentences: [
      { id: 3424104, text: "Tom handed Mary the remote control." },
      { id: 5022793, text: "The car broke down in some remote village." },
      { id: 12919000, text: "I used to live in a remote town." },
    ],
  },
  {
    word: "command",
    sentences: [
      { id: 320126, text: "The troops refused to obey the command." },
      { id: 251593, text: "My secretary has a good command of the English language." },
      { id: 2483344, text: "Does Tom have a good command of French?" },
    ],
  },
  {
    word: "concern",
    sentences: [
      { id: 50430, text: "The matter does not concern me." },
      { id: 3818058, text: "How does this concern you?" },
      { id: 12463803, text: "The situation gives cause for concern." },
    ],
  },
  {
    word: "handsome",
    sentences: [
      { id: 2045801, text: "Tom is a handsome young man." },
      { id: 10778193, text: "Tom looked very handsome in his new suit." },
      { id: 8440115, text: "You have a very handsome son." },
    ],
  },
  {
    word: "current",
    sentences: [
      { id: 9096731, text: "Have you read the current issue of this magazine?" },
      { id: 12993955, text: "I like my current situation as it is." },
      { id: 9836357, text: "Here is a list of current job openings." },
    ],
  },
  {
    word: "hopes",
    sentences: [
      { id: 7367637, text: "I have high hopes for the future." },
      { id: 5729927, text: "We have very high hopes for Tom." },
      { id: 1028633, text: "Tom hopes to meet Mary again in the near future." },
    ],
  },
  {
    word: "hopeful",
    sentences: [
      { id: 258626, text: "I feel hopeful about the future." },
      { id: 5591315, text: "We have every reason to be hopeful." },
      { id: 6521803, text: "Tom and Mary are very hopeful." },
    ],
  },
  {
    word: "dramatic",
    sentences: [
      { id: 2957641, text: "Tom paused for dramatic effect." },
      { id: 2665458, text: "We are in a phase of dramatic change." },
      { id: 10717693, text: "In the past few years, seasons have been subject to dramatic changes." },
    ],
  },
  {
    word: "diving",
    sentences: [
      { id: 11736384, text: "The water was deep enough for diving." },
      { id: 1889703, text: "Tom had the only pool in town with a diving board." },
      { id: 12764844, text: "Tom enjoyed diving into the deep blue ocean." },
    ],
  },
  {
    word: "manner",
    sentences: [
      { id: 10221391, text: "Answer him in a friendly manner!" },
      { id: 9159396, text: "Behave in a more positive manner." },
      { id: 6178895, text: "Your manner of speaking gave you away." },
    ],
  },
  {
    word: "steep",
    sentences: [
      { id: 8826722, text: "The way up the hill was very steep." },
      { id: 12911604, text: "I climbed a very steep hill." },
      { id: 2154898, text: "We climbed a steep slope." },
    ],
  },
  {
    word: "chances",
    sentences: [
      { id: 40598, text: "The chances are that you can pass the test." },
      { id: 65590, text: "The chances are very good that our team will win." },
      { id: 12771292, text: "Do you believe in second chances?" },
    ],
  },
  {
    word: "jobs",
    sentences: [
      { id: 1042139, text: "Many students have part-time jobs." },
      { id: 3424401, text: "We all have jobs to do." },
      { id: 8901456, text: "How many jobs can teachers do?" },
    ],
  },
  {
    word: "astonished",
    sentences: [
      { id: 248136, text: "We were astonished at the news." },
      { id: 311401, text: "She stood astonished at the sight." },
      { id: 7395308, text: "She was astonished by what she saw." },
    ],
  },
  {
    word: "thump",
    sentences: [
      { id: 12378972, text: "The book fell to the ground with a loud thump." },
      { id: 9944099, text: "A loud thump woke me up." },
      { id: 2360718, text: "I heard a thump." },
    ],
  },
  {
    word: "eerie",
    sentences: [
      { id: 11648547, text: "An eerie silence lay over the lake." },
      { id: 11693454, text: "The music sounded a little eerie." },
      { id: 4013301, text: "There was an eerie silence." },
    ],
  },
  {
    word: "favour",
    sentences: [
      { id: 6124, text: "Could you do me a favour please?" },
      { id: 2684415, text: "Would you mind doing me a favour?" },
      { id: 10694510, text: "Are you in favour of that policy or against it?" },
    ],
  },
  {
    word: "flap",
    sentences: [
      { id: 11816003, text: "Bees flap their wings to fly around." },
      { id: 11849596, text: "The tent flap was open." },
    ],
  },
]
