// SPDX-License-Identifier: CC-BY-2.0-FR
//
// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).
// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).
// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>
//
// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.
// "changed: true" means that we expanded a contraction, for example "don't" to "do not".
// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.

import type { TatoebaEntry } from '../bank'

export const TATOEBA_0005_BANK: readonly TatoebaEntry[] = [
  {
    word: "badge",
    sentences: [
      { id: 11211724, text: "Each of the boys wore a school badge on his hat." },
      { id: 276914, text: "Each boy student has a school badge on his cap." },
      { id: 3431066, text: "The police officer flashed his badge." },
    ],
  },
  {
    word: "edge",
    sentences: [
      { id: 39629, text: "Do not put the glass near the edge of the table.", changed: true },
      { id: 9803620, text: "We walked along the edge of the lake." },
      { id: 12916638, text: "I was standing on the edge of the woods." },
    ],
  },
  {
    word: "dodge",
    sentences: [
      { id: 540500, text: "On his bicycle he can dodge through traffic with amazing speed." },
      { id: 7810273, text: "Tom and Mary played dodge ball." },
    ],
  },
  {
    word: "fudge",
    sentences: [
      { id: 2494388, text: "My favourite type of food is chocolate fudge." },
      { id: 13625869, text: "This fudge is way too sweet for me." },
      { id: 2354302, text: "Fudge is not at all healthy, but it sure is amazingly tasty." },
    ],
  },
  {
    word: "age",
    sentences: [
      { id: 245725, text: "Children begin school at the age of six." },
      { id: 1027029, text: "Tom began living by himself at the age of sixteen." },
      { id: 680116, text: "What age was she when she first drove a car?" },
    ],
  },
  {
    word: "change",
    sentences: [
      { id: 892419, text: "The more things change, the more they stay the same." },
      { id: 2120971, text: "Do you think one person can change the world?" },
      { id: 262312, text: "I tried to change the subject." },
    ],
  },
  {
    word: "charge",
    sentences: [
      { id: 3392159, text: "How much do you charge for your services?" },
      { id: 13671648, text: "Tom will be in charge of preparing the food." },
      { id: 276381, text: "Who will take charge of their class?" },
    ],
  },
  {
    word: "giraffe",
    sentences: [
      { id: 8546706, text: "A giraffe could go weeks without water." },
      { id: 8559080, text: "How fast can a giraffe run?" },
    ],
  },
  {
    word: "energy",
    sentences: [
      { id: 7736928, text: "I feel young and full of energy." },
      { id: 7126834, text: "How do you save energy at home?" },
      { id: 6128448, text: "We need cleaner sources of energy." },
    ],
  },
  {
    word: "jar",
    sentences: [
      { id: 13717753, text: "Mother placed the sugar jar on the table." },
      { id: 39792, text: "Is there much sugar in the jar?" },
      { id: 7261366, text: "There is little milk in the jar." },
    ],
  },
  {
    word: "jog",
    sentences: [
      { id: 3439679, text: "Tom went for a morning jog." },
      { id: 325956, text: "The man next door said he goes for a jog every morning." },
      { id: 6531968, text: "I used to jog every day." },
    ],
  },
  {
    word: "join",
    sentences: [
      { id: 4529352, text: "Tom finally agreed to join the team." },
      { id: 852416, text: "Can foreign students join this club?" },
      { id: 11018428, text: "Can I join you for dinner?" },
    ],
  },
  {
    word: "adjust",
    sentences: [
      { id: 11892042, text: "You need to adjust the seat height on your bicycle." },
      { id: 482338, text: "Our eyes take time to adjust to the dark." },
      { id: 11881918, text: "Could you adjust the height of the table, please?" },
    ],
  },
  {
    word: "race",
    sentences: [
      { id: 11356898, text: "I ran really fast and won the race." },
      { id: 6660121, text: "I expected to win the race, but I lost." },
      { id: 11503414, text: "A cycling race will soon take place." },
    ],
  },
  {
    word: "fancy",
    sentences: [
      { id: 5674043, text: "What do you fancy for dinner?" },
      { id: 12882892, text: "Do you fancy going swimming with us this afternoon?" },
      { id: 10730790, text: "Do you fancy a bite to eat?" },
    ],
  },
  {
    word: "gnat",
    sentences: [
      { id: 11341028, text: "I was bitten by a gnat." },
    ],
  },
  {
    word: "gnaw",
    sentences: [
      { id: 9995488, text: "We all know that dogs like to gnaw on bones." },
    ],
  },
  {
    word: "written",
    sentences: [
      { id: 10862593, text: "Many books have been written about it." },
      { id: 6245299, text: "How many pages have you written so far?" },
      { id: 12142575, text: "Have you written lots of songs?" },
    ],
  },
  {
    word: "wrote",
    sentences: [
      { id: 2541208, text: "Tom sat down and wrote a letter." },
      { id: 13374285, text: "I wrote it down on paper." },
      { id: 6336041, text: "I wrote a long letter to Tom last night." },
    ],
  },
  {
    word: "wrong",
    sentences: [
      { id: 3818392, text: "Do you understand the difference between right and wrong?" },
    ],
  },
  {
    word: "apple",
    sentences: [
      { id: 9191823, text: "I try to eat an apple a day." },
      { id: 6665588, text: "Tom picked an apple and handed it to Mary." },
      { id: 13808929, text: "In the middle of the garden stands an apple tree." },
    ],
  },
  {
    word: "middle",
    sentences: [
      { id: 2268020, text: "The car stopped in the middle of the road." },
      { id: 3722343, text: "Tom drew a line down the middle of the page." },
      { id: 6024923, text: "Do you have a middle name?" },
    ],
  },
  {
    word: "camel",
    sentences: [
      { id: 8414780, text: "Tom saw a camel in the desert." },
      { id: 10566543, text: "Have you ever ridden a camel?" },
      { id: 11444713, text: "What does camel milk taste like?" },
    ],
  },
  {
    word: "tunnel",
    sentences: [
      { id: 245084, text: "A new tunnel has been dug through the mountain." },
      { id: 247495, text: "Our train went through a long tunnel." },
      { id: 8783187, text: "The tunnel runs through the mountain." },
    ],
  },
  {
    word: "squirrel",
    sentences: [
      { id: 7697555, text: "The squirrel quickly ran up the tree." },
      { id: 2826636, text: "A squirrel hid in the branches." },
      { id: 9448891, text: "The dog is chasing a squirrel." },
    ],
  },
  {
    word: "travel",
    sentences: [
      { id: 6528809, text: "I like to travel and visit new places." },
      { id: 258952, text: "I want to travel all over the world." },
      { id: 1735110, text: "How do you travel to work?" },
    ],
  },
  {
    word: "towel",
    sentences: [
      { id: 8597183, text: "Use this hand towel to dry your hands." },
      { id: 2540823, text: "Tom dried his hands with a towel." },
      { id: 10899982, text: "You can use that tea towel to dry the dishes." },
    ],
  },
  {
    word: "pedal",
    sentences: [
      { id: 11892465, text: "You need to pedal to move the bike." },
      { id: 10959825, text: "Press the pedal with your left foot." },
      { id: 12316220, text: "Pedal as fast as you can." },
    ],
  },
  {
    word: "capital",
    sentences: [
      { id: 13871043, text: "What is the capital of this country?" },
      { id: 12716354, text: "The capital is not the biggest city in the country.", changed: true },
      { id: 11688215, text: "The message was written in all capital letters." },
    ],
  },
  {
    word: "hospital",
    sentences: [
      { id: 6003794, text: "Tom took Mary to the nearest hospital." },
      { id: 4250327, text: "How long do I have to stay in the hospital?" },
      { id: 317377, text: "Will she be able to leave the hospital next week?" },
    ],
  },
  {
    word: "pencil",
    sentences: [
      { id: 25773, text: "Write with a pen, not with a pencil." },
      { id: 8910289, text: "Do you often draw with a pencil?" },
      { id: 13572500, text: "Please write your name in pencil." },
    ],
  },
  {
    word: "fossil",
    sentences: [
      { id: 6026146, text: "This museum has a large fossil collection." },
      { id: 2808756, text: "Tom found a fossil." },
    ],
  },
  {
    word: "try",
    sentences: [
      { id: 2238962, text: "I like to try new things." },
      { id: 2012098, text: "Do you want to try it on?" },
      { id: 418861, text: "I will try harder next time.", changed: true },
    ],
  },
  {
    word: "reply",
    sentences: [
      { id: 286631, text: "Should I reply to his letter?" },
      { id: 10738342, text: "You must reply to this letter immediately." },
      { id: 11620880, text: "A good question deserves a good reply." },
    ],
  },
  {
    word: "flies",
    sentences: [
      { id: 13759816, text: "As this bird has large wings, it flies really fast." },
      { id: 9828335, text: "A flying fish is not a bird, but a fish that flies.", changed: true },
      { id: 5685153, text: "Happiness is like a little bird: eventually, it flies away." },
    ],
  },
  {
    word: "tries",
    sentences: [
      { id: 7130511, text: "Tom always tries to make things better." },
      { id: 6427402, text: "Mary can do that if she tries." },
      { id: 3071452, text: "Tom made several tries, but failed each time." },
    ],
  },
  {
    word: "replies",
    sentences: [
      { id: 8614281, text: "He always replies to my comments." },
      { id: 11620877, text: "Tom usually replies to text messages within a few minutes." },
      { id: 3195488, text: "Your replies have been slow lately. Have you been busy?" },
    ],
  },
  {
    word: "copies",
    sentences: [
      { id: 1486383, text: "Tom bought two copies of the book." },
      { id: 58528, text: "Please make five copies of this document." },
      { id: 73208, text: "Please make three copies of each page." },
    ],
  },
  {
    word: "babies",
    sentences: [
      { id: 13990347, text: "Mothers put their babies to sleep." },
      { id: 11149670, text: "All the babies started crying at the same time." },
      { id: 27232, text: "Some babies learn to swim even before they are one year old." },
    ],
  },
  {
    word: "carries",
    sentences: [
      { id: 7540286, text: "Tom usually carries a bottle of water with him." },
      { id: 6409815, text: "Mary always carries a camera with her wherever she goes." },
      { id: 319707, text: "The wind carries seeds for great distances." },
    ],
  },
  {
    word: "copied",
    sentences: [
      { id: 2199778, text: "My friend copied my homework and the teacher found out." },
      { id: 272118, text: "In early times all books were copied by hand." },
      { id: 13077221, text: "John copied the sentences." },
    ],
  },
  {
    word: "happier",
    sentences: [
      { id: 8936290, text: "Since her visit he seems much happier." },
      { id: 2698701, text: "How can I make you happier?" },
      { id: 2044805, text: "Would you be happier if I stayed?" },
    ],
  },
  {
    word: "happiest",
    sentences: [
      { id: 256515, text: "I feel happiest when I am at home with my family." },
      { id: 1867391, text: "I am the happiest person in the world!" },
      { id: 12572069, text: "What was the happiest time of your life?" },
    ],
  },
  {
    word: "replied",
    sentences: [
      { id: 276639, text: "No one replied to the question." },
      { id: 12933883, text: "I replied that I was coming." },
      { id: 11554592, text: "When she asked if he was tired, he replied that he was." },
    ],
  },
  {
    word: "copying",
    sentences: [
      { id: 2847771, text: "I am not copying your homework.", changed: true },
      { id: 58521, text: "In copying this paper, be careful not to leave out any words." },
      { id: 13816356, text: "We were copying a sentence." },
    ],
  },
  {
    word: "crying",
    sentences: [
      { id: 9843777, text: "I think I hear a baby crying." },
      { id: 45839, text: "The baby kept crying all night." },
      { id: 6420741, text: "Mary started crying when she fell down." },
    ],
  },
  {
    word: "replying",
    sentences: [
      { id: 2958440, text: "Tom waited a moment before replying." },
      { id: 5907755, text: "I spent all afternoon replying to emails." },
      { id: 3466432, text: "Why did she stop replying to me?" },
    ],
  },
  {
    word: "hiking",
    sentences: [
      { id: 12764601, text: "Mary loves hiking in the mountains during the spring." },
      { id: 12783233, text: "How many times have you gone hiking in the mountains?" },
      { id: 9972214, text: "Are there any good places to go hiking around here?" },
    ],
  },
  {
    word: "hiked",
    sentences: [
      { id: 8843735, text: "Tom and Mary hiked through the forest." },
      { id: 12764620, text: "Mary hiked up the tallest mountain in the area." },
      { id: 682304, text: "We hiked through a beautiful green valley." },
    ],
  },
  {
    word: "hiker",
    sentences: [
      { id: 681524, text: "The hiker has reached the top of the mountain." },
    ],
  },
  {
    word: "nicer",
    sentences: [
      { id: 12623202, text: "The weather is nicer today than yesterday." },
      { id: 3120634, text: "The new library is nicer than the old library." },
      { id: 6671415, text: "Your house is nicer than mine." },
    ],
  },
  {
    word: "nicest",
    sentences: [
      { id: 1397668, text: "This is the nicest present I have ever received.", changed: true },
      { id: 12789722, text: "What is the nicest thing someone has done for you?", changed: true },
      { id: 9396615, text: "Tom is one of the nicest men I know." },
    ],
  },
  {
    word: "shiny",
    sentences: [
      { id: 6603861, text: "Mary has long, shiny hair." },
      { id: 11819149, text: "I bought you a pair of shiny shoes." },
      { id: 5990343, text: "Tom saw something shiny in the water." },
    ],
  },
  {
    word: "patting",
    sentences: [
      { id: 1662714, text: "Tom is patting his dog." },
      { id: 1665744, text: "I am patting my cat." },
      { id: 254990, text: "I felt somebody patting on my shoulder from behind." },
    ],
  },
  {
    word: "patted",
    sentences: [
      { id: 12769971, text: "Tom patted the horse." },
      { id: 272987, text: "The teacher patted me on the back." },
      { id: 12256249, text: "I patted him on the shoulder." },
    ],
  },
  {
    word: "humming",
    sentences: [
      { id: 9410616, text: "What is that tune you are humming?", changed: true },
      { id: 7379401, text: "Mary started humming to herself." },
      { id: 8557214, text: "Tom was in the kitchen humming to himself." },
    ],
  },
  {
    word: "hummed",
    sentences: [
      { id: 248310, text: "We all hummed to the music." },
      { id: 7258068, text: "Tom hummed along with the song." },
      { id: 315010, text: "She hummed her child to sleep." },
    ],
  },
  {
    word: "dropping",
    sentences: [
      { id: 25454, text: "Leaves were dropping silently to the ground." },
      { id: 13293204, text: "The temperature outside is slowly dropping." },
      { id: 11882380, text: "Avoid dropping the remote on the floor." },
    ],
  },
  {
    word: "dropped",
    sentences: [
      { id: 13471549, text: "The temperature has dropped quite a bit since this morning." },
      { id: 5483629, text: "The population of the city dropped by a third." },
    ],
  },
  {
    word: "sadder",
    sentences: [
      { id: 10456156, text: "This sad summer is even sadder without you." },
    ],
  },
  {
    word: "saddest",
    sentences: [
      { id: 11322141, text: "She was singing the saddest song." },
      { id: 3938908, text: "What is the saddest song in the world?", changed: true },
      { id: 43307, text: "The saddest part of the story remains to be told." },
    ],
  },
  {
    word: "fatter",
    sentences: [
      { id: 3309037, text: "Tom seems to be getting fatter." },
      { id: 11908335, text: "Tom is a lot fatter than he used to be." },
      { id: 6602098, text: "All over the world, people are growing fatter." },
    ],
  },
  {
    word: "fattest",
    sentences: [
      { id: 1093429, text: "Tom is the fattest man I know." },
    ],
  },
  {
    word: "runner",
    sentences: [
      { id: 9220354, text: "Tom is the fastest runner on the team." },
      { id: 11040313, text: "Tom was the last runner to cross the finish line." },
      { id: 10118082, text: "Tom is a really fast runner." },
    ],
  },
  {
    word: "runny",
    sentences: [
      { id: 6024931, text: "Tom has a runny nose." },
      { id: 10893495, text: "This egg is too runny." },
      { id: 318203, text: "My nose was very runny." },
    ],
  },
  {
    word: "call",
    sentences: [
      { id: 434374, text: "Can I make a phone call?" },
      { id: 2148918, text: "Until what time can I call you on the phone?" },
      { id: 3133928, text: "What do they call this girl?" },
    ],
  },
  {
    word: "talk",
    sentences: [
      { id: 930425, text: "Do not talk to others during class!" },
      { id: 1886262, text: "Can we talk about this later?" },
      { id: 980726, text: "I need someone to talk to." },
    ],
  },
  {
    word: "donkey",
    sentences: [
      { id: 3590752, text: "Why does the donkey have such long ears?" },
      { id: 8976684, text: "Tom wanted to ride the donkey." },
      { id: 12293552, text: "We brought water on a donkey." },
    ],
  },
  {
    word: "monkey",
    sentences: [
      { id: 25874, text: "A monkey is climbing up a tall tree." },
      { id: 9189918, text: "I see a monkey without a tail." },
      { id: 8580315, text: "Tom has a pet monkey." },
    ],
  },
  {
    word: "chimney",
    sentences: [
      { id: 12943553, text: "The chimney blew off the roof." },
      { id: 10022517, text: "Tom is cleaning the chimney." },
    ],
  },
  {
    word: "watch",
    sentences: [
      { id: 4889959, text: "Do you watch the news every day?" },
      { id: 11679948, text: "I want to watch that film again." },
      { id: 3185355, text: "Can you stay and watch the children?" },
    ],
  },
  {
    word: "wander",
    sentences: [
      { id: 12244870, text: "I like to wander through the forest." },
      { id: 11053822, text: "In the evenings, we would wander around the city centre." },
      { id: 9957222, text: "I had some free time, so I decided to wander around town." },
    ],
  },
  {
    word: "quantity",
    sentences: [
      { id: 36866, text: "What quantity of paper do you need?" },
      { id: 249050, text: "We import a large quantity of food." },
      { id: 325900, text: "Quality is more important than quantity." },
    ],
  },
  {
    word: "squash",
    sentences: [
      { id: 1725129, text: "I cannot squash flies with my book." },
      { id: 3667554, text: "Do you play squash?" },
      { id: 3983923, text: "Do you like squash soup?" },
    ],
  },
  {
    word: "word",
    sentences: [
      { id: 9476376, text: "Without saying another word, Tom left the room." },
      { id: 5807219, text: "Tom believes every word I say." },
      { id: 3219240, text: "Tom left without saying a word." },
    ],
  },
  {
    word: "work",
    sentences: [
      { id: 29075, text: "I have a lot of work to do." },
      { id: 263442, text: "I must work hard to pass the test." },
      { id: 909514, text: "Do you spend more time at home or at work?" },
    ],
  },
  {
    word: "worm",
    sentences: [
      { id: 6009199, text: "The worm is being eaten by a bird." },
      { id: 4976739, text: "Tom found a worm hiding behind the rock." },
      { id: 1830613, text: "I ate half the apple before I noticed there was a worm in it." },
    ],
  },
  {
    word: "towards",
    sentences: [
      { id: 8920099, text: "The train was heading towards the station." },
      { id: 12918865, text: "I was walking towards the front of the car." },
      { id: 1426338, text: "Vegetables slowly lean towards the light." },
    ],
  },
  {
    word: "treasure",
    sentences: [
      { id: 10142276, text: "Tom is digging for buried treasure." },
      { id: 4663493, text: "Are you still hunting for buried treasure?" },
      { id: 12984813, text: "The old map hinted at a treasure hidden deep in the forest." },
    ],
  },
  {
    word: "usual",
    sentences: [
      { id: 6657597, text: "I got to work earlier than usual this morning." },
      { id: 9689453, text: "As usual, Tom was late again this morning." },
      { id: 10359629, text: "I went to bed earlier than usual last night." },
    ],
  },
  {
    word: "enjoyment",
    sentences: [
      { id: 259556, text: "I find much enjoyment in fishing." },
      { id: 280628, text: "Reading is a great enjoyment to him." },
      { id: 25416, text: "The music added to our enjoyment." },
    ],
  },
  {
    word: "sadness",
    sentences: [
      { id: 13203472, text: "Life is filled with moments of joy and sadness." },
      { id: 8282526, text: "I saw the sadness in your eyes." },
      { id: 12293472, text: "Our hearts are full of sadness." },
    ],
  },
  {
    word: "playful",
    sentences: [
      { id: 10823052, text: "Why are cats so playful?" },
      { id: 11644078, text: "She is a really playful cat.", changed: true },
      { id: 9248585, text: "Tom is in a playful mood." },
    ],
  },
  {
    word: "plain",
    sentences: [
      { id: 2890400, text: "Mary wore a plain white dress." },
      { id: 3170635, text: "Tom handed Mary a plain white envelope." },
      { id: 320147, text: "Written in plain English, this book is easy to read." },
    ],
  },
  {
    word: "badly",
    sentences: [
      { id: 10159186, text: "Tom was injured, but not too badly." },
      { id: 4643047, text: "How did you get hurt so badly?" },
      { id: 5834879, text: "How badly do you want this?" },
    ],
  },
  {
    word: "happiness",
    sentences: [
      { id: 243187, text: "May the new year bring you happiness!" },
      { id: 63595, text: "Money does not always bring happiness." },
      { id: 11122539, text: "How can I find happiness in life?" },
    ],
  },
  {
    word: "plentiful",
    sentences: [
      { id: 23310, text: "We have a plentiful supply of water." },
    ],
  },
  {
    word: "penniless",
    sentences: [
      { id: 323905, text: "The problem is that he is penniless." },
      { id: 2259892, text: "When his business failed, he was left penniless." },
      { id: 245336, text: "The failure in business left me penniless." },
    ],
  },
  {
    word: "happily",
    sentences: [
      { id: 44634, text: "The two young girls smiled happily." },
      { id: 3939178, text: "And they lived happily ever after." },
      { id: 22075, text: "Everybody in the picture is smiling happily." },
    ],
  },
  {
    word: "fiction",
    sentences: [
      { id: 7127118, text: "How can you tell fact from fiction?" },
      { id: 10471004, text: "I like reading science fiction novels." },
      { id: 263756, text: "Fact is stranger than fiction." },
    ],
  },
  {
    word: "motion",
    sentences: [
      { id: 6331228, text: "Everything seemed to be happening in slow motion." },
      { id: 66155, text: "When will this machine be put in motion again?" },
      { id: 46190, text: "I want to see the scene in slow motion." },
    ],
  },
  {
    word: "national",
    sentences: [
      { id: 9505395, text: "Every country has a national flag." },
      { id: 248693, text: "We put up the flags on national holidays." },
      { id: 13502214, text: "How many national parks have you been to?" },
    ],
  },
  {
    word: "section",
    sentences: [
      { id: 13045125, text: "I only read the sports section of the newspaper." },
      { id: 9086233, text: "Which section of the newspaper are you most interested in?" },
      { id: 11427791, text: "Where is the pet care section of this store?" },
    ],
  },
  {
    word: "won",
    sentences: [
      { id: 12501570, text: "I played the game, and I won!" },
      { id: 23460, text: "We won the game by three goals to one." },
      { id: 8857219, text: "Do you know who won the race?" },
    ],
  },
  {
    word: "two",
    sentences: [
      { id: 1673283, text: "Why do you have only two cars?" },
      { id: 512912, text: "The play lasts two and a half hours." },
      { id: 1272498, text: "I have not eaten for two days.", changed: true },
    ],
  },
  {
    word: "bee",
    sentences: [
      { id: 684745, text: "The bee flew to the flower." },
      { id: 4305527, text: "The bee landed on a flower." },
      { id: 11658164, text: "A bee is not a bird." },
    ],
  },
  {
    word: "blew",
    sentences: [
      { id: 668550, text: "The leaves blew away in the wind." },
      { id: 10113362, text: "The wind blew the roofs off the houses." },
      { id: 8855837, text: "A fresh wind blew away the dark clouds." },
    ],
  },
  {
    word: "knight",
    sentences: [
      { id: 10708861, text: "Look at that knight riding a horse." },
      { id: 13932066, text: "The brave knight was more popular than the king and the queen." },
      { id: 9216660, text: "Tom dressed up as a knight." },
    ],
  },
  {
    word: "forgetting",
    sentences: [
      { id: 7989552, text: "Why do you keep forgetting to lock the door?" },
      { id: 6377465, text: "I keep forgetting his name." },
      { id: 11880441, text: "Am I forgetting anything else?" },
    ],
  },
  {
    word: "forgotten",
    sentences: [
      { id: 11421481, text: "Come on! Have you forgotten how to laugh?" },
      { id: 12187989, text: "Have you forgotten what happened here last year?" },
      { id: 12526977, text: "Have you really forgotten about it?" },
    ],
  },
  {
    word: "beginning",
    sentences: [
      { id: 10314794, text: "Can you start from the beginning?" },
      { id: 2966881, text: "Have you read the whole paper from beginning to end?" },
      { id: 2258786, text: "I know the story from beginning to end." },
    ],
  },
  {
    word: "beginner",
    sentences: [
      { id: 5354660, text: "She is a beginner, but she is learning fast." },
      { id: 11840273, text: "Riding a horse is tough for a beginner." },
      { id: 12232895, text: "I am a beginner, but I learn fast.", changed: true },
    ],
  },
  {
    word: "prefer",
    sentences: [
      { id: 1266434, text: "Which do you prefer: this one or that one?" },
      { id: 6912427, text: "Do you prefer eating out or eating at home?" },
      { id: 4806953, text: "Which language would you prefer to use?" },
    ],
  },
  {
    word: "preferred",
    sentences: [
      { id: 7818590, text: "When Tom was young, he preferred tea to coffee." },
      { id: 10186917, text: "Tom said that he preferred to sit on the ground." },
      { id: 1798857, text: "I preferred to write in English." },
    ],
  },
  {
    word: "gardening",
    sentences: [
      { id: 3725980, text: "I have a lot of gardening to do." },
      { id: 6579093, text: "Tom spends his time gardening and writing." },
      { id: 12251945, text: "Have you been doing any gardening?" },
    ],
  },
  {
    word: "gardener",
    sentences: [
      { id: 8819545, text: "The gardener planted a rose in the centre of the garden." },
      { id: 268581, text: "I had the gardener plant some trees." },
      { id: 7544364, text: "Tom is a very good gardener." },
    ],
  },
  {
    word: "limited",
    sentences: [
      { id: 11415174, text: "You have a limited amount of time." },
      { id: 12982621, text: "I usually have limited free time." },
      { id: 8352132, text: "Food and water are extremely limited." },
    ],
  },
  {
    word: "gym",
    sentences: [
      { id: 12926917, text: "To be fit, you need to go to the gym." },
      { id: 11575045, text: "I want to go to the gym to keep fit." },
      { id: 12772215, text: "How often do you go to the gym?" },
    ],
  },
  {
    word: "pyramid",
    sentences: [
      { id: 49451, text: "The shape of the roof looks like a pyramid." },
      { id: 9366982, text: "Did you go to the top of the pyramid?" },
      { id: 6769270, text: "The students formed a human pyramid." },
    ],
  },
  {
    word: "mystery",
    sentences: [
      { id: 6078496, text: "Can you help solve this mystery?" },
      { id: 8588049, text: "Why that happens is still a mystery." },
      { id: 1137862, text: "Has anyone solved that mystery?" },
    ],
  },
  {
    word: "young",
    sentences: [
      { id: 1934884, text: "The young boy helped the old woman." },
      { id: 2735261, text: "The young men play and the old men watch." },
      { id: 9483196, text: "What do old people eat that young people do not?", changed: true },
    ],
  },
  {
    word: "double",
    sentences: [
      { id: 282483, text: "I will pay double the price.", changed: true },
      { id: 9855591, text: "There is only a double bed.", changed: true },
      { id: 11886774, text: "You should double-check your homework for errors." },
    ],
  },
  {
    word: "trouble",
    sentences: [
      { id: 253163, text: "I always have trouble remembering names." },
      { id: 5909675, text: "You seem to be having trouble walking." },
      { id: 61543, text: "Do not say anything that might get you into trouble.", changed: true },
    ],
  },
  {
    word: "country",
    sentences: [
      { id: 4491228, text: "Which country do you come from?" },
      { id: 11005638, text: "I want to visit every country in the world." },
      { id: 8838547, text: "Do you live in a town or in the country?" },
    ],
  },
  {
    word: "disappoint",
    sentences: [
      { id: 304737, text: "He is studying hard in order not to disappoint his parents." },
      { id: 242366, text: "I will try not to disappoint you next time.", changed: true },
      { id: 297392, text: "He raised our expectations only to disappoint us." },
    ],
  },
  {
    word: "disagree",
    sentences: [
      { id: 13446213, text: "I respect your opinions, even when we disagree." },
      { id: 8559967, text: "I strongly disagree with what you said." },
      { id: 6018533, text: "We disagree on many things, but we are still good friends.", changed: true },
    ],
  },
  {
    word: "disobey",
    sentences: [
      { id: 1260984, text: "Do not disobey the rules." },
      { id: 9939427, text: "Tom does not usually disobey his parents.", changed: true },
      { id: 2643093, text: "Why did you disobey my order?" },
    ],
  },
  {
    word: "misbehave",
    sentences: [
      { id: 7114848, text: "If you misbehave, you will not get anything." },
      { id: 12611162, text: "I do not want you to misbehave during dinner time.", changed: true },
      { id: 10819499, text: "The teacher let the kids misbehave." },
    ],
  },
  {
    word: "mislead",
    sentences: [
      { id: 13020566, text: "First impressions can mislead you." },
      { id: 12067813, text: "Are you trying to mislead me?" },
      { id: 5251723, text: "I do not want to mislead you.", changed: true },
    ],
  },
  {
    word: "misspell",
    sentences: [
      { id: 8441024, text: "Which word did I misspell?" },
      { id: 5066831, text: "I do not want to misspell anything.", changed: true },
    ],
  },
  {
    word: "spell",
    sentences: [
      { id: 4997283, text: "Can you spell your name for me?" },
      { id: 12396716, text: "Could you please tell me how to spell your name?" },
      { id: 9988711, text: "Can you spell that, please?" },
    ],
  },
  {
    word: "immature",
    sentences: [
      { id: 1941194, text: "He is young and immature." },
      { id: 10683997, text: "Tom is very immature for his age." },
      { id: 602057, text: "My brother is an immature boy." },
    ],
  },
  {
    word: "immortal",
    sentences: [
      { id: 3823601, text: "No one is immortal." },
      { id: 1874019, text: "Do you really want to be immortal?" },
      { id: 11028365, text: "If you eat the fruit, you will become immortal.", changed: true },
    ],
  },
  {
    word: "impossible",
    sentences: [
      { id: 8212129, text: "Is it impossible to build a city in one day?" },
      { id: 2952307, text: "I knew it would be impossible for me to win." },
      { id: 11948816, text: "We were able to do what, at first, seemed impossible." },
    ],
  },
  {
    word: "impatient",
    sentences: [
      { id: 275313, text: "The longer we waited, the more impatient we became." },
      { id: 21438, text: "Students are impatient for the summer holidays to come." },
      { id: 263506, text: "I was impatient for the game to start." },
    ],
  },
  {
    word: "imperfect",
    sentences: [
      { id: 907008, text: "We are all imperfect. We cannot expect perfect government." },
    ],
  },
  {
    word: "irresponsible",
    sentences: [
      { id: 6381955, text: "Tom is too irresponsible to have a pet." },
      { id: 9617149, text: "You cannot trust him with anything. He is very irresponsible.", changed: true },
      { id: 7129687, text: "Do you really think that Tom is irresponsible?" },
    ],
  },
]
