import type { BankEntry } from '../bank'

// A third sentence for each common exception word of years 1 and 2 that has only 2. Our own work (CC0).
// The rule in CLAUDE.md gives each word a minimum of 3 sentences, so that the teacher has a choice.
// mergeEntries in src/sentences/bank.ts joins these sentences with the sentences in commonExceptionWords.ts.
export const WRITTEN_EXCEPTION_EXTRA_BANK: readonly BankEntry[] = [
  { word: 'said', sentences: ['After I asked for help, my friend said that he would come.'] },
  { word: 'says', sentences: ['The sign says stop, and it tells the driver to wait.'] },
  { word: 'she', sentences: ['The girl put on her coat, and then she ran outside.'] },
  { word: 'here', sentences: ['Put the box here, in this room, and not in the garden.'] },
  { word: 'love', sentences: ['I love my dog, and I like my cat too.'] },
  { word: 'come', sentences: ['Come to the park with us, and then we can go home.'] },
  { word: 'once', sentences: ['Once a year, in the summer, we go to the beach.'] },
  { word: 'ask', sentences: ['If you do not understand, ask your teacher for the answer.'] },
  { word: 'put', sentences: ['Put the plate on the table, and do not drop it.'] },
  { word: 'full', sentences: ['The glass is full of water, right to the top.'] },
  { word: 'poor', sentences: ['A poor country needs help, but a rich country does not.'] },
  { word: 'find', sentences: ['Look in every room, and you will find your lost shoe.'] },
  { word: 'kind', sentences: ['It was kind of you to help, and I say thank you.'] },
  { word: 'mind', sentences: ['Keep the rule in your mind, and do not forget it.'] },
  { word: 'behind', sentences: ['My bag is behind the door, at the back of the room.'] },
  { word: 'children', sentences: ['The children in my class are boys and girls.'] },
  { word: 'most', sentences: ['She had the most sweets, more than anyone else.'] },
  { word: 'only', sentences: ['The shop had only one apple left, and no more.'] },
  { word: 'both', sentences: ['Both of my shoes are wet, the left one and the right one.'] },
  { word: 'old', sentences: ['This old book is from the past, and it is not new.'] },
  { word: 'hold', sentences: ['Hold the bag tight, and keep your hands closed.'] },
  { word: 'told', sentences: ['He told me the news, and I said thank you.'] },
  { word: 'every', sentences: ['Brush your teeth every morning and every night.'] },
  { word: 'everybody', sentences: ['When everybody sings, everyone in the hall can hear.'] },
  { word: 'even', sentences: ['The rain was bad, and it was even worse at night.'] },
  { word: 'steak', sentences: ['A steak is a thick piece of meat.'] },
  { word: 'last', sentences: ['This is the last day of the holiday, and the first day of school.'] },
  { word: 'pass', sentences: ['You must pass the test before you move to the next class.'] },
  { word: 'path', sentences: ['A path is a narrow road for people to walk on.'] },
  { word: 'hour', sentences: ['An hour is much longer than a minute.'] },
  { word: 'move', sentences: ['Do not move, and stay still in one place.'] },
  { word: 'prove', sentences: ['Test the plan to prove that it works.'] },
  { word: 'improve', sentences: ['If you improve your spelling, your work will get better.'] },
  { word: 'sure', sentences: ['I am not sure, because I do not know the answer.'] },
  { word: 'should', sentences: ['You should listen to the teacher, and you must be quiet.'] },
  { word: 'whole', sentences: ['The whole class, all thirty children, went on the trip.'] },
  { word: 'many', sentences: ['Many days are hot, but a few days are cold.'] },
  { word: 'people', sentences: ['A crowd of people filled the street.'] },
  { word: 'again', sentences: ['Try again, and do not give up after one try.'] },
  { word: 'half', sentences: ['Cut the cake in half, so we get one piece each.'] },
  { word: 'mr', sentences: ['Mr Green is a man, and Mrs Green is his wife.'] },
  { word: 'mrs', sentences: ['Mrs Green is a woman, and Mr Green is her husband.'] },
  { word: 'parents', sentences: ['Children live at home with their parents.'] },
  { word: 'christmas', sentences: ['Christmas comes in the winter, and we put up a tree.'] },
]
