// Write a sentence bank data file from the chosen Tatoeba candidates.
// Run from tools/mining: node node_modules/tsx/dist/cli.mjs writeBank.ts --batch 0-300 --name tatoeba0001
//
// Input:
// - ../../.cache/mining/candidates-<batch>.json, from mineTatoeba.ts.
// - ../../.cache/mining/selection-<batch>.json: { "<word>": [<Tatoeba id>, ...] }. Claude reads the candidates and
//   writes this file. The order of the ids is the order of the sentences in the bank.
// Output: ../../src/sentences/bank/<name>.ts

import { readFileSync, writeFileSync } from 'node:fs'

type Candidate = { readonly id: number; readonly text: string; readonly changed: boolean; readonly context: number }
type WordCandidates = { readonly word: string; readonly candidates: readonly Candidate[] }

const argument = (name: string): string => {
  const index = process.argv.indexOf(`--${name}`)
  if (index === -1 || process.argv[index + 1] === undefined) throw new Error(`Give --${name}`)
  return process.argv[index + 1]
}

const batch = argument('batch')
const name = argument('name')
const constantName = `${name.replace(/([a-z])([0-9])/g, '$1_$2').toUpperCase()}_BANK`

const results = JSON.parse(readFileSync(`../../.cache/mining/candidates-${batch}.json`, 'utf8')) as WordCandidates[]
const selection = JSON.parse(readFileSync(`../../.cache/mining/selection-${batch}.json`, 'utf8')) as Record<string, number[]>
const byWord = new Map(results.map((result) => [result.word, new Map(result.candidates.map((c) => [c.id, c]))]))

const NEWLINE = String.fromCharCode(10)
const quote = (text: string): string => JSON.stringify(text)

const entries = Object.entries(selection).map(([word, ids]) => {
  const candidates = byWord.get(word)
  if (!candidates) throw new Error(`The batch ${batch} has no candidates for "${word}"`)
  const sentences = ids.map((id) => {
    const candidate = candidates.get(id)
    if (!candidate) throw new Error(`"${word}" has no candidate with the id ${id}`)
    return `      { id: ${id}, text: ${quote(candidate.text)}${candidate.changed ? ', changed: true' : ''} },`
  })
  return [`  {`, `    word: ${quote(word)},`, `    sentences: [`, ...sentences, `    ],`, `  },`].join(NEWLINE)
})

const file = [
  '// SPDX-License-Identifier: CC-BY-2.0-FR',
  '//',
  '// Sentences from Tatoeba (https://tatoeba.org), licensed under CC BY 2.0 FR (https://creativecommons.org/licenses/by/2.0/fr/).',
  '// Source: https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences_detailed.tsv.bz2 (export of 2026-09-12).',
  '// The id of each sentence finds it on Tatoeba: https://tatoeba.org/en/sentences/show/<id>',
  '//',
  '// Changes: tools/mining/mineTatoeba.ts found and scored the sentences, and Claude chose them.',
  '// "changed: true" means that we expanded a contraction, for example "don\'t" to "do not".',
  '// Generated by tools/mining/writeBank.ts. Change the selection and generate the file again.',
  '',
  "import type { TatoebaEntry } from '../bank'",
  '',
  `export const ${constantName}: readonly TatoebaEntry[] = [`,
  ...entries,
  ']',
  '',
].join(NEWLINE)

writeFileSync(`../../src/sentences/bank/${name}.ts`, file)
console.log(`wrote src/sentences/bank/${name}.ts with ${entries.length} words`)
